{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250713+2/kmpotest-20250713+2.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250713+2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-iosArm64Main-20250713+2.klib",
          "url": "kmpotest-iosarm64-20250713+2.klib",
          "size": 38161,
          "sha512": "cbf7020c8a94c7dfbd71088504e55a8d0f9f6087b2518f14833f83cab9ac36be27d22ed69ac94c3e19c81b5bca11ddc3228e920e9b1a828aecceaebe4bb46f7d",
          "sha256": "b41e75a919f3ebc87a10b338cb91aa87bd80e646ce09256fee382352ffb6216e",
          "sha1": "f8057eebc32787962c250ef51cf89c4e21f964e7",
          "md5": "2f2f3a56f9422234542fe5edf070c3fc"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-iosarm64-20250713+2-sources.jar",
          "url": "kmpotest-iosarm64-20250713+2-sources.jar",
          "size": 3842,
          "sha512": "79872ead0ea119c3c4de94f213963ff6127248d7037870cc64ee49c405e680a3f93e3c4f16cf7cc508f39c96f30f0869c919e1a525c0e1b723484e5b3900c220",
          "sha256": "0b58721e921481599dfa2de37430e14bba87ba8918a768581c09df49466c1edd",
          "sha1": "7238d2b12b4c226418399c0e6ff076b28ae092a4",
          "md5": "260e94e019f90fdc15d86f7999597461"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-iosarm64-20250713+2-metadata.jar",
          "url": "kmpotest-iosarm64-20250713+2-metadata.jar",
          "size": 261,
          "sha512": "15c04c3e7115fc5d7afd6326e0b95017c36bba824299e54eb2e673157c17000740984c4957be583ca10ca94d1ed4a6f52cd90ea991bf43d52eda9a323360d69c",
          "sha256": "ab59b6e3eb9c0874944626577742285aa222885502895e411fa1b85d0b8676b1",
          "sha1": "994f76958d49547c960da0318a6e77ea6cd2dba7",
          "md5": "4d112bb0ea6233abe0edc2590ad83f71"
        }
      ]
    }
  ]
}
