{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250714/kmpotest-20250714.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250714",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosArm32Main-20250714.klib",
          "url": "kmpotest-watchosarm32-20250714.klib",
          "size": 38195,
          "sha512": "04bba8c0558b56521291508896fddbc510a6ae39fb1c1a47e8918e8128b2f395faff4262f2f7b160aa2a7ba9f9d6c6519a3e25aab930992fb613ff6017cb5aaf",
          "sha256": "39136dd5baa13c0041039f1876ad0b262e6c045b9c419d7b6be1022eb5233370",
          "sha1": "1ca59f171c8b694a27b94fde5274277e54491e39",
          "md5": "d29c3065e61f099213839168b75c7665"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-watchosarm32-20250714-sources.jar",
          "url": "kmpotest-watchosarm32-20250714-sources.jar",
          "size": 3886,
          "sha512": "a6ec9538b8a722f2d0f47774cc5b9fbd5fcf02129d22c1e03ba7047061c3ec2e478bdc0168131c655fb536dc69935fd92986e8d615eda57ae4b7081407733cea",
          "sha256": "ee4582eb56c209e7e29e553c9da6bac272ad6891c040c75b2eeab7b4f76d8b1c",
          "sha1": "507431a6228b3a080f4e0799ea8545c4350519d6",
          "md5": "7b3f4dee141de6c719e7f69398f42ef2"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosarm32-20250714-metadata.jar",
          "url": "kmpotest-watchosarm32-20250714-metadata.jar",
          "size": 261,
          "sha512": "279f57878533ac638638ff07f165b77627f95a06ae3a5c70034b0a081ed1b4ec50c1944a651260670d4e37eb2b5036a957ab83b40031316c5235a9dd1bf747ce",
          "sha256": "1f7dfb5f57b9460822cab71439ab3a8c244b119dad32d0f961d108d0b1a1036a",
          "sha1": "79d380e402c2ee0482a2011343ec58fab6f7490d",
          "md5": "7dfcd36a270fa8e34886529104befa27"
        }
      ]
    }
  ]
}
