{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251109/testhelper-20251109.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251109",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-tvosX64Main-20251109.klib",
          "url": "testhelper-tvosx64-20251109.klib",
          "size": 6088,
          "sha512": "60f686a3035aa3259ef004311fbea94df00fb40281a13b994721f9947c8dccfe339944046cf88aff24edb558652d1bfab3ce4dcfd15be80dcd837bed9a91b179",
          "sha256": "bf733ee25cc2844d8f2089423f54e1b1c24b98bae9f46d99440bb7c95be6232d",
          "sha1": "815c0dcdc3da93c98e5c2c184f2ea718f9e2748c",
          "md5": "974772cbd12fe1d943c9b52d070e444c"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-tvosx64-20251109-sources.jar",
          "url": "testhelper-tvosx64-20251109-sources.jar",
          "size": 1869,
          "sha512": "84dcda1b0460f0f4eb06287ed23793891d0343e53b80134e9f0a872fb5489a25158b6d0660094abebcd1d8447a0814fe75ba6c670c93f2a23fd62f0ce6e7176e",
          "sha256": "1ce9616e3e6000ad84dec9343058b2b941eb80125bffa33941fe20d14c3bfd5c",
          "sha1": "6ef896896a91443c4b344a4bfb98aeebcac4af3a",
          "md5": "7ac31434ecd1007f4c39567d750781b1"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-tvosx64-20251109-metadata.jar",
          "url": "testhelper-tvosx64-20251109-metadata.jar",
          "size": 261,
          "sha512": "0181e8c6a726479c64faa1b3e1d97dd17d2c2eda86b5ebc5de1f9efec1aaa4dd4814656877d5c93b7250a7bf486e5cdb64f4e6a029bc48fbff6cbb377b061b4a",
          "sha256": "2ea53908854525fae7978186d41581731c703a406355a2fb4393e25ba316b520",
          "sha1": "8e40d6d73a4673a07814c9dbfae5fe7610b1905d",
          "md5": "71af01ef3c3219a3a74d3eedef3385d3"
        }
      ]
    }
  ]
}
