{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-koin/6.0.0-LOCAL/kotest-extensions-koin-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-extensions-koin",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-koin-js-6.0.0-LOCAL.klib",
          "url": "kotest-extensions-koin-js-6.0.0-LOCAL.klib",
          "size": 9604,
          "sha512": "ae22e770769acd11253b4d8caef7150639a2e7b63529ca6e9761f56b6383be0b3c8002d1f595ef8228e13c9c071ab7ca5753450599edc7bff770c00001ab3941",
          "sha256": "3470c3aac80e720b273840027900b55cc87c037bf61e2cfbfef1eea411fcd50b",
          "sha1": "da7537dc10eda6a00f2a1459662409c04cebae23",
          "md5": "58549b361904707a0c855984beb9258b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-koin-js-6.0.0-LOCAL.klib",
          "url": "kotest-extensions-koin-js-6.0.0-LOCAL.klib",
          "size": 9604,
          "sha512": "ae22e770769acd11253b4d8caef7150639a2e7b63529ca6e9761f56b6383be0b3c8002d1f595ef8228e13c9c071ab7ca5753450599edc7bff770c00001ab3941",
          "sha256": "3470c3aac80e720b273840027900b55cc87c037bf61e2cfbfef1eea411fcd50b",
          "sha1": "da7537dc10eda6a00f2a1459662409c04cebae23",
          "md5": "58549b361904707a0c855984beb9258b"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotest-extensions-koin-js-6.0.0-LOCAL-sources.jar",
          "url": "kotest-extensions-koin-js-6.0.0-LOCAL-sources.jar",
          "size": 1921,
          "sha512": "90abf70609469a92a4d21efe1e3450939678a685c5c59e2293ba6bda8c7618a8a13522139b7a9c9cb2e873c71fac2297385d0671e078c5bbc7cb80c124446589",
          "sha256": "005c8e142c3177baedc3130fb2ed2067171fa388a1b9c2218ad848d94516147b",
          "sha1": "587d26289d3c20e40b135a90ba4fd791758f6ba0",
          "md5": "f412afa78e5f7c5fd02cb0b819ccda38"
        }
      ]
    }
  ]
}
