{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.0.20+20241024",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20241024"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.20-1.0.25"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.20+20241024.jar",
          "url": "k2-2.0.20+20241024.jar",
          "size": 10771,
          "sha512": "624721538ca28af21895ad8ffd52a4200988ea84f10f05012b9b9daec56f5bde605af5b4a9b05fd13581a13d859605ab4794b3ed89b6bd790b8994bf0e42880e",
          "sha256": "c67f12a315cd3a05bac00877707d53ae7933bd55e8ce4e04a4514033a7b27c87",
          "sha1": "b6ef2bded59c1ce7cc23e9295a75baa1aeb7fd87",
          "md5": "989e5d74258d58a26298c9e25763beaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20241024"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.20-1.0.25"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.20+20241024.jar",
          "url": "k2-2.0.20+20241024.jar",
          "size": 10771,
          "sha512": "624721538ca28af21895ad8ffd52a4200988ea84f10f05012b9b9daec56f5bde605af5b4a9b05fd13581a13d859605ab4794b3ed89b6bd790b8994bf0e42880e",
          "sha256": "c67f12a315cd3a05bac00877707d53ae7933bd55e8ce4e04a4514033a7b27c87",
          "sha1": "b6ef2bded59c1ce7cc23e9295a75baa1aeb7fd87",
          "md5": "989e5d74258d58a26298c9e25763beaa"
        }
      ]
    }
  ]
}
