kotlin=2.4.0
kotest=6.0.4
serialization=1.11.0
agp=9.0.1
androidTestRunner=1.5.2
coroutines=1.11.0
ktor=3.5.1
nexus=2.0.0
dokka=2.2.0
datetime=0.8.0
napier=2.7.1
bouncycastle=1.84
kmmresult=1.9.3
testballoon=1.0.1-K2.3.0
testballoonAddons=0.16.0
