{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-shared/6.0.0-LOCAL/kotest-assertions-shared-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-assertions-shared",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-androidNativeX86Main-6.0.0-LOCAL.klib",
          "url": "kotest-assertions-shared-androidnativex86-6.0.0-LOCAL.klib",
          "size": 518970,
          "sha512": "ecf2734f8ac488d2d1ab61090f456c9b891e7fdefd6aae1369bb1e244469275fc1e3adce101011c03712782114c802d9d2e654cbf6ed9e1f8e593c51a4c240a7",
          "sha256": "c47f637034010b282dc060f36866cabebc58649cfaefb39784df22f57a7bcb28",
          "sha1": "d19ac45d64968bfa8e539c0120f8b9d80cac7998",
          "md5": "6e6764148c59f1d88cc41cc8ab4fcdd1"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-assertions-shared-androidnativex86-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-shared-androidnativex86-6.0.0-LOCAL-sources.jar",
          "size": 77938,
          "sha512": "b5c969d0987f5e71a50f6010a1a80107871c9c489921b389014b0db501180b66806644aaf13ee5aadf824378e645262c6fe4a6f8d7c9c3c9f518524df0341505",
          "sha256": "ba74c3e22c240c62b27a683cbe446dbfc3fe135c2b0cc0372cde386d888abe7f",
          "sha1": "dd781dc336d4ffc1824a1d6d4e7c9f97c958f222",
          "md5": "5cc81b4ff78f4fd9674c0a7ab0e9def4"
        }
      ]
    }
  ]
}
