{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/20251017/testballoon-shim-20251017.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-iosX64Main-20251017.klib",
          "url": "testballoon-shim-iosx64-20251017.klib",
          "size": 19826,
          "sha512": "e712d2d8f35bc0b2d065f0c73bdaf153a02a82d7087f57e509806ed39b406b40275b9dbcf0ef31f7dc89c0723bc3b3e5053d304f20c68f3d9d852d217955456f",
          "sha256": "effedb42544acd4a78e4fa328587f52d8a22e24e921a1e4784a15cb9854ac7cb",
          "sha1": "d6b57b79a261e8f63d24cd3a322f106957acbed5",
          "md5": "80460071b126f630f120b1ca30f6cadd"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-iosx64-20251017-sources.jar",
          "url": "testballoon-shim-iosx64-20251017-sources.jar",
          "size": 3319,
          "sha512": "406ce6795e090ebd44be4599c14cb70ed9bae7b405f79e277dbfcab86f542a1b8062e226313aabcffbee06d7477eeab9be7ddb1f8629cd5eb786139754f4e281",
          "sha256": "c30afff4e1f65eae3fc78dae94a5f35917220a430960fe0802c8628e884a44d4",
          "sha1": "746cb4d28746fbb0d0d174ec3e25a8d607b968dd",
          "md5": "2685749fe0a497fcbbc00fc63788200b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-iosx64-20251017-metadata.jar",
          "url": "testballoon-shim-iosx64-20251017-metadata.jar",
          "size": 261,
          "sha512": "94248673b9b4deca3405b7a249059ccfeb0f293031164041986e159620f980053d87875e874ac57aa2ba2d0ae87dedc8986c7391cf12b6c653488e21d82ff531",
          "sha256": "943e4875df6644c6bba8841cd8af8cab1b0a4b3bff855a0110f1ede5291d7157",
          "sha1": "49e4c19b7d00e58e9591105d40398df66e6d6d79",
          "md5": "c7ec3c20c700acd71f8290f8373df891"
        }
      ]
    }
  ]
}
