{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-shared/6.0.0-LOCAL/kotest-assertions-shared-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-assertions-shared",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-androidNativeX64Main-6.0.0-LOCAL.klib",
          "url": "kotest-assertions-shared-androidnativex64-6.0.0-LOCAL.klib",
          "size": 518970,
          "sha512": "3aff43d4f26b7070313ece1e9405e31c5b3b3e101927b09d64705847bdcc5fc3de49a83512ad7f3d4e8de117909f2c43e44706fbf49378c5c99dd09d528e1736",
          "sha256": "c7258af433e0c2af2057bfba8c7a8ca58e1e828aaac0877214cca9e486b4879c",
          "sha1": "02fd06f6d8dc018c5ba50f9f5c9052f0f844a633",
          "md5": "8ef1d6ac8ef9ff35f7dc506a6dabe8cf"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-assertions-shared-androidnativex64-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-shared-androidnativex64-6.0.0-LOCAL-sources.jar",
          "size": 77938,
          "sha512": "b5c969d0987f5e71a50f6010a1a80107871c9c489921b389014b0db501180b66806644aaf13ee5aadf824378e645262c6fe4a6f8d7c9c3c9f518524df0341505",
          "sha256": "ba74c3e22c240c62b27a683cbe446dbfc3fe135c2b0cc0372cde386d888abe7f",
          "sha1": "dd781dc336d4ffc1824a1d6d4e7c9f97c958f222",
          "md5": "5cc81b4ff78f4fd9674c0a7ab0e9def4"
        }
      ]
    }
  ]
}
