{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/20251017/testballoon-shim-20251017.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-androidNativeX64Main-20251017.klib",
          "url": "testballoon-shim-androidnativex64-20251017.klib",
          "size": 19807,
          "sha512": "b740e2a3bccf3d1f9dae2274ba8a7fe1fbe29fbb10711ff4a97e57c27ba338c81f96d721f7f92b354671a756b789df93bd5d74523de8586db28349b730c3b064",
          "sha256": "f5adf8a020017a404e9cb614904432714cabd70f35144ad667bdf4abcf52f507",
          "sha1": "6d8d5d3996d50e6485d6652e1d1b856db2c63fd8",
          "md5": "b8b64d9148d3003bbb065e36b5d954c9"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-androidnativex64-20251017-sources.jar",
          "url": "testballoon-shim-androidnativex64-20251017-sources.jar",
          "size": 3423,
          "sha512": "6f52af3fab065be5348a53467eb99e0b57a8bca3b359a62b21ea229ab89808eed1b565696bcb1f77a8b3640e71c173fac9baa7c1eb6b26cc58c19cde2e354e65",
          "sha256": "00819630ff669e47fc6f6b05bd6807c5a839872a9a1a266fd7bbac033d1f096b",
          "sha1": "823e2ff4ff40036d80dd38670d60c506897362b8",
          "md5": "3fceae67cdcbb589f8214e50f95e3371"
        }
      ]
    }
  ]
}
