{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-runner-junit5/6.0.0-LOCAL/kotest-runner-junit5-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-runner-junit5",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-extensions",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-suite-api",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-runner-junit5-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-runner-junit5-jvm-6.0.0-LOCAL.jar",
          "size": 65003,
          "sha512": "917d37af359ba30e490f42bb97dd128c196fe1676b6d81626ecb6824a4fba5d3fac577d610bf0dc964a279a5db62ce4de97334184f690ce492bcb8e7ed84a3d8",
          "sha256": "2e79ca38e0ec63c8307ab36c2f3d3d2f725387a513de5d00ffa28f7c8f35227c",
          "sha1": "a51d920503ebd5f18055a3c992ec0f46d7b6d201",
          "md5": "5ccc601818a7bdce24af1baf7cee39d1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-extensions",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-suite-api",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-runner-junit5-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-runner-junit5-jvm-6.0.0-LOCAL.jar",
          "size": 65003,
          "sha512": "917d37af359ba30e490f42bb97dd128c196fe1676b6d81626ecb6824a4fba5d3fac577d610bf0dc964a279a5db62ce4de97334184f690ce492bcb8e7ed84a3d8",
          "sha256": "2e79ca38e0ec63c8307ab36c2f3d3d2f725387a513de5d00ffa28f7c8f35227c",
          "sha1": "a51d920503ebd5f18055a3c992ec0f46d7b6d201",
          "md5": "5ccc601818a7bdce24af1baf7cee39d1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-runner-junit5-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-runner-junit5-jvm-6.0.0-LOCAL-sources.jar",
          "size": 18737,
          "sha512": "8f8b336c29b08278c8f62920ba47f67371c90913acb711ea31b61b22fbb51ef7ee47dc826c4fb907a0b26f275497c9db1b317dcbf5821da81e44544ca3d1df0b",
          "sha256": "e2a8171ffc477f29697416acd7c1a04640b4e6f340e49c716ed70d4049fd4939",
          "sha1": "1454822fdc811fbffae03e904e9c70b0d7e794b5",
          "md5": "aca0dbe9286c5c271bebe79f32fe5782"
        }
      ]
    }
  ]
}
