{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/20251003/testballoon-shim-20251003.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251003",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-iosX64Main-20251003.klib",
          "url": "testballoon-shim-iosx64-20251003.klib",
          "size": 17914,
          "sha512": "4c948c7fdfa264c342f0f8765f1045100f284d5606cdf8f024778f4bf87425e8e693ea8e813c77a9adbbfe76b0b1aea55c2bd91ea4733d3a6065a0b78a6253c5",
          "sha256": "5ee8f1d6a09619d3b7528e976607464f1a226153eb8b97d42d5dd2867112e5e2",
          "sha1": "f65600de7f52befa819c166821b6bd04688afbe1",
          "md5": "6088f86aa523a15f2b3eb836029a1a64"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-iosx64-20251003-sources.jar",
          "url": "testballoon-shim-iosx64-20251003-sources.jar",
          "size": 3108,
          "sha512": "1eaeb46d68ad2c684a3aa5ef42a762f08967c39f0651fc898787098f84a73a05a8cd264e68d164386be336d325af754e7aa69e00ac8353e58fb990996a38378d",
          "sha256": "77e845b21a42b8393ab94a9ef958292d311c417d5ee4e11e843de5b5d5c8e867",
          "sha1": "09f84cb2bfb67634b3cb2a02262570e6d7004495",
          "md5": "c29f57172477ca37e34d7903c72a3641"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-iosx64-20251003-metadata.jar",
          "url": "testballoon-shim-iosx64-20251003-metadata.jar",
          "size": 261,
          "sha512": "6a7451f932d97a5966341e76676aa0124b760c6215a0141fdfe27c131aaf616e9d6d6a5faee6ab96548ea903a8520b458c4a3e20e3d1b81c787cbf9fd115c2a3",
          "sha256": "c7b37f6922adb0da97d39dc68c4b45b33dcff101fd7a6938567956d85d0cc24a",
          "sha1": "df37566b5ad45fc6b6231037a819d45302030b58",
          "md5": "ee4b88988652b60a168f8c0f04aad9f2"
        }
      ]
    }
  ]
}
