{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "1.9.23+20240409",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240409"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.19"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240409.jar",
          "url": "k2-1.9.23+20240409.jar",
          "size": 10384,
          "sha512": "9419966457ef58aef296c15859ab2b79728b419c2d0f8b99508b3b799a3281e618e707450cf3469a09eb9a96026665b17e72d3b81f37fd1998e2d18088b5ec61",
          "sha256": "f7e2f7ded395fe56043b4108a485187bbebfb6a6fbd6dbd1815f5858f8cd19e6",
          "sha1": "f59b33fe22d869daef62b94e8bd4889bdf7b8360",
          "md5": "1da460d7d766a8f5f7fe4c847f4eb579"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240409"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.19"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240409.jar",
          "url": "k2-1.9.23+20240409.jar",
          "size": 10384,
          "sha512": "9419966457ef58aef296c15859ab2b79728b419c2d0f8b99508b3b799a3281e618e707450cf3469a09eb9a96026665b17e72d3b81f37fd1998e2d18088b5ec61",
          "sha256": "f7e2f7ded395fe56043b4108a485187bbebfb6a6fbd6dbd1815f5858f8cd19e6",
          "sha1": "f59b33fe22d869daef62b94e8bd4889bdf7b8360",
          "md5": "1da460d7d766a8f5f7fe4c847f4eb579"
        }
      ]
    }
  ]
}
