{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251114/testhelper-20251114.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchosSimulatorArm64Main-20251114.klib",
          "url": "testhelper-watchossimulatorarm64-20251114.klib",
          "size": 6177,
          "sha512": "bfe920199093b4a0ad6007dae23b7cb8bd6e787ef25fb3de380a1f62b228b954f56e58d72549f909b6a7d4925120af19e69c1ab80e539f681a57e09c601af969",
          "sha256": "898bfc9d3c54008f846980dc4bb283f943cec97a26e88b2a0fb0f92ee3099d96",
          "sha1": "d44cf4fbe92c2f25ee26d8467aba10317ae6b35e",
          "md5": "4475ab6172fb88e6346011777821e7c2"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-watchossimulatorarm64-20251114-sources.jar",
          "url": "testhelper-watchossimulatorarm64-20251114-sources.jar",
          "size": 2025,
          "sha512": "811ba8801be5d0505076bdc0c6af245b2b0b664ab6f41b8468a80a55e6fb2a097e17650f75883c1bed3e2bd238cae9a0221fc415588df61470566b6f230825de",
          "sha256": "19708bb50d3aafa1c3cd3c7696fca9132464276862aad75bca4dec9a0fb336b3",
          "sha1": "9297554bc21ef0058232eb31307aad3eec8ea4c7",
          "md5": "815e984a3f9da8a1e763b90bf812f80b"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchossimulatorarm64-20251114-metadata.jar",
          "url": "testhelper-watchossimulatorarm64-20251114-metadata.jar",
          "size": 261,
          "sha512": "366828b0e692123f2872c4e3321ca3835517403040a95b09430ab5785d51302f2e4af6eab4bdbb29b002279923908fc711788a262a544c09550623f632ab76e7",
          "sha256": "95931f2cd50dadf25ccd6c2cae8486f49e552f4641bd99c8b6b336fc5612d927",
          "sha1": "4ba9bd66a26568a88ec8bd1b891210614758d005",
          "md5": "e7d1986dd4bc4b0fc3869bfc0a2d2789"
        }
      ]
    }
  ]
}
