{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251114/testhelper-20251114.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchosDeviceArm64Main-20251114.klib",
          "url": "testhelper-watchosdevicearm64-20251114.klib",
          "size": 6178,
          "sha512": "d3be748fddc2939523d2bcfea7a8df3ee3c4571f3c387137e0583ff4409ec61d8cddd694befe3f3ecdbf9d9713152b383154f454a3a1e17ff1f9409e9db1dee0",
          "sha256": "ace9333890f5278c758355cbdd500d0890800cf01a02d79f162d221acc31bb39",
          "sha1": "072b913342d2367ef4a3cae979066d52e0ea664c",
          "md5": "94b78e62fd95e52d9b1aebbd1cef0eea"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-watchosdevicearm64-20251114-sources.jar",
          "url": "testhelper-watchosdevicearm64-20251114-sources.jar",
          "size": 2030,
          "sha512": "e6a04a563b396a6eac39ba36a75939a2cb020f4bcc18be519e22d2ca02340210a6803c22a4c2db0d433617b6fdff5ba38265c25ebf391d31bc74c2c4112544f6",
          "sha256": "6e03de9b70cadf82babd90fa4a47c601e57da3ff27f8dccf44cf902b54dc6600",
          "sha1": "d94d60f9502c1e017c10d5b6cc308210a508958c",
          "md5": "6224a24f3fa78281ef62024f6f931f82"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchosdevicearm64-20251114-metadata.jar",
          "url": "testhelper-watchosdevicearm64-20251114-metadata.jar",
          "size": 261,
          "sha512": "a6d3b112dbe7c3c0e4d3a191fbcee6000d0c14dba9fdd1823f414d421bd72641f1d076f96d4938bd7058c81caafc46ab5498033c52c3a2f9978d7ab7a24a3e6f",
          "sha256": "5d4e630e8ad270150dda33fbff0ea9cdfdb4798e29c6e47e3a2aada790962760",
          "sha1": "89904b12b1c600d46eb4f1b98717324ce6d82d38",
          "md5": "8e80af8e9953bd0e38e0462ebdf3d3da"
        }
      ]
    }
  ]
}
