{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251114/testhelper-20251114.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchosX64Main-20251114.klib",
          "url": "testhelper-watchosx64-20251114.klib",
          "size": 6085,
          "sha512": "dc66f95de0431aabfdc9e110702441d2a905a4f746a611b0f06ee1517bde4e9b9bed1b9e9b0cbd83c59e98c88fd8bf2dc2074b3c38c42f9079bd463c6c95e9ae",
          "sha256": "b0429035867886d85c68f4dee6f52fe041815fb520dcf54c7eedbaea1ba8840e",
          "sha1": "95a2b61291d001ffc5f404d0eb5784536399d165",
          "md5": "433f7bc137ca0de553eab58a155e0117"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-watchosx64-20251114-sources.jar",
          "url": "testhelper-watchosx64-20251114-sources.jar",
          "size": 1902,
          "sha512": "8f27b92df640bbecc9d8771250ed6417cd599122c29aeaa933cc9b0e9abf940fd2b18dcb9ba6a987bd9194126754086cdeb636ab6e7e753f8249c009bd4a1daa",
          "sha256": "7981816a42d6576d07d8f97f050362b74fe493f922920aea76e4380bb1a88359",
          "sha1": "110602155ed315f0e39e8e051b44f2f3889b8965",
          "md5": "610cdf0354d6fcf246b8da993123b920"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchosx64-20251114-metadata.jar",
          "url": "testhelper-watchosx64-20251114-metadata.jar",
          "size": 261,
          "sha512": "366828b0e692123f2872c4e3321ca3835517403040a95b09430ab5785d51302f2e4af6eab4bdbb29b002279923908fc711788a262a544c09550623f632ab76e7",
          "sha256": "95931f2cd50dadf25ccd6c2cae8486f49e552f4641bd99c8b6b336fc5612d927",
          "sha1": "4ba9bd66a26568a88ec8bd1b891210614758d005",
          "md5": "e7d1986dd4bc4b0fc3869bfc0a2d2789"
        }
      ]
    }
  ]
}
