{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-kotlinx-datetime/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-assertions-kotlinx-datetime",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-js-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-assertions-kotlinx-datetime-js-6.0.0-LOCAL-PRE.klib",
          "size": 23741,
          "sha512": "3467336f7c30e41ef3d55cc4162f71d8d8b9e75f7e49d9ed416db9b48cd4476bc0788156273e3ee0a7bbb6d2ab291043d763687b10ff4a4aabe6778ab627b2d2",
          "sha256": "5a05c4995e46e41fdea7ecb7858b841315ad5c9ceda21d77f30767bb72b43b01",
          "sha1": "70fd1c278134d6df1a38851f4ef04471ad3d3151",
          "md5": "6123081343edf30a612ee89d5d09fc62"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-js-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-assertions-kotlinx-datetime-js-6.0.0-LOCAL-PRE.klib",
          "size": 23741,
          "sha512": "3467336f7c30e41ef3d55cc4162f71d8d8b9e75f7e49d9ed416db9b48cd4476bc0788156273e3ee0a7bbb6d2ab291043d763687b10ff4a4aabe6778ab627b2d2",
          "sha256": "5a05c4995e46e41fdea7ecb7858b841315ad5c9ceda21d77f30767bb72b43b01",
          "sha1": "70fd1c278134d6df1a38851f4ef04471ad3d3151",
          "md5": "6123081343edf30a612ee89d5d09fc62"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-js-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-kotlinx-datetime-js-6.0.0-LOCAL-PRE-sources.jar",
          "size": 5894,
          "sha512": "3c4de6915eb75ce5c779ab644be50368f319599a32a90792083f2b01924a992cab4482e49850a3a4e2594e20cc5e3743eb31b6d0689d44ea02917db3e172b86a",
          "sha256": "caa4b864e009f1f040b1bbb4a76f0a4ed698f5625cc56a93553bc5730cd63822",
          "sha1": "c35d27219f982a289125ae27434b952f613c7b43",
          "md5": "b5e5cf5e1e0de91477301be67a048bf5"
        }
      ]
    }
  ]
}
