{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-linuxX64Main-202509019.klib",
          "url": "testballoon-shim-linuxx64-202509019.klib",
          "size": 18973,
          "sha512": "8b650ac462eec3201678e29209fe290e6924e4aaf8911531497bacd497817d2f184f6770eaee23bdf7c80d2025f56752f68096e8f48196397c5674b1e9cfdac3",
          "sha256": "048ada9761c4fc5d2ee1be3834eab824bbea3605cd1635c4280b868bba940248",
          "sha1": "e9dd435cdec48b464f8d61a116100585601a9ee4",
          "md5": "a1fbf62301816d65b4029d78a7656d22"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-linuxx64-202509019-sources.jar",
          "url": "testballoon-shim-linuxx64-202509019-sources.jar",
          "size": 3178,
          "sha512": "e3121db28c62de943311ee16f88ae74576d66ae1ceee99b268e0e51c7b175b560b224a44047db0517bb7331c83609cba9f873a32e1df2d494f1ce13a4d5824d5",
          "sha256": "5750924bcef5211378c413108f592bfdb67ab4023350f5182463f48b1f11345e",
          "sha1": "9c745de40c92fa015fe8e74c55fa4185fa9eb110",
          "md5": "8cac46eb49200e2f03aff9cc85a0f52d"
        }
      ]
    }
  ]
}
