{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-linuxX64Main-202509019.klib",
          "url": "testballoon-shim-linuxx64-202509019.klib",
          "size": 18141,
          "sha512": "f49a56a5136e672bd6231409488c76f4d8655e124987adf8feebf6dc2a342a627e3ceee12403e6157d2b6ae2edbfcd3f687e2cedd8b066ef4ac42c0da9a1fe93",
          "sha256": "98944ff96c2a98601cb8868434ffc55ecbf77e68aa14540b25b947effc5a8148",
          "sha1": "272d8d76ecf1b6ed808de98ab4b466b47bf4f6db",
          "md5": "96749a0dad246b53474a0e644a8b3582"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-linuxx64-202509019-sources.jar",
          "url": "testballoon-shim-linuxx64-202509019-sources.jar",
          "size": 3036,
          "sha512": "5f7cec9d91d1eca78f7a34dc0b81e1d8baa39ab22e0b1ca5a0f2ac9fa338afdfba1627b4629a3b2f60c0408ae689cc5b99acb2c7db54a1a2c408f5d3a9e53092",
          "sha256": "d86567a4742e06057f6886d37cbb9a9b82cb64cff6091b1bbaa1dc423059dfbd",
          "sha1": "864bb5d6e2a423f241925cd28c06efbb38995ce5",
          "md5": "97bb9b456bbf6b4b084cac752eb82189"
        }
      ]
    }
  ]
}
