{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-arrow-fx-coroutines/6.0.0-LOCAL/kotest-assertions-arrow-fx-coroutines-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-assertions-arrow-fx-coroutines",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-arrow",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-fx-coroutines",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-fx-coroutines-wasm-js-6.0.0-LOCAL.klib",
          "url": "kotest-assertions-arrow-fx-coroutines-wasm-js-6.0.0-LOCAL.klib",
          "size": 24065,
          "sha512": "db2e64d70f5a4e0b8725f9e0cd008f23142d99aac6193fb95fb8a6f904ba892fa686f029536edbfe632f640cb0337519a1b6e64e66582ef9dae6e9127d4ab01d",
          "sha256": "716d00e87436f55f12e15a13cd63f0bd45c579688413d993a5fa4bedea41c47a",
          "sha1": "741bb94677e92e0ab82e758532964f1677aeb8e4",
          "md5": "4812bb02e0d3d42d17a3485678ebc97d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-arrow",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-fx-coroutines",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-fx-coroutines-wasm-js-6.0.0-LOCAL.klib",
          "url": "kotest-assertions-arrow-fx-coroutines-wasm-js-6.0.0-LOCAL.klib",
          "size": 24065,
          "sha512": "db2e64d70f5a4e0b8725f9e0cd008f23142d99aac6193fb95fb8a6f904ba892fa686f029536edbfe632f640cb0337519a1b6e64e66582ef9dae6e9127d4ab01d",
          "sha256": "716d00e87436f55f12e15a13cd63f0bd45c579688413d993a5fa4bedea41c47a",
          "sha1": "741bb94677e92e0ab82e758532964f1677aeb8e4",
          "md5": "4812bb02e0d3d42d17a3485678ebc97d"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotest-assertions-arrow-fx-coroutines-wasm-js-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-arrow-fx-coroutines-wasm-js-6.0.0-LOCAL-sources.jar",
          "size": 5189,
          "sha512": "213f753fc92f5e0df095d79f91afcb2bfaea52d15cec513c50da5c2bb0f65bc93ecd6454cf4dd6d8fcfcd92d172dc2571f4651ab7426d816434d68f07ea80f8e",
          "sha256": "53256b46333a7c37138c0de43eb58401ec40f0df70c11302b73f137ca4e24bac",
          "sha1": "00ad21bba9c65e64c6e3588774923f20f5f7a701",
          "md5": "fa7b6257b0f3cc4cc60c88cbd373f00a"
        }
      ]
    }
  ]
}
