{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-blocking-detection/0.6.2-K2.2.20-SNAPSHOT/testBalloon-integration-blocking-detection-0.6.2-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-blocking-detection",
    "version": "0.6.2-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-wasm-js-0.6.2-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-integration-blocking-detection-wasm-js-0.6.2-K2.2.20-SNAPSHOT.klib",
          "size": 5212,
          "sha512": "877d0c6babefac6bb187aa32141669a07d5990b1a71b8cea17f539824bca5d7f4c66cc3d6dfcd205697e79dfe26a51a420c544a06903b0a6f3aaec913bde21b0",
          "sha256": "134e7c29d1fd9f671ae3f96407e7db512754828abbb869a2ba34b734daf11316",
          "sha1": "4eb34e9afedf7b5722a01261e476062e3c542751",
          "md5": "985b23b305cf3e6c6775ebc32c60f8bd"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-wasm-js-0.6.2-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-integration-blocking-detection-wasm-js-0.6.2-K2.2.20-SNAPSHOT.klib",
          "size": 5212,
          "sha512": "877d0c6babefac6bb187aa32141669a07d5990b1a71b8cea17f539824bca5d7f4c66cc3d6dfcd205697e79dfe26a51a420c544a06903b0a6f3aaec913bde21b0",
          "sha256": "134e7c29d1fd9f671ae3f96407e7db512754828abbb869a2ba34b734daf11316",
          "sha1": "4eb34e9afedf7b5722a01261e476062e3c542751",
          "md5": "985b23b305cf3e6c6775ebc32c60f8bd"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-wasm-js-0.6.2-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-blocking-detection-wasm-js-0.6.2-K2.2.20-SNAPSHOT-sources.jar",
          "size": 2945,
          "sha512": "3a6ffd841a76c83fa5eb32beda5c04fbba6ccd5478a6571f871d9baf91e37280375182070833a5a9cfa2a808d90dcfe28e523fe271e3bad465e10c464cb685fb",
          "sha256": "c0406b8268c345c0671c09f5a0eeab8fcd152c25e7132c5c31ad0f25d7483ef0",
          "sha1": "e78f2caa91e06c010dce75eea7ae669a622cd299",
          "md5": "08716f9c53284aed393df921de230d27"
        }
      ]
    }
  ]
}
