{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-core/0.6.3-K2.2.20-SNAPSHOT/testBalloon-framework-core-0.6.3-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-core",
    "version": "0.6.3-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-abstractions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-core-watchosX64Main-0.6.3-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-framework-core-watchosx64-0.6.3-K2.2.20-SNAPSHOT.klib",
          "size": 138374,
          "sha512": "bb917089845952d5d86a3d94bf014f023220e99667a162c7cecc7eb8413b1a64fcd873908752bda366fea6b2cdf0ff7d954b6200f98920a16ea00f6f760e44b7",
          "sha256": "9a667b17552fe52de8e67dbcc409c7e141d6b82797725102f60d3e05aca70f9b",
          "sha1": "989f7bee862272139190f243abd638e565050bff",
          "md5": "e2a044521cc051759bb68583093b2279"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-framework-core-watchosx64-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-core-watchosx64-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "size": 34816,
          "sha512": "df10b18e845cf67e41ee7ebbe98638f9e3957ab38ffda931e68d8397e5fe7d66f782584265b5a28c6bb00013e032acb8c3c8b2986601465456c809caa311e438",
          "sha256": "58af33a24876bd7d8d4d803069f7122444c5ab77beed0d2f2b91131d300612e5",
          "sha1": "26bd26c13e5e85de90eda9004d774bcae10bdab9",
          "md5": "46e1e064c8e99bdc9080a42683fc2b59"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-abstractions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-core-watchosx64-0.6.3-K2.2.20-SNAPSHOT-metadata.jar",
          "url": "testBalloon-framework-core-watchosx64-0.6.3-K2.2.20-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
