{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251110/testhelper-20251110.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251110",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchosSimulatorArm64Main-20251110.klib",
          "url": "testhelper-watchossimulatorarm64-20251110.klib",
          "size": 6202,
          "sha512": "22c022337b7c6ec9d859fdafa6a74020fa53b28b373399fa303886851cbcc1443d67c74e13ff4ff6039a672cf3ca20ffb85336e0782792b0fb741c7bcb30ae86",
          "sha256": "9183adc26be2c4e18e6f1c35c52cb7cfc3514d103cc259b77a313195adfc1e84",
          "sha1": "55f7fd420cfee1301f4e5375a37aec8e34efb77a",
          "md5": "e6cabf7474d8f08c1b0d245ea9d39132"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-watchossimulatorarm64-20251110-sources.jar",
          "url": "testhelper-watchossimulatorarm64-20251110-sources.jar",
          "size": 2025,
          "sha512": "811ba8801be5d0505076bdc0c6af245b2b0b664ab6f41b8468a80a55e6fb2a097e17650f75883c1bed3e2bd238cae9a0221fc415588df61470566b6f230825de",
          "sha256": "19708bb50d3aafa1c3cd3c7696fca9132464276862aad75bca4dec9a0fb336b3",
          "sha1": "9297554bc21ef0058232eb31307aad3eec8ea4c7",
          "md5": "815e984a3f9da8a1e763b90bf812f80b"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchossimulatorarm64-20251110-metadata.jar",
          "url": "testhelper-watchossimulatorarm64-20251110-metadata.jar",
          "size": 261,
          "sha512": "381e063c92837ccf20ddb631a9b0708b381af22b0dc10c0f83553e5b5a562a811862dbb506222548950a4931d34c78e1c85030895f548f8fcad5067e1242f9de",
          "sha256": "a21b6a67251ea4719f372c81d235a94ab8f2999ce8c216d0024aa72f155e6964",
          "sha1": "1ace565993c4d294ff1cca6de42829fd3ad92806",
          "md5": "647ad46b14644c63b5f91c04315052db"
        }
      ]
    }
  ]
}
