{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250727/kmpotest-20250727.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250727",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-iosX64Main-20250727.klib",
          "url": "kmpotest-iosx64-20250727.klib",
          "size": 39645,
          "sha512": "1aa53e2fd51e938fb6003172ec17f462c59259b34a5ed095607405192e7a4694d44e47d5738d0a4e5061891db3ade1aa0373bebe6c19c527a970b640b22e4974",
          "sha256": "6b1806dd8715147ec22529ebb172634546b9e3647a30c5ba506ebc3dbcb3fc33",
          "sha1": "a6c971d020cf1142b8d1ceefae8909bb4c492fcb",
          "md5": "400ceba271d681d72225dd830fa206b7"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-iosx64-20250727-sources.jar",
          "url": "kmpotest-iosx64-20250727-sources.jar",
          "size": 4274,
          "sha512": "8556604752de9619ab877c82162d81b3afdddf1e9040a90d370a08414fba252a2e96a4cf8ceed904c65ff6c86da41464f74a6582c16771b97e6da47645ca9ffc",
          "sha256": "507ef67c4d74da50aa17712c9bb8dbb70fa226ce4c830015c12c402eb74f4f1d",
          "sha1": "c58208b3a041f977603fd8ae5499a0b6501787d3",
          "md5": "2ccd50215ae8b8d0c43ba7075c8cd6af"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-iosx64-20250727-metadata.jar",
          "url": "kmpotest-iosx64-20250727-metadata.jar",
          "size": 261,
          "sha512": "75d6990357748f9ff7fad59c69f731411c3e5ecbe96087abc1571910c68c43faecfbab94c30a439df5443f6a8c83c361536b1d759502e06c7a120ec506062570",
          "sha256": "34f9681a020cfa0d4c22829ef0148c5df000a48aceb3d9f298a1b5ac1b281022",
          "sha1": "2ea47d9c8a1e8cdf9814308143e083b75149c830",
          "md5": "4729a702199c9ffd5deb77e60a6445a5"
        }
      ]
    }
  ]
}
