{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-framework-engine",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-framework-engine-6.0.0-LOCAL.jar",
          "size": 239876,
          "sha512": "fce4890b06929204397846667262fa46ba9e6b9c316b49f024ffb36a16eb1814c2477fe0f4d7a1b2a0af7c22db2f0bc8ce6332590e26f843885e15ef0c1be5be",
          "sha256": "803bfd95e2afd6ffea5c1b43d43498cb626cde600073a9e9de2375b629408d6f",
          "sha1": "e1b329bca8553d790092643e8ed39983812bc798",
          "md5": "9ba9ce00cd69c8fc1b287d893f813506"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-framework-engine-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-framework-engine-6.0.0-LOCAL-sources.jar",
          "size": 264571,
          "sha512": "0d88c3fc9aeea6ad976b980de24aaee6a513b56f4acb27e95ae0a73a26b341d8e2cbd57a61794c769b944f1064ed36f736036d0be68e30c1945bef0d10588d97",
          "sha256": "5f889cca64b14f65222f56e63399859662ad21cbe24ab44fd27d875bedda4756",
          "sha1": "f1645e3a9b296879d68150b2cedf296ddfee9fbf",
          "md5": "1bbfec8df1a7ca462c142f63da2f9918"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativearm32/6.0.0-LOCAL/kotest-framework-engine-androidnativearm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativearm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativearm32/6.0.0-LOCAL/kotest-framework-engine-androidnativearm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativearm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativearm64/6.0.0-LOCAL/kotest-framework-engine-androidnativearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativearm64/6.0.0-LOCAL/kotest-framework-engine-androidnativearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativex64/6.0.0-LOCAL/kotest-framework-engine-androidnativex64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativex64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativex64/6.0.0-LOCAL/kotest-framework-engine-androidnativex64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativex64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativex86/6.0.0-LOCAL/kotest-framework-engine-androidnativex86-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativex86",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativex86/6.0.0-LOCAL/kotest-framework-engine-androidnativex86-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativex86",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-js/6.0.0-LOCAL/kotest-framework-engine-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-js/6.0.0-LOCAL/kotest-framework-engine-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-js/6.0.0-LOCAL/kotest-framework-engine-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-jvm/6.0.0-LOCAL/kotest-framework-engine-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-jvm/6.0.0-LOCAL/kotest-framework-engine-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-jvm/6.0.0-LOCAL/kotest-framework-engine-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-wasm-js/6.0.0-LOCAL/kotest-framework-engine-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-wasm-js/6.0.0-LOCAL/kotest-framework-engine-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-wasm-js/6.0.0-LOCAL/kotest-framework-engine-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
