{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-framework-engine",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-framework-engine-6.0.0-LOCAL.jar",
          "size": 239985,
          "sha512": "47cd3ef592dcfa914f17cd59313de943209b755985ecc8ac9f7cc2af800eaf2d4daf3a5b865297c0310a5284890633933c2500d9d3825cb25b3d6893d60f1a9a",
          "sha256": "c96372c27f6e3351ae6d651f07f0cf706c0c1aa0417c9ec06951157a6dc4879f",
          "sha1": "96e8a57bfd25895ab466d40a01f0f653b9a19639",
          "md5": "65c89f3703871624d76161428af62c05"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-framework-engine-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-framework-engine-6.0.0-LOCAL-sources.jar",
          "size": 265090,
          "sha512": "1223dd4f486994a0a1d33db4643ac6dcd1ba4f431b61f5c40d0944afde7279f38d09a8e6be981b4a888533c30522100459c6a9bfb70858e29b9ea30cd78f5918",
          "sha256": "b545ccad18610ec62d36c3ddde3018cb3b2359ca79a04f5cfdb2d90631f02ea6",
          "sha1": "22ca1028005d84439f40b50abb812ef2579a0057",
          "md5": "2b18866bea465855bf551ce2c7bbb5dd"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativearm32/6.0.0-LOCAL/kotest-framework-engine-androidnativearm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativearm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativearm32/6.0.0-LOCAL/kotest-framework-engine-androidnativearm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativearm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativearm64/6.0.0-LOCAL/kotest-framework-engine-androidnativearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativearm64/6.0.0-LOCAL/kotest-framework-engine-androidnativearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativex64/6.0.0-LOCAL/kotest-framework-engine-androidnativex64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativex64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativex64/6.0.0-LOCAL/kotest-framework-engine-androidnativex64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativex64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativex86/6.0.0-LOCAL/kotest-framework-engine-androidnativex86-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativex86",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-androidnativex86/6.0.0-LOCAL/kotest-framework-engine-androidnativex86-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-androidnativex86",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-iosarm64/6.0.0-LOCAL/kotest-framework-engine-iosarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-iosarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-iosarm64/6.0.0-LOCAL/kotest-framework-engine-iosarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-iosarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-iosarm64/6.0.0-LOCAL/kotest-framework-engine-iosarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-iosarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-iossimulatorarm64/6.0.0-LOCAL/kotest-framework-engine-iossimulatorarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-iossimulatorarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-iossimulatorarm64/6.0.0-LOCAL/kotest-framework-engine-iossimulatorarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-iossimulatorarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-iossimulatorarm64/6.0.0-LOCAL/kotest-framework-engine-iossimulatorarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-iossimulatorarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-iosx64/6.0.0-LOCAL/kotest-framework-engine-iosx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-iosx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-iosx64/6.0.0-LOCAL/kotest-framework-engine-iosx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-iosx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-iosx64/6.0.0-LOCAL/kotest-framework-engine-iosx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-iosx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-js/6.0.0-LOCAL/kotest-framework-engine-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-js/6.0.0-LOCAL/kotest-framework-engine-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-js/6.0.0-LOCAL/kotest-framework-engine-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-jvm/6.0.0-LOCAL/kotest-framework-engine-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-jvm/6.0.0-LOCAL/kotest-framework-engine-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-jvm/6.0.0-LOCAL/kotest-framework-engine-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-linuxarm64/6.0.0-LOCAL/kotest-framework-engine-linuxarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-linuxarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-linuxarm64/6.0.0-LOCAL/kotest-framework-engine-linuxarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-linuxarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-linuxx64/6.0.0-LOCAL/kotest-framework-engine-linuxx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-linuxx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-linuxx64/6.0.0-LOCAL/kotest-framework-engine-linuxx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-linuxx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-macosarm64/6.0.0-LOCAL/kotest-framework-engine-macosarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-macosarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-macosarm64/6.0.0-LOCAL/kotest-framework-engine-macosarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-macosarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-macosarm64/6.0.0-LOCAL/kotest-framework-engine-macosarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-macosarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-macosx64/6.0.0-LOCAL/kotest-framework-engine-macosx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-macosx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-macosx64/6.0.0-LOCAL/kotest-framework-engine-macosx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-macosx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-macosx64/6.0.0-LOCAL/kotest-framework-engine-macosx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-macosx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-mingwx64/6.0.0-LOCAL/kotest-framework-engine-mingwx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-mingwx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-mingwx64/6.0.0-LOCAL/kotest-framework-engine-mingwx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-mingwx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-tvosarm64/6.0.0-LOCAL/kotest-framework-engine-tvosarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-tvosarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-tvosarm64/6.0.0-LOCAL/kotest-framework-engine-tvosarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-tvosarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-tvosarm64/6.0.0-LOCAL/kotest-framework-engine-tvosarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-tvosarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-tvossimulatorarm64/6.0.0-LOCAL/kotest-framework-engine-tvossimulatorarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-tvossimulatorarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-tvossimulatorarm64/6.0.0-LOCAL/kotest-framework-engine-tvossimulatorarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-tvossimulatorarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-tvossimulatorarm64/6.0.0-LOCAL/kotest-framework-engine-tvossimulatorarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-tvossimulatorarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-tvosx64/6.0.0-LOCAL/kotest-framework-engine-tvosx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-tvosx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-tvosx64/6.0.0-LOCAL/kotest-framework-engine-tvosx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-tvosx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-tvosx64/6.0.0-LOCAL/kotest-framework-engine-tvosx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-tvosx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-wasm-js/6.0.0-LOCAL/kotest-framework-engine-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-wasm-js/6.0.0-LOCAL/kotest-framework-engine-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-wasm-js/6.0.0-LOCAL/kotest-framework-engine-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchosarm32/6.0.0-LOCAL/kotest-framework-engine-watchosarm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchosarm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchosarm32/6.0.0-LOCAL/kotest-framework-engine-watchosarm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchosarm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchosarm32/6.0.0-LOCAL/kotest-framework-engine-watchosarm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchosarm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchosarm64/6.0.0-LOCAL/kotest-framework-engine-watchosarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchosarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchosarm64/6.0.0-LOCAL/kotest-framework-engine-watchosarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchosarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchosarm64/6.0.0-LOCAL/kotest-framework-engine-watchosarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchosarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchosdevicearm64/6.0.0-LOCAL/kotest-framework-engine-watchosdevicearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchosdevicearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchosdevicearm64/6.0.0-LOCAL/kotest-framework-engine-watchosdevicearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchosdevicearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchosdevicearm64/6.0.0-LOCAL/kotest-framework-engine-watchosdevicearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchosdevicearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchossimulatorarm64/6.0.0-LOCAL/kotest-framework-engine-watchossimulatorarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchossimulatorarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchossimulatorarm64/6.0.0-LOCAL/kotest-framework-engine-watchossimulatorarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchossimulatorarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchossimulatorarm64/6.0.0-LOCAL/kotest-framework-engine-watchossimulatorarm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchossimulatorarm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchosx64/6.0.0-LOCAL/kotest-framework-engine-watchosx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchosx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchosx64/6.0.0-LOCAL/kotest-framework-engine-watchosx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchosx64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-framework-engine-watchosx64/6.0.0-LOCAL/kotest-framework-engine-watchosx64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-framework-engine-watchosx64",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
