{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-common",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-common-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-common-6.0.0-LOCAL.jar",
          "size": 14094,
          "sha512": "9a5a61d71c5067630f6f8399607fa80bea0d42f7d07efd83e625ccf1e4b2a90efd1b1e0e818b81f54a15107f7ea5c863917d960a37f2b5831a3f32521d257801",
          "sha256": "d73bec1ef8372b01a9de69663e8142d8aa559d9b44a45297a6912d0079081cc0",
          "sha1": "574551d331a98d206f41080cea94031991ea00dc",
          "md5": "12a66d5624f942e2294ae625ccfb2e70"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-common-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-common-6.0.0-LOCAL-sources.jar",
          "size": 9634,
          "sha512": "45389658cbc2c4bc410d962028474a7a74ed37b24db25a0545c6a28159085c44d800de2dc25061e4bc67a206b2929224f48b84a554a475ad690c3f0dbba13ca4",
          "sha256": "53a7c800b26c298ebd2d992fe73b6969d52b5719c3eb2b7f6c3ed32c8bd65d7a",
          "sha1": "8c841d7a5e7aa374b8a87b160a0b2fd3e49145f7",
          "md5": "9c26167645a58340192fc1cdc6ba0dc3"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-common-androidnativearm32/6.0.0-LOCAL/kotest-common-androidnativearm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-androidnativearm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-common-androidnativearm32/6.0.0-LOCAL/kotest-common-androidnativearm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-androidnativearm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-common-androidnativearm64/6.0.0-LOCAL/kotest-common-androidnativearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-androidnativearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-common-androidnativearm64/6.0.0-LOCAL/kotest-common-androidnativearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-androidnativearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-common-androidnativex64/6.0.0-LOCAL/kotest-common-androidnativex64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-androidnativex64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-common-androidnativex64/6.0.0-LOCAL/kotest-common-androidnativex64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-androidnativex64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-common-androidnativex86/6.0.0-LOCAL/kotest-common-androidnativex86-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-androidnativex86",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-common-androidnativex86/6.0.0-LOCAL/kotest-common-androidnativex86-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-androidnativex86",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-common-js/6.0.0-LOCAL/kotest-common-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-common-js/6.0.0-LOCAL/kotest-common-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-common-js/6.0.0-LOCAL/kotest-common-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-common-jvm/6.0.0-LOCAL/kotest-common-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-common-jvm/6.0.0-LOCAL/kotest-common-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-common-jvm/6.0.0-LOCAL/kotest-common-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-common-wasm-js/6.0.0-LOCAL/kotest-common-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-common-wasm-js/6.0.0-LOCAL/kotest-common-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-common-wasm-js/6.0.0-LOCAL/kotest-common-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-common-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
