{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/20251023/testballoon-shim-20251023.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251023",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-iosX64Main-20251023.klib",
          "url": "testballoon-shim-iosx64-20251023.klib",
          "size": 19826,
          "sha512": "e712d2d8f35bc0b2d065f0c73bdaf153a02a82d7087f57e509806ed39b406b40275b9dbcf0ef31f7dc89c0723bc3b3e5053d304f20c68f3d9d852d217955456f",
          "sha256": "effedb42544acd4a78e4fa328587f52d8a22e24e921a1e4784a15cb9854ac7cb",
          "sha1": "d6b57b79a261e8f63d24cd3a322f106957acbed5",
          "md5": "80460071b126f630f120b1ca30f6cadd"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-iosx64-20251023-sources.jar",
          "url": "testballoon-shim-iosx64-20251023-sources.jar",
          "size": 3319,
          "sha512": "406ce6795e090ebd44be4599c14cb70ed9bae7b405f79e277dbfcab86f542a1b8062e226313aabcffbee06d7477eeab9be7ddb1f8629cd5eb786139754f4e281",
          "sha256": "c30afff4e1f65eae3fc78dae94a5f35917220a430960fe0802c8628e884a44d4",
          "sha1": "746cb4d28746fbb0d0d174ec3e25a8d607b968dd",
          "md5": "2685749fe0a497fcbbc00fc63788200b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-iosx64-20251023-metadata.jar",
          "url": "testballoon-shim-iosx64-20251023-metadata.jar",
          "size": 261,
          "sha512": "459ddcc74cd97bed786922be7baabd5988f579c1f32a8b1bfd3a866b4f2f4bc9e15e42448cd178979b8a3f7c01cd1d4821ec0cc66193ec9c93fa1766f52a9d34",
          "sha256": "adfcd837184146274b4763d130a3a168aacc345670e0c96290f930323158fec5",
          "sha1": "8da5a1054a000cd480eb0776b4ee773acfad9054",
          "md5": "a80f7a8eb2d55275e7094a2a81b5e2e0"
        }
      ]
    }
  ]
}
