{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-androidNativeX86Main-202509019.klib",
          "url": "testballoon-shim-androidnativex86-202509019.klib",
          "size": 18961,
          "sha512": "181105d4542aefa9785151ef649b9b41d30246b1d726ab8fce225151359f6ab66159e88ec21f571b15e18b655f008b2be1bba4ac53e15fc77dd901edae6ef738",
          "sha256": "433b63223adbf8df2f67d51ce2d4a8dd7f12fef6d5731c1c5a957727d390d027",
          "sha1": "a97c044af2c9e6b3c6aea9ea0b06b598775439a1",
          "md5": "a275a866bb96d4c9995aac2bd1134087"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-androidnativex86-202509019-sources.jar",
          "url": "testballoon-shim-androidnativex86-202509019-sources.jar",
          "size": 3264,
          "sha512": "ed8391e0a2ef7d01b252f8eccbce6f06974286860b01e807c86924d92e1df7f4c2e23d10a7bc3b6481e58e0e4df496137ef00693980ae821a74c92234842394b",
          "sha256": "ac68f54bfc15a91a0525e9e56453984b6e73b352b426b957dd73fc3ab5c94f5f",
          "sha1": "881435a14b967638c917ab2469a2ddeb059688c6",
          "md5": "1368eda18c570e143ee9cecff234a8fa"
        }
      ]
    }
  ]
}
