{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-framework-engine/6.0.0-LOCAL/kotest-framework-engine-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-framework-engine",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-androidNativeX86Main-6.0.0-LOCAL.klib",
          "url": "kotest-framework-engine-androidnativex86-6.0.0-LOCAL.klib",
          "size": 898114,
          "sha512": "4d328f9ab532ec905a129d5314a591991406e69a09908ef5ff15e7d0d3c602a42bebe6353a8fefc4cb6178b3342d70ae0237a7755a7d545282970be8ccc7221b",
          "sha256": "5bf382e5519c427bce7136efcad0db2cdd0abc61fc064e4408a27752fbbd8d72",
          "sha1": "b9cafae2198630d1ac67d8c0814262c9f811ff55",
          "md5": "9675f181fd073814ff812d82a60d4708"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-framework-engine-androidnativex86-6.0.0-LOCAL-sources.jar",
          "url": "kotest-framework-engine-androidnativex86-6.0.0-LOCAL-sources.jar",
          "size": 254450,
          "sha512": "92a8ae393afb4f7e27b20f4b4ee62bc76d34cf5b57e1cb95ba8625513ba8e3f7a480094dc285d8b626120dce969d1ef9eb9b4af7bdaefdf795481b6db794cf08",
          "sha256": "182428b1ba3acd61626c47ff3c47c5a111528b38b01ca2b7ec7ee4f35e4e426c",
          "sha1": "aabf1c71b3665d95f9295d35721a8ca3af697b2e",
          "md5": "1048582fc97c09411d03dc101e430037"
        }
      ]
    }
  ]
}
