{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-arrow-fx-coroutines",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-arrow",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-fx-coroutines",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-fx-coroutines-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-assertions-arrow-fx-coroutines-6.0.0-LOCAL.jar",
          "size": 5927,
          "sha512": "0cee5b9c129f4c35e137031f6f0a69ff68a407a7b406ea11edd6ecef2b04cbf05e7aa4471311df4aebd9f5103934a250deb8c9904b0af057a6b52de9bbdf487e",
          "sha256": "8d910bec3e2d895f966c8f6fc4897e6d5d2d815179fc126c111bca9a3d2cf57c",
          "sha1": "a4caff2297d34a62e1519606fb0ab59ca149469f",
          "md5": "6223084d719e2c98fc80bf8592de6fdf"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-arrow-fx-coroutines-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-arrow-fx-coroutines-6.0.0-LOCAL-sources.jar",
          "size": 5189,
          "sha512": "213f753fc92f5e0df095d79f91afcb2bfaea52d15cec513c50da5c2bb0f65bc93ecd6454cf4dd6d8fcfcd92d172dc2571f4651ab7426d816434d68f07ea80f8e",
          "sha256": "53256b46333a7c37138c0de43eb58401ec40f0df70c11302b73f137ca4e24bac",
          "sha1": "00ad21bba9c65e64c6e3588774923f20f5f7a701",
          "md5": "fa7b6257b0f3cc4cc60c88cbd373f00a"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-fx-coroutines-js/6.0.0-LOCAL/kotest-assertions-arrow-fx-coroutines-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-fx-coroutines-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-fx-coroutines-js/6.0.0-LOCAL/kotest-assertions-arrow-fx-coroutines-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-fx-coroutines-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-fx-coroutines-js/6.0.0-LOCAL/kotest-assertions-arrow-fx-coroutines-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-fx-coroutines-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-fx-coroutines-jvm/6.0.0-LOCAL/kotest-assertions-arrow-fx-coroutines-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-fx-coroutines-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-fx-coroutines-jvm/6.0.0-LOCAL/kotest-assertions-arrow-fx-coroutines-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-fx-coroutines-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-fx-coroutines-jvm/6.0.0-LOCAL/kotest-assertions-arrow-fx-coroutines-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-fx-coroutines-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-fx-coroutines-wasm-js/6.0.0-LOCAL/kotest-assertions-arrow-fx-coroutines-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-fx-coroutines-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-fx-coroutines-wasm-js/6.0.0-LOCAL/kotest-assertions-arrow-fx-coroutines-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-fx-coroutines-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-fx-coroutines-wasm-js/6.0.0-LOCAL/kotest-assertions-arrow-fx-coroutines-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-fx-coroutines-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
