{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-shared/6.0.0-LOCAL-PRE/kotest-assertions-shared-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-assertions-shared",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-js-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-assertions-shared-js-6.0.0-LOCAL-PRE.klib",
          "size": 521811,
          "sha512": "98b67b2bbc8c9f56f3d433ad1e2bfd5c6b7801c5e982abd9f707460aa173075c7354b8729063a6b7eb18ec6725a8e94f16681d6cb620a1cc019e35cb8864174c",
          "sha256": "82cd6330a858eb1cc8afa5fead9b3c4440a0b47c08d4696053847dde554b6846",
          "sha1": "dd9260d4308554aa0dc72d446f91ff499e5abee3",
          "md5": "85c2fe455a85d804d3750aad6412f5ae"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-js-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-assertions-shared-js-6.0.0-LOCAL-PRE.klib",
          "size": 521811,
          "sha512": "98b67b2bbc8c9f56f3d433ad1e2bfd5c6b7801c5e982abd9f707460aa173075c7354b8729063a6b7eb18ec6725a8e94f16681d6cb620a1cc019e35cb8864174c",
          "sha256": "82cd6330a858eb1cc8afa5fead9b3c4440a0b47c08d4696053847dde554b6846",
          "sha1": "dd9260d4308554aa0dc72d446f91ff499e5abee3",
          "md5": "85c2fe455a85d804d3750aad6412f5ae"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotest-assertions-shared-js-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-shared-js-6.0.0-LOCAL-PRE-sources.jar",
          "size": 78871,
          "sha512": "32b3a97b5f639ec6be1c74fdca6ace7f9cdeb599d9ea195cac6ec5b04d1f5a49f0cff97f57868037e297fd0bb05722ff99e744698565d3b2a7d8283c26b568d1",
          "sha256": "df56d2f6f7976fffc9e06a894d59ecae0b9ecf73bfb8c6013a41330a255982de",
          "sha1": "6d1173f0d00c2cd01557455552c3b8bba9d858be",
          "md5": "67e277c42e34dff66ee075d6ce3685f0"
        }
      ]
    }
  ]
}
