{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-property-arrow-optics/6.0.0-LOCAL/kotest-property-arrow-optics-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-property-arrow-optics",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property-arrow",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-optics",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-arrow-optics-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-property-arrow-optics-jvm-6.0.0-LOCAL.jar",
          "size": 112442,
          "sha512": "2f0a98d4ce1df1c9f93d454c0e85b206266c0de7c9d77f62f8f25b3cbbb0c7a1b68d29a73a718dc2712679ff962768d151ecb0428385679cae8b534465db1746",
          "sha256": "41253253c1eeb5b2871d13d300877aa3a351d4dabed9e37c344fb0b7ee321747",
          "sha1": "211be6fec43049ee4aba5e650b43d9f2d3e159d1",
          "md5": "3a731d02dbbe10d10c1c4c253d5d5965"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property-arrow",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-optics",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-functions",
          "version": {
            "requires": "2.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-arrow-optics-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-property-arrow-optics-jvm-6.0.0-LOCAL.jar",
          "size": 112442,
          "sha512": "2f0a98d4ce1df1c9f93d454c0e85b206266c0de7c9d77f62f8f25b3cbbb0c7a1b68d29a73a718dc2712679ff962768d151ecb0428385679cae8b534465db1746",
          "sha256": "41253253c1eeb5b2871d13d300877aa3a351d4dabed9e37c344fb0b7ee321747",
          "sha1": "211be6fec43049ee4aba5e650b43d9f2d3e159d1",
          "md5": "3a731d02dbbe10d10c1c4c253d5d5965"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-property-arrow-optics-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-property-arrow-optics-jvm-6.0.0-LOCAL-sources.jar",
          "size": 5271,
          "sha512": "b0aa690de09fe3d692815caa0efeabcc9ab7d6bef51824c3e7e53df0f91690be294293cbc4121cf8531588dd1a5b3a725cefa2c9c6387e8b4dd701de1d15fe16",
          "sha256": "31669bb69c0409a059385c659213f9a1408467b801213ec61fc1852daeedf727",
          "sha1": "9708b9f9672c101d46e491e9b04f415625030692",
          "md5": "d49d957d3be0a85d7310c99eb3362544"
        }
      ]
    }
  ]
}
