{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-macosX64Main-202509019.klib",
          "url": "testballoon-shim-macosx64-202509019.klib",
          "size": 18973,
          "sha512": "4c082310ac41f4423781bf4611c0cd30588634ea3e4a5ab4420173a3e4545b316917e2e2ee2251a9ac690fe6c64cbc7f083515031cd268ececa9de479fa5550d",
          "sha256": "100bde50e1aa5366bb45f3ce1000a77f055d092c3427a02f90e74385daed7947",
          "sha1": "9ddd772e9b89a22de03577b0ea2d554581481ec7",
          "md5": "29dd7a3a160230f6092fbb15c29c664a"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-macosx64-202509019-sources.jar",
          "url": "testballoon-shim-macosx64-202509019-sources.jar",
          "size": 3178,
          "sha512": "5b92e5b245272d1e343bc6443d4a9857de9f61e70b780b0c796412259620ea57cfe7034d09a7bf651b858425c49156c021f1a9037bc9730c0a54ecb9aa2ce8f0",
          "sha256": "c5e81d2d62e5e3a0b03578016b65979eff091128926b7a0c45736d0a0dcd0e2f",
          "sha1": "9109e078e66994b5c3c23dd13272f027d57c3ed9",
          "md5": "19dff9fbadbdc664609681d724a416aa"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-macosx64-202509019-metadata.jar",
          "url": "testballoon-shim-macosx64-202509019-metadata.jar",
          "size": 261,
          "sha512": "fdbdb09493fac38eb28553de1d0b40bdbcaa1226f211ce144e3c6d398839a058217d45a452f3e684fe87571c7d85555dac760c01debd51220e9f0d8a48737d12",
          "sha256": "52bc0c6c79abac5e1d4a5aaec928c042b40ee457ed55174e83f70533bb022aec",
          "sha1": "b060959d856004813e9965ba8c00177764de16ba",
          "md5": "202864a94bf509137b8e802b7179583f"
        }
      ]
    }
  ]
}
