{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-kotest-assertions/0.6.3-K2.2.20-SNAPSHOT/testBalloon-integration-kotest-assertions-0.6.3-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-kotest-assertions",
    "version": "0.6.3-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-kotest-assertions-androidNativeX86Main-0.6.3-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-integration-kotest-assertions-androidnativex86-0.6.3-K2.2.20-SNAPSHOT.klib",
          "size": 4482,
          "sha512": "53014a727b8dff4cc3d24aa08c6af74476bbdd84162d791b7708abad53b34956828444f69ff9a64fbf5870b2d8e33f98f22056c139e8801cb2a60cd748de45cf",
          "sha256": "36cbe806ddffdbac5a28e91c04d7ed5e9e3a7a12383eb5b2f06ca20c7f20d6a2",
          "sha1": "b22b3b94adb421d8e8678bec0741ebc0c28371ea",
          "md5": "a6c6fb5ec074173f20fed3a968f5ef2d"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-integration-kotest-assertions-androidnativex86-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-kotest-assertions-androidnativex86-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "size": 3228,
          "sha512": "31212c7babf8b5b4fa9b564296b615ba5bb30656ff6f5f23fb7c27bfd214205d6a83e256a9d8a3a314243107f493c3bec5becff683db597558aac5e391524997",
          "sha256": "54f5b6a8eacbd9581931da7de58e6f5e33b7b5f3a890425bc5ed59aacdf44c1f",
          "sha1": "953585d699003149061bb63205c9c0143c874b36",
          "md5": "c91aa499b9f36c00fd79f687b304c33a"
        }
      ]
    }
  ]
}
