{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-shared/6.0.0-LOCAL-PRE/kotest-assertions-shared-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-assertions-shared",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-watchosDeviceArm64Main-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-assertions-shared-watchosdevicearm64-6.0.0-LOCAL-PRE.klib",
          "size": 519030,
          "sha512": "0e5d58e56caac663607db0fe48c1e98ad1f5e1542b03938ddca55d42e16824d5c9c93c668c7410c99cfbf59c0ff56b57cf6b65fc775f2b8f1d08a66333a0cc63",
          "sha256": "67994840a072fccf1e9df3fdcf81bd904da027f571925372784655ac3b3aaaca",
          "sha1": "e6723525cdce0bcf121461dfc5fcea3b14f25fb5",
          "md5": "42b5036ab64f24822bd93565c48210da"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-assertions-shared-watchosdevicearm64-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-shared-watchosdevicearm64-6.0.0-LOCAL-PRE-sources.jar",
          "size": 77938,
          "sha512": "b5c969d0987f5e71a50f6010a1a80107871c9c489921b389014b0db501180b66806644aaf13ee5aadf824378e645262c6fe4a6f8d7c9c3c9f518524df0341505",
          "sha256": "ba74c3e22c240c62b27a683cbe446dbfc3fe135c2b0cc0372cde386d888abe7f",
          "sha1": "dd781dc336d4ffc1824a1d6d4e7c9f97c958f222",
          "md5": "5cc81b4ff78f4fd9674c0a7ab0e9def4"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-watchosdevicearm64-6.0.0-LOCAL-PRE-metadata.jar",
          "url": "kotest-assertions-shared-watchosdevicearm64-6.0.0-LOCAL-PRE-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
