{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-shared/6.0.0-LOCAL/kotest-assertions-shared-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-assertions-shared",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-androidNativeArm64Main-6.0.0-LOCAL.klib",
          "url": "kotest-assertions-shared-androidnativearm64-6.0.0-LOCAL.klib",
          "size": 518983,
          "sha512": "88f95dcfa58e42d9c473c47fb30ba331093debe2293bca4049df6b73ec3dad86092105e32aeb484e3a70fdd283fee90d277e460b05a735e5b22ff9eb0cbc7647",
          "sha256": "1fe26be54ffe6a28d5ce78d774424000c1936203fd8818c066a3ddd3783bf1c3",
          "sha1": "e0314834c2d0284317d19d959a370cfac3184f55",
          "md5": "f9cc677e964312cedeccb5e8b63daf30"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-assertions-shared-androidnativearm64-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-shared-androidnativearm64-6.0.0-LOCAL-sources.jar",
          "size": 77938,
          "sha512": "b5c969d0987f5e71a50f6010a1a80107871c9c489921b389014b0db501180b66806644aaf13ee5aadf824378e645262c6fe4a6f8d7c9c3c9f518524df0341505",
          "sha256": "ba74c3e22c240c62b27a683cbe446dbfc3fe135c2b0cc0372cde386d888abe7f",
          "sha1": "dd781dc336d4ffc1824a1d6d4e7c9f97c958f222",
          "md5": "5cc81b4ff78f4fd9674c0a7ab0e9def4"
        }
      ]
    }
  ]
}
