{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-linuxArm64Main-202509019.klib",
          "url": "testballoon-shim-linuxarm64-202509019.klib",
          "size": 18992,
          "sha512": "21a17e71e55e70752f2aba82d3a6ecf987389be67077053b2584bd86105e80ba6d455f56351b334ad03602681f5fd610c5c703e69852dbe9a1a2029d4723bddc",
          "sha256": "bd5d42ff4c8a39e360ce247fb542e2e48441a0f750404f975a745136b3c9d593",
          "sha1": "36695b5725d560870b4fe30f3df6508f0e2e188b",
          "md5": "2cf25267254ead8184de949bb0cff7b1"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-linuxarm64-202509019-sources.jar",
          "url": "testballoon-shim-linuxarm64-202509019-sources.jar",
          "size": 3200,
          "sha512": "946fe7f316560333cd00553fd9e8895c0fcdd156f331af4a9229c45f0060b7994a465c25120369238d7f01a164cfea77f7607800c0da31c2786cb9a4e2a6d9f8",
          "sha256": "d486156aa9ecc771e6c12145ac53054c8d3d1b435490034d2968173486af087b",
          "sha1": "f9f7dd65f8e751e518eb25419cb8d75987d6dc2c",
          "md5": "ed340eef4bacfc2812a2978d356dfa82"
        }
      ]
    }
  ]
}
