{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-ktor",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-ktor-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-assertions-ktor-6.0.0-LOCAL.jar",
          "size": 3231,
          "sha512": "499931c3e80c04fe81f9313b7d40358ac465d8bc97268b1a862cee180deb0677f0d2884684112a0025005e5abc83056557cef92b4e67ef182551a96887fc288c",
          "sha256": "0afbe8a0ab62b98a7051abee4da2d573e337137b95f10ab22b49dd1f71a975b2",
          "sha1": "b72f281901c34479fdeedf4f6912a6e93def8763",
          "md5": "455ecb55861ec0912ecf45f68194dfdd"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-ktor-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-ktor-6.0.0-LOCAL-sources.jar",
          "size": 2555,
          "sha512": "d3655ac22fd2af34e1e4366c24884b89b3aee761b2c477febbae429a8df7f4291e5f777e8817c18252a99cad34e04a15735d5bc6c4bfa9fa6beedef840a984c5",
          "sha256": "26e1d4a5e207b163ff6f24c296dcf15ffed7a80d45144f36900b0f4981f167d7",
          "sha1": "d98083b8adbbf33f0807d500c77f85595ad21a80",
          "md5": "722e1b5d52841b39f4f728ceb8061fb3"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-ktor-js/6.0.0-LOCAL/kotest-assertions-ktor-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-ktor-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-ktor-js/6.0.0-LOCAL/kotest-assertions-ktor-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-ktor-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-ktor-js/6.0.0-LOCAL/kotest-assertions-ktor-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-ktor-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-ktor-jvm/6.0.0-LOCAL/kotest-assertions-ktor-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-ktor-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-ktor-jvm/6.0.0-LOCAL/kotest-assertions-ktor-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-ktor-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-ktor-jvm/6.0.0-LOCAL/kotest-assertions-ktor-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-ktor-jvm",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
