{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-property/6.0.0-LOCAL/kotest-property-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-property",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-androidNativeArm32Main-6.0.0-LOCAL.klib",
          "url": "kotest-property-androidnativearm32-6.0.0-LOCAL.klib",
          "size": 783074,
          "sha512": "54b199515b4f6bc1680dd1bcad1807c9c39f2131d80df188e76e256c223a98b41d7b95783af1563ee4e498f2e18d70b974084690b1586e2dbf4c30f4dcc8dee4",
          "sha256": "4646f189171eff7507362e809429acfe8ff8c64cb1c913448ddfa0c3a87342aa",
          "sha1": "1b75e7d0238a30d49a205dff3fb3179bbcce3593",
          "md5": "617d25082a88ef4272af86810dcf2fdc"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-property-androidnativearm32-6.0.0-LOCAL-sources.jar",
          "url": "kotest-property-androidnativearm32-6.0.0-LOCAL-sources.jar",
          "size": 104410,
          "sha512": "e8bb801cddb72452ed072e8b781c464e067cf6e0180468b15e6b4fdd34fb83564c69fc32e98ea547353487237299e094ff14e58207673f2c894b0875ce4cb20e",
          "sha256": "fc649612ac43a12d2f5131f36adc73328b4747e5e658e7d224c5783ee6f40ee2",
          "sha1": "6b9f3cc7d279ebb9bb635410452140525df6eed4",
          "md5": "9e2593e855c104fa9eb0fa0fc29ad305"
        }
      ]
    }
  ]
}
