{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.2.0-Beta1+20250409",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0-Beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.2.0-Beta1"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.2.0-Beta1-2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.2.0-Beta1+20250409.jar",
          "url": "k2-2.2.0-Beta1+20250409.jar",
          "size": 162033,
          "sha512": "f98c9ca9d46d5b2acdb358ee6f27360fb26a13e74505676914a3f8b5c5e1a52e151a719a1407bc860054bc86e02bbb13bcb8958d8875be117041d6b4c36a3692",
          "sha256": "c6c5c7ac9289f64a35e30d70814acc8a183ec808126932c3e8199e6eaaf8d66e",
          "sha1": "5ecd41771c427f4a106e1e178138e5f7b193add6",
          "md5": "383fc404a470b12c4c62e14a290a484e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0-Beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.2.0-Beta1"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.2.0-Beta1-2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.2.0-Beta1+20250409.jar",
          "url": "k2-2.2.0-Beta1+20250409.jar",
          "size": 162033,
          "sha512": "f98c9ca9d46d5b2acdb358ee6f27360fb26a13e74505676914a3f8b5c5e1a52e151a719a1407bc860054bc86e02bbb13bcb8958d8875be117041d6b4c36a3692",
          "sha256": "c6c5c7ac9289f64a35e30d70814acc8a183ec808126932c3e8199e6eaaf8d66e",
          "sha1": "5ecd41771c427f4a106e1e178138e5f7b193add6",
          "md5": "383fc404a470b12c4c62e14a290a484e"
        }
      ]
    }
  ]
}
