{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-spring/6.0.0-LOCAL/kotest-extensions-spring-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-extensions-spring",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-spring-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-spring-jvm-6.0.0-LOCAL.jar",
          "size": 29794,
          "sha512": "e4cd070b3060a9b833964d4e59abb69c0aff9742d4b137e7a6a1ad03df7ac272b693d44aae45b1b4db67694fda31ad8381c07cf2ab62ff106d51168c839a4ebc",
          "sha256": "c089638e86ac0fdf84b49786f3152a365c0747573bf3246c96f71b56977498c3",
          "sha1": "b40c17bc43feb283ce9e43dd4115f88276906d92",
          "md5": "01e026e086a80ce56cef0d1e2a4727d3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.15.11"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-spring-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-spring-jvm-6.0.0-LOCAL.jar",
          "size": 29794,
          "sha512": "e4cd070b3060a9b833964d4e59abb69c0aff9742d4b137e7a6a1ad03df7ac272b693d44aae45b1b4db67694fda31ad8381c07cf2ab62ff106d51168c839a4ebc",
          "sha256": "c089638e86ac0fdf84b49786f3152a365c0747573bf3246c96f71b56977498c3",
          "sha1": "b40c17bc43feb283ce9e43dd4115f88276906d92",
          "md5": "01e026e086a80ce56cef0d1e2a4727d3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-extensions-spring-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-extensions-spring-jvm-6.0.0-LOCAL-sources.jar",
          "size": 6609,
          "sha512": "404d70f55f4ffa8c7819138512053ea2fb68d68d13817594188217c3ad34d19c64e9e6027d2971701db29b7a333e609db89f03a431cdedfd3e98eb25083ca55e",
          "sha256": "8f20bc01b4fd769b14b6542519a417dd99c2034ca2a5bb12c45d3bfaaa7b3c0d",
          "sha1": "20c67b90dd37e82de50122e7eec06cd789b31a7d",
          "md5": "7a69eb363663051c90fa08832e38fee6"
        }
      ]
    }
  ]
}
