{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-property-datetime/6.0.0-LOCAL/kotest-property-datetime-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-property-datetime",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-datetime-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-property-datetime-jvm-6.0.0-LOCAL.jar",
          "size": 9984,
          "sha512": "22935a0d44adb082473ba0f3f29e1f23135568c227c43cba92f9b0da90210813b2c452a5d8689d2c4a2e231343d5681467adf850e75d0b6bebcb2b76bcc818b0",
          "sha256": "2e1a819716ad1e11054d2713c1b3efed480468e20778459b44f6353dc630f72f",
          "sha1": "95fe4399da027ac75608d9b6da44d03aa4aa1488",
          "md5": "361f3c1fdb4b614c0d09c4bf7130906f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-datetime-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-property-datetime-jvm-6.0.0-LOCAL.jar",
          "size": 9984,
          "sha512": "22935a0d44adb082473ba0f3f29e1f23135568c227c43cba92f9b0da90210813b2c452a5d8689d2c4a2e231343d5681467adf850e75d0b6bebcb2b76bcc818b0",
          "sha256": "2e1a819716ad1e11054d2713c1b3efed480468e20778459b44f6353dc630f72f",
          "sha1": "95fe4399da027ac75608d9b6da44d03aa4aa1488",
          "md5": "361f3c1fdb4b614c0d09c4bf7130906f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-property-datetime-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-property-datetime-jvm-6.0.0-LOCAL-sources.jar",
          "size": 2321,
          "sha512": "244f648dfc6340d235d3d4977a11ebf90807554457d265b8bd8f18d38968ab409d24e7b95c784c908f63395d405d73b08cb02ce3df7a70f041578871f9470614",
          "sha256": "bd65a98761fda08f9bd822ccd321ff8fa5d08e39bf650a01315ab9cf6e52d277",
          "sha1": "7399b8325c330f539f1ddc48b203a006a9304612",
          "md5": "1a0b7fcd34fb52e48d8169b2bddf2f3a"
        }
      ]
    }
  ]
}
