{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-yaml/6.0.0-LOCAL-PRE/kotest-assertions-yaml-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-assertions-yaml",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "com.charleskorn.kaml",
          "module": "kaml",
          "version": {
            "requires": "0.66.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-yaml-tvosArm64Main-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-assertions-yaml-tvosarm64-6.0.0-LOCAL-PRE.klib",
          "size": 8671,
          "sha512": "6c8f4a1e4c2756975b77e682eff751b71d1ddbea13f77963a7a73043607d0e0992acdc5d667e2640835ba41c4938d6a1a6fdb617ea56039d232cb6cc4cb1c07d",
          "sha256": "2508b4b1c646d35dec402a69669ca02cfa0db8dfb5c652e51742ee45d2f57b95",
          "sha1": "8171d5201c8200ee287ad2ba6274d02c849c05b8",
          "md5": "cbf323046e5337560aee71852de0c44c"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-assertions-yaml-tvosarm64-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-yaml-tvosarm64-6.0.0-LOCAL-PRE-sources.jar",
          "size": 1756,
          "sha512": "7c4df3857b3bec2081b35b3415adc081030f8720f8bea9bfe89f19f79ce10aa6baaf393d56d0384cb19387dc005874a5c743e96ef3fc5216827fb61c2f6412d2",
          "sha256": "c6bcc40dd3d8d253f046d136ca2a1bcf25bf1e16e71159d5bb7db36073c3d7ab",
          "sha1": "fe24caacc606dcffe382770e9ad3bb97138dca17",
          "md5": "97c9b6e287b878d83cc3fbcb567e48d7"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "com.charleskorn.kaml",
          "module": "kaml",
          "version": {
            "requires": "0.66.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-yaml-tvosarm64-6.0.0-LOCAL-PRE-metadata.jar",
          "url": "kotest-assertions-yaml-tvosarm64-6.0.0-LOCAL-PRE-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
