{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-iosArm64Main-202509019.klib",
          "url": "testballoon-shim-iosarm64-202509019.klib",
          "size": 18972,
          "sha512": "e7f9f9f6f01360f38f5bc4c5bfb58e9a6fd9b24f93860f7cfb06e8da147ffcd296629a90b4acf454ad5011904f6b84b480c4b0b550f7d49a4515f34631dfa42a",
          "sha256": "0a53d00557e461eed18d2310ce34aecce29f8e7c0da2711e70a87d5cd0d36146",
          "sha1": "70bf8f9a3cd6d102dd0c3eff7f968cb7eedfa4f3",
          "md5": "67a09803a731f6c73aeb744321fe35a6"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-iosarm64-202509019-sources.jar",
          "url": "testballoon-shim-iosarm64-202509019-sources.jar",
          "size": 3178,
          "sha512": "80ddbb8e9ad1106ee37c9bc9a043e4941d1bc2a8599d022022e9e4ee1dc6723103029cf8b66d86bce98705f28a2612392a41296b6bcb364e859485faf92d0c91",
          "sha256": "7fb6aaaefb5d6da89fd1c3d60a491c32712d34199f2fe53f179cb2571fa62977",
          "sha1": "b23db06fc71d00b92762000befcd8f6fda0c2690",
          "md5": "b707d26a7de9cb9f7fdfe35a2d76cefc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-iosarm64-202509019-metadata.jar",
          "url": "testballoon-shim-iosarm64-202509019-metadata.jar",
          "size": 261,
          "sha512": "cc582fb105e572b89dafa3c5697a9439627cce5e9fecf37d93c6719f3e685324ee0a75ae006ba3aade2930b00c68c51670c286a0e237db1e9ae5e60c65e24ea5",
          "sha256": "21735570e3478634ae76a7be4a4099bcc3959ea3f3d775df5fd66f7fcab6b510",
          "sha1": "81b6909384d413e0b8aaa92195d13a1824e6e6dc",
          "md5": "f70b21bd2751f6a9ee1f98c8a7f7cd2e"
        }
      ]
    }
  ]
}
