{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-wasm-js-202509019.klib",
          "url": "testballoon-shim-wasm-js-202509019.klib",
          "size": 18732,
          "sha512": "4f6cd8de246408297ab0da9d80e5a5160b74b609da35553a30aec28f6a6385da67cc549dc2f0f4fb2d5434087682e37bbd0f6732de24eb4fe33423228eb9c31e",
          "sha256": "7c3869189e65427a20168dd3d053532d24a33a1b4b9cd2be7dbc45caed215035",
          "sha1": "6a07dc570e895584a0257c00d6c7c2242516bd90",
          "md5": "095236c0a86739609701c24986b584bf"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-wasm-js-202509019.klib",
          "url": "testballoon-shim-wasm-js-202509019.klib",
          "size": 18732,
          "sha512": "4f6cd8de246408297ab0da9d80e5a5160b74b609da35553a30aec28f6a6385da67cc549dc2f0f4fb2d5434087682e37bbd0f6732de24eb4fe33423228eb9c31e",
          "sha256": "7c3869189e65427a20168dd3d053532d24a33a1b4b9cd2be7dbc45caed215035",
          "sha1": "6a07dc570e895584a0257c00d6c7c2242516bd90",
          "md5": "095236c0a86739609701c24986b584bf"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "testballoon-shim-wasm-js-202509019-sources.jar",
          "url": "testballoon-shim-wasm-js-202509019-sources.jar",
          "size": 3158,
          "sha512": "ff134df8e8c8bd25fea52ac350948446ec54833895e9727aa86d42a3368afe1fe00e5b43f580edf8a780e9f8ff301e08c136adfa46355f2419f82d1eab02fc37",
          "sha256": "8c0ed5a65418127869913e1e881879770672128abea4348abcafda724ffde756",
          "sha1": "d815aa3a99f9be4ab3d1d8cf7a17429620432adb",
          "md5": "ee3523515cfcd45f9fd1b5ef85e13ee4"
        }
      ]
    }
  ]
}
