{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-allure/6.0.0-LOCAL/kotest-extensions-allure-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-extensions-allure",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.qameta.allure",
          "module": "allure-java-commons",
          "version": {
            "requires": "2.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-allure-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-allure-jvm-6.0.0-LOCAL.jar",
          "size": 19560,
          "sha512": "6d6a612d2a52dc651bf6fefaf141d0d0a0f13aada78806ab58fc73628b3bc0613ac516019c914fde962e7e05666b35e3beb0bbcacf5f4164f2eb487e9b115a96",
          "sha256": "aa2744cf495ae6be77ef1665471500fa1e0e98ca2dabe589adb7a6cfc58d3f1a",
          "sha1": "2477ea09afc822dc5d65794fcca2977926445dc3",
          "md5": "b516f527e736062fb0bcdb8e4cf06eae"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.qameta.allure",
          "module": "allure-java-commons",
          "version": {
            "requires": "2.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-allure-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-allure-jvm-6.0.0-LOCAL.jar",
          "size": 19560,
          "sha512": "6d6a612d2a52dc651bf6fefaf141d0d0a0f13aada78806ab58fc73628b3bc0613ac516019c914fde962e7e05666b35e3beb0bbcacf5f4164f2eb487e9b115a96",
          "sha256": "aa2744cf495ae6be77ef1665471500fa1e0e98ca2dabe589adb7a6cfc58d3f1a",
          "sha1": "2477ea09afc822dc5d65794fcca2977926445dc3",
          "md5": "b516f527e736062fb0bcdb8e4cf06eae"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-extensions-allure-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-extensions-allure-jvm-6.0.0-LOCAL-sources.jar",
          "size": 4775,
          "sha512": "63e574f8a860f4ecead6678d43f52645ed35c8857fefc6fc017215670b3586f0c1d49297e2f89754d76bf681ca81700f227929a9ccc0e208624ffbb7a9e156af",
          "sha256": "51e9849d7d614157a7e2732636d930cceb20bac819e8333dbe1ad565cac6e018",
          "sha1": "8144eb475f271776128661b2c4c3294c38598ec1",
          "md5": "8a35271b595bc24ae0c0e9d493154dcc"
        }
      ]
    }
  ]
}
