{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/0.0.1/kmpotest-0.0.1.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-tvosSimulatorArm64Main-0.0.1.klib",
          "url": "kmpotest-tvossimulatorarm64-0.0.1.klib",
          "size": 38249,
          "sha512": "ef65fa6c697eb6ea37769289fae35f500087ebdb016ca4e454b74563c7505e7ddad7de2c187fa89565cdcd910b52a4e223fca21ba5b782e482dadb4654646a76",
          "sha256": "0da1ddf81fe454428ab55cb141ff539537b62288ce390e328708f28e672fc3c6",
          "sha1": "bca4139866d84563d49f1261f2d8f45dc97ced3d",
          "md5": "fd67350f8afe8055c24075948bd4a2cc"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-tvossimulatorarm64-0.0.1-sources.jar",
          "url": "kmpotest-tvossimulatorarm64-0.0.1-sources.jar",
          "size": 3949,
          "sha512": "0a94bbd8401486ff558fa489db76d037db73020b3cc8ae34df8a40db8206574b305d0039a989ce7bfdf8e144973269364d5d6e4c1b6c68328df29414ec04a8d1",
          "sha256": "0982519d331f584f2638472516e9960a08fe056b1b7b826ba0cd7743fc4f60a3",
          "sha1": "fcc209adb9823d17439eedb6dfed89c0d8036f76",
          "md5": "b9f4ab3189d88acbb03ddf08e6cd77b6"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-tvossimulatorarm64-0.0.1-metadata.jar",
          "url": "kmpotest-tvossimulatorarm64-0.0.1-metadata.jar",
          "size": 261,
          "sha512": "dd06b5cf33d650b9af97146271ca1a6767acacd9ec92609cb58b8aec3fa5035364f933a52d60ce5c98136967454b814611f62cfd723d1f402ff46bb468886386",
          "sha256": "9343944a3e972171329d6cba02f7581aea926e3a0502d44494395f3b02c1be4f",
          "sha1": "29a5ccc38bf6cd1487730187ba2ed17e707216e0",
          "md5": "adadab6ca86ba612076933e09fc286e3"
        }
      ]
    }
  ]
}
