{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-mockserver/6.0.0-LOCAL-PRE/kotest-extensions-mockserver-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-extensions-mockserver",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.mock-server",
          "module": "mockserver-netty",
          "version": {
            "requires": "5.15.0"
          }
        },
        {
          "group": "org.mock-server",
          "module": "mockserver-client-java",
          "version": {
            "requires": "5.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-mockserver-jvm-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-extensions-mockserver-jvm-6.0.0-LOCAL-PRE.jar",
          "size": 7735,
          "sha512": "4855f10ee0eebbd57fc3a8aeb57e7b07e37ad709564b9afc81a1b959bdeee0695f3832babb7b7f17d13cb8c80447394555d8d262325d6328709ffae2c84dfb7f",
          "sha256": "bd0779f9bb7aa85084f5caf9ef973799ef1d31f353f50fd673f488cebfd35f3f",
          "sha1": "7741ad6255d92b768437624c8a33bb77a67f25f2",
          "md5": "fc40aef5a993f291a6606ac214c8f4a4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.mock-server",
          "module": "mockserver-netty",
          "version": {
            "requires": "5.15.0"
          }
        },
        {
          "group": "org.mock-server",
          "module": "mockserver-client-java",
          "version": {
            "requires": "5.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-mockserver-jvm-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-extensions-mockserver-jvm-6.0.0-LOCAL-PRE.jar",
          "size": 7735,
          "sha512": "4855f10ee0eebbd57fc3a8aeb57e7b07e37ad709564b9afc81a1b959bdeee0695f3832babb7b7f17d13cb8c80447394555d8d262325d6328709ffae2c84dfb7f",
          "sha256": "bd0779f9bb7aa85084f5caf9ef973799ef1d31f353f50fd673f488cebfd35f3f",
          "sha1": "7741ad6255d92b768437624c8a33bb77a67f25f2",
          "md5": "fc40aef5a993f291a6606ac214c8f4a4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-extensions-mockserver-jvm-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-extensions-mockserver-jvm-6.0.0-LOCAL-PRE-sources.jar",
          "size": 2312,
          "sha512": "c3cd01ad622286760eaa840401787c297e6b2dfe78539596662a41d33d8b099953164214e9fdaeae2364c54fc37821d58d5c1100d9001f3ba328d0a8e5a5ac22",
          "sha256": "a6dc77f07129c82e713e35621adbaa000255c2de6d8efdc729c5673af2349ac9",
          "sha1": "e875fe6df346ac88bf6fd106ca563499cf22ce41",
          "md5": "668512ab7d910597a9b1ff550888b39d"
        }
      ]
    }
  ]
}
