{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-junitxml/6.0.0-LOCAL-PRE/kotest-extensions-junitxml-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-extensions-junitxml",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-junitxml-jvm-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-extensions-junitxml-jvm-6.0.0-LOCAL-PRE.jar",
          "size": 13036,
          "sha512": "5391e43b224e031e64d67f7b118af6d2c6054c2ae504951d910675f4dc08994dad4a08e88b65799f7080dc8d727faa57a3e7cdf82325f7e037b18d4cec17b377",
          "sha256": "6695177dfe74d072e5e359e7fa5416b73653bc8911a7b44ee4cec9b5943775b3",
          "sha1": "5a484f0fe127a9c22157e45918c6288ff7f4fe70",
          "md5": "3439c6064ce56c7deb750ccc76b477e3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-junitxml-jvm-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-extensions-junitxml-jvm-6.0.0-LOCAL-PRE.jar",
          "size": 13036,
          "sha512": "5391e43b224e031e64d67f7b118af6d2c6054c2ae504951d910675f4dc08994dad4a08e88b65799f7080dc8d727faa57a3e7cdf82325f7e037b18d4cec17b377",
          "sha256": "6695177dfe74d072e5e359e7fa5416b73653bc8911a7b44ee4cec9b5943775b3",
          "sha1": "5a484f0fe127a9c22157e45918c6288ff7f4fe70",
          "md5": "3439c6064ce56c7deb750ccc76b477e3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-extensions-junitxml-jvm-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-extensions-junitxml-jvm-6.0.0-LOCAL-PRE-sources.jar",
          "size": 3460,
          "sha512": "b42324b32a1ec889bef65304e5a18366e92acf3794108f8adb0ac4baae36549028a8ae2434347bb6d78506de40cfd533016e1b95b91c885b5227c7de29c2e071",
          "sha256": "29a147f5d2a101d592b934218f9fc1a90d95b8bc35d6f581c270e98c50fbb03d",
          "sha1": "80ac14e22eca03dcf3c82024b6fd771a5bc7a77e",
          "md5": "814893da81cf65d761baf3456cbf497b"
        }
      ]
    }
  ]
}
