{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-core/6.0.0-LOCAL/kotest-assertions-core-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-assertions-core",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-core-js-6.0.0-LOCAL.klib",
          "url": "kotest-assertions-core-js-6.0.0-LOCAL.klib",
          "size": 538464,
          "sha512": "b52072e05f26ab9e0f4ef8eb806cb3ba3e7f7c196221055bff1973e2b9859779b1de19f37ebbbf502e7620147fd079b937af35ca7d5055d92a20bc0f41d3f5d9",
          "sha256": "6b30916cd7207e1bf609b42f79e83e7fd54a42cf83a4dc26c216807e43aa6aaa",
          "sha1": "030adef32f4732dd70613286cd2c3a4fb3aeda8a",
          "md5": "245ac76282b1698e2ca35da959aa97fe"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-core-js-6.0.0-LOCAL.klib",
          "url": "kotest-assertions-core-js-6.0.0-LOCAL.klib",
          "size": 538464,
          "sha512": "b52072e05f26ab9e0f4ef8eb806cb3ba3e7f7c196221055bff1973e2b9859779b1de19f37ebbbf502e7620147fd079b937af35ca7d5055d92a20bc0f41d3f5d9",
          "sha256": "6b30916cd7207e1bf609b42f79e83e7fd54a42cf83a4dc26c216807e43aa6aaa",
          "sha1": "030adef32f4732dd70613286cd2c3a4fb3aeda8a",
          "md5": "245ac76282b1698e2ca35da959aa97fe"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotest-assertions-core-js-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-core-js-6.0.0-LOCAL-sources.jar",
          "size": 111359,
          "sha512": "47b7a1462e8eb15f29d269eaa44fb426d3d34a153841d678423cbf2fdc24f1f91c865e17c642ff5b3539f6695bdb41dcf4a21e117916c0be1dec8cac89d55f10",
          "sha256": "39f8b710a3b4b8161d943ac287fd2d5bb86b889d40106501e9a29f5a1f3ef159",
          "sha1": "a112485577a6720ccb19f0a8071c6390c34de954",
          "md5": "f838fcd81db1cbe7512526ed24167a59"
        }
      ]
    }
  ]
}
