{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/20251017/testballoon-shim-20251017.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim.aar",
          "url": "testballoon-shim-android-20251017.aar",
          "size": 24688,
          "sha512": "a2d4a56d0372197d8e81405b5ca627c336fcc3de8ca9d46afc8cb9d9687868d50541244ddee9db547628265641520148978011127f4f2d6b38734ebfd077d614",
          "sha256": "3b66e421f2a62b9ff3b6007a9a876e3f60723fe479de2472e25c3276df2a878b",
          "sha1": "38e0e0c8caa4f172bf0bbcc30628f86b37e0bf47",
          "md5": "dd8547a90d5ef64330ffd07cfcc974f4"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim.aar",
          "url": "testballoon-shim-android-20251017.aar",
          "size": 24688,
          "sha512": "a2d4a56d0372197d8e81405b5ca627c336fcc3de8ca9d46afc8cb9d9687868d50541244ddee9db547628265641520148978011127f4f2d6b38734ebfd077d614",
          "sha256": "3b66e421f2a62b9ff3b6007a9a876e3f60723fe479de2472e25c3276df2a878b",
          "sha1": "38e0e0c8caa4f172bf0bbcc30628f86b37e0bf47",
          "md5": "dd8547a90d5ef64330ffd07cfcc974f4"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "testballoon-shim-android-20251017-sources.jar",
          "url": "testballoon-shim-android-20251017-sources.jar",
          "size": 3133,
          "sha512": "f277f922238e10b13e19813066b0259535ed8551ee29b8853477be11a12db4570bbf719d1047e540af607f9083ca4a2e504b7e9132324384e1f10777e4bc4a14",
          "sha256": "d61a39b91a15ff7b2eac0976d799ba6de5bc6f27fd4601958d98dbb6c64ef2a1",
          "sha1": "826942f565a2d1479d2f140126a572632c74f0fa",
          "md5": "938a932f60e7fd7dae253a72115eb0cc"
        }
      ]
    }
  ]
}
