{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250714/kmpotest-20250714.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250714",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-tvosSimulatorArm64Main-20250714.klib",
          "url": "kmpotest-tvossimulatorarm64-20250714.klib",
          "size": 38249,
          "sha512": "ef65fa6c697eb6ea37769289fae35f500087ebdb016ca4e454b74563c7505e7ddad7de2c187fa89565cdcd910b52a4e223fca21ba5b782e482dadb4654646a76",
          "sha256": "0da1ddf81fe454428ab55cb141ff539537b62288ce390e328708f28e672fc3c6",
          "sha1": "bca4139866d84563d49f1261f2d8f45dc97ced3d",
          "md5": "fd67350f8afe8055c24075948bd4a2cc"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-tvossimulatorarm64-20250714-sources.jar",
          "url": "kmpotest-tvossimulatorarm64-20250714-sources.jar",
          "size": 3949,
          "sha512": "0a94bbd8401486ff558fa489db76d037db73020b3cc8ae34df8a40db8206574b305d0039a989ce7bfdf8e144973269364d5d6e4c1b6c68328df29414ec04a8d1",
          "sha256": "0982519d331f584f2638472516e9960a08fe056b1b7b826ba0cd7743fc4f60a3",
          "sha1": "fcc209adb9823d17439eedb6dfed89c0d8036f76",
          "md5": "b9f4ab3189d88acbb03ddf08e6cd77b6"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-tvossimulatorarm64-20250714-metadata.jar",
          "url": "kmpotest-tvossimulatorarm64-20250714-metadata.jar",
          "size": 261,
          "sha512": "ef29641d87932b3aa9774a0d2283bb4012a6d71dc6a3a1d2f1ff93d236358fdabfc839e963b389cb3e4baa8afede32a0ab7b71bdba9db9748b85c36d3df517e8",
          "sha256": "9e9760a50c98acfc6f2756067a21d1c7308d7be8a493b71be5de2875805d59c5",
          "sha1": "ae04256d019ca82114f404dcbba2bf6b375d9bc2",
          "md5": "abb93215337bb2a6fd0a22176633b528"
        }
      ]
    }
  ]
}
