{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.0.10-RC+20240717",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240717"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.10-RC"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "strictly": "5.9.1",
            "requires": "5.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.10-RC+20240717.jar",
          "url": "k2-2.0.10-RC+20240717.jar",
          "size": 10757,
          "sha512": "800b0429d948bfa58ff965fcbb7dd72d4a90e4454c3c7b1d85758321d2aab3692cfed83b96dda3eb19f70e4d174d9bd9c3e577554dd4d1bded1f022ea8139a3a",
          "sha256": "caa309826abdc5eeaf0c73d32e77e2f334bf0d0d438bda271a6cfca8fd48c314",
          "sha1": "c7c0aed8f95382a78e958eb1e90d3f2feabc988c",
          "md5": "6aa5e845078d2a23d1329c6acd7324e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240717"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.10-RC"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "strictly": "5.9.1",
            "requires": "5.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.10-RC+20240717.jar",
          "url": "k2-2.0.10-RC+20240717.jar",
          "size": 10757,
          "sha512": "800b0429d948bfa58ff965fcbb7dd72d4a90e4454c3c7b1d85758321d2aab3692cfed83b96dda3eb19f70e4d174d9bd9c3e577554dd4d1bded1f022ea8139a3a",
          "sha256": "caa309826abdc5eeaf0c73d32e77e2f334bf0d0d438bda271a6cfca8fd48c314",
          "sha1": "c7c0aed8f95382a78e958eb1e90d3f2feabc988c",
          "md5": "6aa5e845078d2a23d1329c6acd7324e5"
        }
      ]
    }
  ]
}
