{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-tvosX64Main-202509019.klib",
          "url": "testballoon-shim-tvosx64-202509019.klib",
          "size": 18968,
          "sha512": "21189cf8311b99a98e0c2398fcaa09adc46c4755254a0aa136eb910ff5189955c95151d7820f6a7445d3a917e02b42db272fb559c6234be9e222e63810cd3917",
          "sha256": "9b012632bf3e7d7586be525333a576738e1391947d338873f4841daa56d877ed",
          "sha1": "4eab099d99a7287f542ca3ea74113cc230577a22",
          "md5": "2f21d9147a0a905bf785e4b27445c62e"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-tvosx64-202509019-sources.jar",
          "url": "testballoon-shim-tvosx64-202509019-sources.jar",
          "size": 3167,
          "sha512": "a43ce3d09f9d6f092b528e6016ab4a4414de53a3f217b9cfb9f7c5bdb05f4f51cfc0756b5f889f2a73d4cdfd81d3d3a5af2e073258bc44fb3d9b7583f353c29e",
          "sha256": "1efb7e77341f98e832897f350601e853f2167b31a23c8e9dc6e45d6810a00d18",
          "sha1": "bb45d0fddd795a1eb9cde427e41b265426566ca9",
          "md5": "e82d488f07bc176b867c34c75cf04993"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-tvosx64-202509019-metadata.jar",
          "url": "testballoon-shim-tvosx64-202509019-metadata.jar",
          "size": 261,
          "sha512": "fdbdb09493fac38eb28553de1d0b40bdbcaa1226f211ce144e3c6d398839a058217d45a452f3e684fe87571c7d85555dac760c01debd51220e9f0d8a48737d12",
          "sha256": "52bc0c6c79abac5e1d4a5aaec928c042b40ee457ed55174e83f70533bb022aec",
          "sha1": "b060959d856004813e9965ba8c00177764de16ba",
          "md5": "202864a94bf509137b8e802b7179583f"
        }
      ]
    }
  ]
}
