{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.0.20+20240917",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240917"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.20-1.0.24"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0-20240905.065253-61"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.20+20240917.jar",
          "url": "k2-2.0.20+20240917.jar",
          "size": 10779,
          "sha512": "c3c6c87468dcc2ce8ca7e50a3aedc9cb792fba9a81fc5b8774c529d3daf9d75adc7e292021a9dcbee1f01ec1f0ad1145ce56caf159f7320320c4271e2caee3b7",
          "sha256": "76f704d5b3a00be10c6e042abb79b2053e730c76088dd29c5adc77f026275bfd",
          "sha1": "ad65d4f1557be8a5f1bab952c088c2c6213a8157",
          "md5": "bd01a05926c4e19f38ce99671c9d5505"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240917"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.20-1.0.24"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0-20240905.065253-61"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.20+20240917.jar",
          "url": "k2-2.0.20+20240917.jar",
          "size": 10779,
          "sha512": "c3c6c87468dcc2ce8ca7e50a3aedc9cb792fba9a81fc5b8774c529d3daf9d75adc7e292021a9dcbee1f01ec1f0ad1145ce56caf159f7320320c4271e2caee3b7",
          "sha256": "76f704d5b3a00be10c6e042abb79b2053e730c76088dd29c5adc77f026275bfd",
          "sha1": "ad65d4f1557be8a5f1bab952c088c2c6213a8157",
          "md5": "bd01a05926c4e19f38ce99671c9d5505"
        }
      ]
    }
  ]
}
