{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "1.9.23+20240319",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240319"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.19"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240319.jar",
          "url": "k2-1.9.23+20240319.jar",
          "size": 10231,
          "sha512": "be1a39d4f0cc0cbc9f472a34930691706aae5054b90e11000b0274e4be8c88e2da0abb3ff38e16807744d12da971696df92a9fc1883f33562b7de26f1162879c",
          "sha256": "b67db4df3c58c60e17dd0e8d74a66c8370cd918f9906c03c3348d17730db4f12",
          "sha1": "b1e33883b3c4eabb0182a5fce1bb75be5d282824",
          "md5": "dd822e9cd6aca55bcb560fbfc4a86896"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240319"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.19"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240319.jar",
          "url": "k2-1.9.23+20240319.jar",
          "size": 10231,
          "sha512": "be1a39d4f0cc0cbc9f472a34930691706aae5054b90e11000b0274e4be8c88e2da0abb3ff38e16807744d12da971696df92a9fc1883f33562b7de26f1162879c",
          "sha256": "b67db4df3c58c60e17dd0e8d74a66c8370cd918f9906c03c3348d17730db4f12",
          "sha1": "b1e33883b3c4eabb0182a5fce1bb75be5d282824",
          "md5": "dd822e9cd6aca55bcb560fbfc4a86896"
        }
      ]
    }
  ]
}
