{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "1.9.23+20240319",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240319"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.19"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240319.jar",
          "url": "k2-1.9.23+20240319.jar",
          "size": 10231,
          "sha512": "240fc83f6f779dde18260b2b4004ea3a82f506ea2617804d8e5f33eab472b4941ea90b62900936915421e1a364a85edf5371ab5fa4b9c802585d2e348b3abb28",
          "sha256": "589e5ae22735b4d02b30233909a1574b0ddfbbfcb233ec67a6067104d3f9f7f8",
          "sha1": "30ec3faf988049628992e77ce1c9a0adb8640a92",
          "md5": "6097b6811d90dcaa99f91f96a65eb517"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240319"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.19"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240319.jar",
          "url": "k2-1.9.23+20240319.jar",
          "size": 10231,
          "sha512": "240fc83f6f779dde18260b2b4004ea3a82f506ea2617804d8e5f33eab472b4941ea90b62900936915421e1a364a85edf5371ab5fa4b9c802585d2e348b3abb28",
          "sha256": "589e5ae22735b4d02b30233909a1574b0ddfbbfcb233ec67a6067104d3f9f7f8",
          "sha1": "30ec3faf988049628992e77ce1c9a0adb8640a92",
          "md5": "6097b6811d90dcaa99f91f96a65eb517"
        }
      ]
    }
  ]
}
