{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "1.9.23+20240501",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240501"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240501.jar",
          "url": "k2-1.9.23+20240501.jar",
          "size": 10385,
          "sha512": "ea152d3a895ec565161e01d16e0e875dca606684dcdcad3ea83d8ccc2ef1d52a87d6db69cbbc648e59c05f0b55e825058b6f937fa363422413695766ec378ecf",
          "sha256": "4bda1101f4134c42feca62e1363e21f11272789e05c2b6729df818bfc534d220",
          "sha1": "b1b1d8b28c77666bee28d5c1f2af45a95938a3b4",
          "md5": "532628d9314f99f7eea6aec1329a256c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240501"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240501.jar",
          "url": "k2-1.9.23+20240501.jar",
          "size": 10385,
          "sha512": "ea152d3a895ec565161e01d16e0e875dca606684dcdcad3ea83d8ccc2ef1d52a87d6db69cbbc648e59c05f0b55e825058b6f937fa363422413695766ec378ecf",
          "sha256": "4bda1101f4134c42feca62e1363e21f11272789e05c2b6729df818bfc534d220",
          "sha1": "b1b1d8b28c77666bee28d5c1f2af45a95938a3b4",
          "md5": "532628d9314f99f7eea6aec1329a256c"
        }
      ]
    }
  ]
}
