{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250715-SNAPSHOT/kmpotest-20250715-SNAPSHOT.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250715-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosArm64Main-20250715-SNAPSHOT.klib",
          "url": "kmpotest-watchosarm64-20250715-SNAPSHOT.klib",
          "size": 38208,
          "sha512": "d5e6bd42c6a3da8fcc165d9faa1953ae01e9501d223fdfd6ec0cc2414487c2773983bba6e4ab46c418cc21e1e9d0969a66a6954518eb82b7eec9571fb391c3ab",
          "sha256": "625cd564e693796885ed492b817e90478d4eb4282b3c54c7a13c5d962e265f0f",
          "sha1": "1f3b5a1402c583ff2ab600f12dac2c19cc095fa8",
          "md5": "5eb9d3f5a1a5ec4ed13bde2dd6fd418a"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-watchosarm64-20250715-SNAPSHOT-sources.jar",
          "url": "kmpotest-watchosarm64-20250715-SNAPSHOT-sources.jar",
          "size": 4518,
          "sha512": "a3bde0879368f4179ae08c9b6419e9e057318f03ac6c0c2805d9eed615557e8ac35244515aa6139a7b47b2b27caa917995fe9dec88a6d3365b9cd14f8bcb5673",
          "sha256": "15974235af9b7868084d4467486a476449ea136f59e50dc0b3b54fbaf6399c86",
          "sha1": "ee852d4709c46ab22de257d34dbbd46b4ebc4bcd",
          "md5": "761466c2323c0e2ffa304b1cf5b885ca"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosarm64-20250715-SNAPSHOT-metadata.jar",
          "url": "kmpotest-watchosarm64-20250715-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "41ac39bd6001a4741e3988dad2c3007909d904e9e631d5b5264357027a88aae330e4c867e5acf78214f1e4175e3b2db6d95d9fe173fafeb5d63e709891b7677c",
          "sha256": "b379614455f4f5b65d68230a4963482b9224683f3b1383aad1824614ca3bf75d",
          "sha1": "0069faa9c3c7e491ca6a0be3e3a6ecc81b5fa535",
          "md5": "4fdac75dc6b6de3f3fb054e6d6054b35"
        }
      ]
    }
  ]
}
