{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.0.0+20240610",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240610"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.0-1.0.22"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "strictly": "5.9.1",
            "requires": "5.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.0+20240610.jar",
          "url": "k2-2.0.0+20240610.jar",
          "size": 10753,
          "sha512": "858454bd2334fd1ae61f5f2887d5f614634e842b7811c0ac95af4fbd3d0daa8b9eb79f5f1858f3234b20af81acaf9eef3e71e61e294304e745912d9263a47cdd",
          "sha256": "8d89174a2337df68124dd0f8ab0e09bd2fd9a2bbfc6e51901a5e2f245247b4eb",
          "sha1": "74fd5b6f732495d227947f872f01f6f064281944",
          "md5": "5f7051a4836c5bc10539c8760cbb9c2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240610"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.0-1.0.22"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "strictly": "5.9.1",
            "requires": "5.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.0+20240610.jar",
          "url": "k2-2.0.0+20240610.jar",
          "size": 10753,
          "sha512": "858454bd2334fd1ae61f5f2887d5f614634e842b7811c0ac95af4fbd3d0daa8b9eb79f5f1858f3234b20af81acaf9eef3e71e61e294304e745912d9263a47cdd",
          "sha256": "8d89174a2337df68124dd0f8ab0e09bd2fd9a2bbfc6e51901a5e2f245247b4eb",
          "sha1": "74fd5b6f732495d227947f872f01f6f064281944",
          "md5": "5f7051a4836c5bc10539c8760cbb9c2b"
        }
      ]
    }
  ]
}
