{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-androidNativeArm32Main-202509019.klib",
          "url": "testballoon-shim-androidnativearm32-202509019.klib",
          "size": 18975,
          "sha512": "b94261d790e552f78a50ce6121512da9666a69ba287b8fd3a141046977d31d30a0d1ecbc54f5cdc37c078b069fb12259370be300087fb4ed33864d3d78452c45",
          "sha256": "04cf486215408a69062c9f461f4594ed468b6df4fcbcf72c75236dc7a9e542ee",
          "sha1": "119e9f25eaa7ef5f43523d998e76d09b0216ec87",
          "md5": "d30362c5dbb9b8d12a93b25fb47bc37d"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-androidnativearm32-202509019-sources.jar",
          "url": "testballoon-shim-androidnativearm32-202509019-sources.jar",
          "size": 3286,
          "sha512": "2f706a314e57a69a8d184ef05222c41487458f9b769025ba01b4db9cf9cefd8892f607074a70a60b1ae3474bfd1252b7eed31cafcf0b3144cd3e708278e6d56a",
          "sha256": "10e509274a0420f5bd6b7f8e8ceed18a3cb92b81a7b4fbdff6a5e09882fc8af5",
          "sha1": "bef864bd413051d7136affb7a7893499f330de46",
          "md5": "36f94ce7975f6d4466a73cb8be717c97"
        }
      ]
    }
  ]
}
