{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251107/testhelper-20251107.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251107",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-macosArm64Main-20251107.klib",
          "url": "testhelper-macosarm64-20251107.klib",
          "size": 6114,
          "sha512": "597e44c8f665ebc27809b8177dfd83aa037ccff8c35bc211e061e5d83973230ac775240094e3b5072c2e860d00b111ddeaf8e1a335020dd3e3f06a091b330ad4",
          "sha256": "9d960645e82f4b095daf3ab758dfad7619cf162580d826467c2c937df1ef25d5",
          "sha1": "ec7bcd2fd94ca7944a03cf5466251cd14653962b",
          "md5": "47afc8a76c4dd8112dca024604ea9d0a"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-macosarm64-20251107-sources.jar",
          "url": "testhelper-macosarm64-20251107-sources.jar",
          "size": 1904,
          "sha512": "bd842e951e1948add275390a812ebd26b506fb40106ec18a6e7343c1d2821f8a5b394b904a1e69a2286c3bf21d539fbd201869035e0f7afb78f24af61f1c28c9",
          "sha256": "d12dcb3885666f306f614dad3a117c956e7b840f6b5eadb07fd3d67c826c3980",
          "sha1": "ad77c36734533482b09fefd2e2232a80a9e77f84",
          "md5": "363076ecde671a07182e5316cf6e3c8d"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-macosarm64-20251107-metadata.jar",
          "url": "testhelper-macosarm64-20251107-metadata.jar",
          "size": 261,
          "sha512": "d7bdd15dd7f51dc10634a4cfedc513f56d91364e7903dd24642e3222e553bcaf5d6e9b22828e23e8e76c9e425c56b9efec1c20dd26acf93ac83d525b3a242d88",
          "sha256": "cd60835a5a495a2756f7bc4e9a9b281ae12c6d1aa4d5cc23700b7c2bb75d68a8",
          "sha1": "da11c82c5187f10a3045bbb8ae3d8f9f6a5cd92a",
          "md5": "39aa720f37e7fa21fd0e1031e2df21b1"
        }
      ]
    }
  ]
}
