{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-property/6.0.0-LOCAL/kotest-property-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-property",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-wasm-js-6.0.0-LOCAL.klib",
          "url": "kotest-property-wasm-js-6.0.0-LOCAL.klib",
          "size": 784846,
          "sha512": "2574e2d320f25f56e8a7fe75bed543a2982f0a936745b1a1565357c2f1e5bbd947cf8faa38eb377b0957e4920dbfbe74fceb0765c222ffbe1e0690c767d0e6ad",
          "sha256": "f0811cbd53f5cf7ab6f896fd58b0b054f1652c2f9a7090574225b33569140d6a",
          "sha1": "945289abd9ecf49b89a35469f14e38605e154643",
          "md5": "f4fe3303e2e2e8a924e6f6087cdb6f03"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-wasm-js-6.0.0-LOCAL.klib",
          "url": "kotest-property-wasm-js-6.0.0-LOCAL.klib",
          "size": 784846,
          "sha512": "2574e2d320f25f56e8a7fe75bed543a2982f0a936745b1a1565357c2f1e5bbd947cf8faa38eb377b0957e4920dbfbe74fceb0765c222ffbe1e0690c767d0e6ad",
          "sha256": "f0811cbd53f5cf7ab6f896fd58b0b054f1652c2f9a7090574225b33569140d6a",
          "sha1": "945289abd9ecf49b89a35469f14e38605e154643",
          "md5": "f4fe3303e2e2e8a924e6f6087cdb6f03"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotest-property-wasm-js-6.0.0-LOCAL-sources.jar",
          "url": "kotest-property-wasm-js-6.0.0-LOCAL-sources.jar",
          "size": 104426,
          "sha512": "045d46a7586a131e6584f1873528dfffbc06da83550ec334a722c91aed71c49ccb51fe709434a0041fc0698c7f50ec5b6498ca8b12b578f80ffc4f9913bbe735",
          "sha256": "6d664a0fdca4ba256a719de53606ed6875502b9eba52664bad43cd284fb2444b",
          "sha1": "efb1112e6396625467d41616decf3a7f6fa782bd",
          "md5": "4e7d8fc11e274713587f8f56f8d9f444"
        }
      ]
    }
  ]
}
