{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-framework-engine/6.0.0-LOCAL/kotest-framework-engine-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-framework-engine",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-androidNativeArm32Main-6.0.0-LOCAL.klib",
          "url": "kotest-framework-engine-androidnativearm32-6.0.0-LOCAL.klib",
          "size": 898125,
          "sha512": "6796ecf607bd7d5020464f61193ff51013ddbc33df1eec0c4f1d9805fb6d9521b50b42064d95f126f98a5a6e4f8539f8a42448476d874928bcbd7b1b519a07a9",
          "sha256": "f9c5341f2574b15bd2f9db4e47999ba271733afa595c0226659ac74d620c86a4",
          "sha1": "338fe4484db3840c75dd61afa0dc397daac17abd",
          "md5": "67c6d03458739d7e596133da40292039"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-framework-engine-androidnativearm32-6.0.0-LOCAL-sources.jar",
          "url": "kotest-framework-engine-androidnativearm32-6.0.0-LOCAL-sources.jar",
          "size": 254450,
          "sha512": "92a8ae393afb4f7e27b20f4b4ee62bc76d34cf5b57e1cb95ba8625513ba8e3f7a480094dc285d8b626120dce969d1ef9eb9b4af7bdaefdf795481b6db794cf08",
          "sha256": "182428b1ba3acd61626c47ff3c47c5a111528b38b01ca2b7ec7ee4f35e4e426c",
          "sha1": "aabf1c71b3665d95f9295d35721a8ca3af697b2e",
          "md5": "1048582fc97c09411d03dc101e430037"
        }
      ]
    }
  ]
}
