{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-property-lifecycle/6.0.0-LOCAL/kotest-property-lifecycle-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-property-lifecycle",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-lifecycle-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-property-lifecycle-jvm-6.0.0-LOCAL.jar",
          "size": 12038,
          "sha512": "67504e5d06c1d93224d62ebeb900f41f664e673833df1c202237c86aa51c1d5692040f3b11de8ed6fb561f4157144950a6af2831bdbe412e9a27dd032681c888",
          "sha256": "0b8cb532d7ccb080da45039c1c0f61224ca075ab202815dc9c73b351c20bfd95",
          "sha1": "f5212014685634b1d95df153d64e79efa15084d3",
          "md5": "1cf3172b3eeb2553f4c91d570ee7f4e8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-lifecycle-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-property-lifecycle-jvm-6.0.0-LOCAL.jar",
          "size": 12038,
          "sha512": "67504e5d06c1d93224d62ebeb900f41f664e673833df1c202237c86aa51c1d5692040f3b11de8ed6fb561f4157144950a6af2831bdbe412e9a27dd032681c888",
          "sha256": "0b8cb532d7ccb080da45039c1c0f61224ca075ab202815dc9c73b351c20bfd95",
          "sha1": "f5212014685634b1d95df153d64e79efa15084d3",
          "md5": "1cf3172b3eeb2553f4c91d570ee7f4e8"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-property-lifecycle-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-property-lifecycle-jvm-6.0.0-LOCAL-sources.jar",
          "size": 1468,
          "sha512": "5fd4c3a0d24c6ab27b1f5c7b919250e5298e46898761cc580f968acd43750ea4fcdc8b52dd27fa6a538213d284a20817bef28033a3803053952e6b4cf976ae8a",
          "sha256": "b2b9bb642a3d1afd9ee3eb87edd7f05fccdf517920ff842c2b7bb933e1d6553f",
          "sha1": "324e1892502cbc265df9584ef96a809645e66c78",
          "md5": "cea07e4c53ee2523bdead40b73eeefb9"
        }
      ]
    }
  ]
}
