{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-arrow/6.0.0-LOCAL/kotest-assertions-arrow-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-assertions-arrow",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-wasm-js-6.0.0-LOCAL.klib",
          "url": "kotest-assertions-arrow-wasm-js-6.0.0-LOCAL.klib",
          "size": 25635,
          "sha512": "4938785bd5c72e658142fc9e555ac34f47fb2d72ca0eef3111aec24cf765e936355d26b14b1e83ac7d3e8556d40291da64e5891fd6daf08ad3af7d8f6a08b7c4",
          "sha256": "9ea5f56b20499d8803b4c82ce1d51e2f11e7fb89477a72259c5cba0684a44ea5",
          "sha1": "d8289b43069726a5bac39c3d2ada6fb7663fa306",
          "md5": "33ad88adcdd2cc47eed21aa846e31bf4"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-wasm-js-6.0.0-LOCAL.klib",
          "url": "kotest-assertions-arrow-wasm-js-6.0.0-LOCAL.klib",
          "size": 25635,
          "sha512": "4938785bd5c72e658142fc9e555ac34f47fb2d72ca0eef3111aec24cf765e936355d26b14b1e83ac7d3e8556d40291da64e5891fd6daf08ad3af7d8f6a08b7c4",
          "sha256": "9ea5f56b20499d8803b4c82ce1d51e2f11e7fb89477a72259c5cba0684a44ea5",
          "sha1": "d8289b43069726a5bac39c3d2ada6fb7663fa306",
          "md5": "33ad88adcdd2cc47eed21aa846e31bf4"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotest-assertions-arrow-wasm-js-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-arrow-wasm-js-6.0.0-LOCAL-sources.jar",
          "size": 5886,
          "sha512": "47f310168f28a95b4891a58033e2d2f033c378cf1df484945f61e2246699c7a28d7f88b3ac756dec60b4eeeed90896f4320c7b8b11887ff1f20e5dbc5eb6f376",
          "sha256": "c79bc48d7979091cdee82371143e7d9d6aee6075362a6cac7928162e416fce25",
          "sha1": "4326d6be6dea17da849809ee10b7d03f17366b05",
          "md5": "1b8fe5fcd85a859b5d4532f68c7d1e4f"
        }
      ]
    }
  ]
}
