{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-yaml/6.0.0-LOCAL/kotest-assertions-yaml-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-assertions-yaml",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "com.charleskorn.kaml",
          "module": "kaml",
          "version": {
            "requires": "0.66.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-yaml-iosX64Main-6.0.0-LOCAL.klib",
          "url": "kotest-assertions-yaml-iosx64-6.0.0-LOCAL.klib",
          "size": 8651,
          "sha512": "fbbaa57089362454ab0641f3c979db67e39beca843ecc68f55dc54a130c67c96c1b57e81b8530277f2dc0827fc30eac09d851affd80ea60f83952053e79a2531",
          "sha256": "3f1126118a272729f104ea5719a6066ac351c7ec1a1267b7a286eb49e01b9afe",
          "sha1": "d02b1bf7cd32e2b30279db95aeb5b6f622cdfa17",
          "md5": "04c38ed02e9a2dad7a2a3fc40d12aab7"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-assertions-yaml-iosx64-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-yaml-iosx64-6.0.0-LOCAL-sources.jar",
          "size": 1756,
          "sha512": "7c4df3857b3bec2081b35b3415adc081030f8720f8bea9bfe89f19f79ce10aa6baaf393d56d0384cb19387dc005874a5c743e96ef3fc5216827fb61c2f6412d2",
          "sha256": "c6bcc40dd3d8d253f046d136ca2a1bcf25bf1e16e71159d5bb7db36073c3d7ab",
          "sha1": "fe24caacc606dcffe382770e9ad3bb97138dca17",
          "md5": "97c9b6e287b878d83cc3fbcb567e48d7"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "com.charleskorn.kaml",
          "module": "kaml",
          "version": {
            "requires": "0.66.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-yaml-iosx64-6.0.0-LOCAL-metadata.jar",
          "url": "kotest-assertions-yaml-iosx64-6.0.0-LOCAL-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
