{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/20251003/testballoon-shim-20251003.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251003",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim.aar",
          "url": "testballoon-shim-android-20251003.aar",
          "size": 24776,
          "sha512": "42b599fdb3c004e6559bddd71312a84e6df5b915ee9b83512c5bd0f255aabdc0e398a10f72a9e0e37a122858712eba853c7a9d3d395280eb8258010a7b9ff2d5",
          "sha256": "55c3f2b39775545e70c26e421a30455462dd4292541c5808506c6b18bddbc3fc",
          "sha1": "073c9c179f29dd6bc242ae15d22fecdd4bb3fae6",
          "md5": "39cf44fe17524815bb6e9f6d29477109"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim.aar",
          "url": "testballoon-shim-android-20251003.aar",
          "size": 24776,
          "sha512": "42b599fdb3c004e6559bddd71312a84e6df5b915ee9b83512c5bd0f255aabdc0e398a10f72a9e0e37a122858712eba853c7a9d3d395280eb8258010a7b9ff2d5",
          "sha256": "55c3f2b39775545e70c26e421a30455462dd4292541c5808506c6b18bddbc3fc",
          "sha1": "073c9c179f29dd6bc242ae15d22fecdd4bb3fae6",
          "md5": "39cf44fe17524815bb6e9f6d29477109"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "testballoon-shim-android-20251003-sources.jar",
          "url": "testballoon-shim-android-20251003-sources.jar",
          "size": 3133,
          "sha512": "f277f922238e10b13e19813066b0259535ed8551ee29b8853477be11a12db4570bbf719d1047e540af607f9083ca4a2e504b7e9132324384e1f10777e4bc4a14",
          "sha256": "d61a39b91a15ff7b2eac0976d799ba6de5bc6f27fd4601958d98dbb6c64ef2a1",
          "sha1": "826942f565a2d1479d2f140126a572632c74f0fa",
          "md5": "938a932f60e7fd7dae253a72115eb0cc"
        }
      ]
    }
  ]
}
