{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-now/6.0.0-LOCAL/kotest-extensions-now-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-extensions-now",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-now-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-now-jvm-6.0.0-LOCAL.jar",
          "size": 10083,
          "sha512": "e67c363bd830b6a60ff6a29e0e55f7cdd9204003bba0ac16aa97c473efb07b3ef449c3a6fb34e8f60ee3ae109712abec2a0d2f5b9f9e507d750fed418318a4b6",
          "sha256": "81925a713a580d5a63ee30c2d1999d00b856b69fb777f30e10129338c4c58bab",
          "sha1": "f955f590877772b06a25d2b7496eff458e108202",
          "md5": "a5dbfcceff70503a9c08993e7de168d0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.17"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-now-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-now-jvm-6.0.0-LOCAL.jar",
          "size": 10083,
          "sha512": "e67c363bd830b6a60ff6a29e0e55f7cdd9204003bba0ac16aa97c473efb07b3ef449c3a6fb34e8f60ee3ae109712abec2a0d2f5b9f9e507d750fed418318a4b6",
          "sha256": "81925a713a580d5a63ee30c2d1999d00b856b69fb777f30e10129338c4c58bab",
          "sha1": "f955f590877772b06a25d2b7496eff458e108202",
          "md5": "a5dbfcceff70503a9c08993e7de168d0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-extensions-now-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-extensions-now-jvm-6.0.0-LOCAL-sources.jar",
          "size": 2235,
          "sha512": "1eed8b0ad39e2b0c7d2789e54a4f9365190969d900dae20e10febf9bb613b3982beed88aef1cbc2b8b22ef5170afb5db6d31b278db85428cbd276e9ce545c1b2",
          "sha256": "cb0d4a97f694f54b243d72fd4b66de9346f38819c75e92ba8724686bca8cb4a1",
          "sha1": "c05d41a49751ce6de7f90c4f794de8425638c099",
          "md5": "bfde9823f5dddd3ab5a570805ff7e269"
        }
      ]
    }
  ]
}
