{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-common/6.0.0-LOCAL/kotest-common-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-common",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-common-iosX64Main-6.0.0-LOCAL.klib",
          "url": "kotest-common-iosx64-6.0.0-LOCAL.klib",
          "size": 28751,
          "sha512": "ad36a11d37cc85e010783e3d08e2a492a87beaa226cfb98dec023704ed02db7723618de22ea006936750cf48dab36f05b36daa34230ebe20eee7a1da8a83185d",
          "sha256": "162e429d2dedd4f9566fe95ac557da0ed91a4f2483a49964e911b3004ae4b094",
          "sha1": "e86cfd747f9be09fd2d8e374af85dd691dea5822",
          "md5": "6c8adda6ef9b713d218bfe181a725221"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-common-iosx64-6.0.0-LOCAL-sources.jar",
          "url": "kotest-common-iosx64-6.0.0-LOCAL-sources.jar",
          "size": 8119,
          "sha512": "0caf444a201bf9d61f7d677787ee7974a0c20118a65e8c5293ed5291a9fa21a401f404ed7146d283da97d5716aaea0b0806d6388132bdfbcc830ed42183599c2",
          "sha256": "95156022732dac7ca3157a3c11c4f21f40344bf258b48115ac68bd7559ee4fc9",
          "sha1": "b1c173c573b0722ee82dfb3e1d2e1ed23292943e",
          "md5": "7d6e3d9f2e28eda894bd6561856eddac"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-common-iosx64-6.0.0-LOCAL-metadata.jar",
          "url": "kotest-common-iosx64-6.0.0-LOCAL-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
