{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250727/kmpotest-20250727.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250727",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosSimulatorArm64Main-20250727.klib",
          "url": "kmpotest-watchossimulatorarm64-20250727.klib",
          "size": 39777,
          "sha512": "06ccea8e227f96606bfaaa8b27374da676b05cc6702c6034e523bf329ae1c50979831a8a45fcfeafe9a9eadffaea60e4b23721791b8c05da1c678ff30f822232",
          "sha256": "215cfb4140f34363ada1d488b6b1d3a89355a2f9354ac7d1f22ddd5c152f3027",
          "sha1": "80380c682e404beb757351a7b7d05be22b3c3319",
          "md5": "1a03cb6d8aecf2f580b0d0a590252e0c"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-watchossimulatorarm64-20250727-sources.jar",
          "url": "kmpotest-watchossimulatorarm64-20250727-sources.jar",
          "size": 4436,
          "sha512": "ad740786f0fb56b911c0d31bf86c60c801ceef6e76d9aa932b0377051168d7e91b0ae23bf398601884009bac4b3869d177b26943951eaced151dd9d88a0f3561",
          "sha256": "7c95e01bc53fe32f20159bafd9ae777a7ce03c191c6e3e72bbb2d86829063612",
          "sha1": "bff7916c227d981ade358884d15aa3b04894129c",
          "md5": "38c16b46ee7b254a55f7e68fdb4035c8"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchossimulatorarm64-20250727-metadata.jar",
          "url": "kmpotest-watchossimulatorarm64-20250727-metadata.jar",
          "size": 261,
          "sha512": "1365a43c62c05236049b2cfb5df48ff556806f3c4b49fb78a77ea96e4cd52afc545a62afeacaafb04263d9ffd7bfc45eae6efa7d591968a1e601bf4597d3baa3",
          "sha256": "0e22ca79a10c712ffa891c634981bdfec9032d69cc5e2353542024270c3c1917",
          "sha1": "99206441326d8afabfc99e0c46edca386727c64f",
          "md5": "f9e31d68fd5ff981aca53213273ea960"
        }
      ]
    }
  ]
}
