{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.0.0+20240619",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240619"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.0-1.0.22"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "strictly": "5.9.1",
            "requires": "5.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.0+20240619.jar",
          "url": "k2-2.0.0+20240619.jar",
          "size": 10753,
          "sha512": "15c29be31a379042cffc95e396b5cb276c45e569a84813bac6fdd95cee968362aef81e3315191a845313d5fb3b7a4a02bc125acee0d809660f991b5bb48c612e",
          "sha256": "3edb75d3b09ff77b3a40aef777425f95d329ae3e812096f932e39f7781fa80f5",
          "sha1": "baddf7fd1cd651276ce1c0d91183a1896d0d5e76",
          "md5": "4fcb75f039d25774f3cfdfbd7dd3c1ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240619"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.0-1.0.22"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "strictly": "5.9.1",
            "requires": "5.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.0+20240619.jar",
          "url": "k2-2.0.0+20240619.jar",
          "size": 10753,
          "sha512": "15c29be31a379042cffc95e396b5cb276c45e569a84813bac6fdd95cee968362aef81e3315191a845313d5fb3b7a4a02bc125acee0d809660f991b5bb48c612e",
          "sha256": "3edb75d3b09ff77b3a40aef777425f95d329ae3e812096f932e39f7781fa80f5",
          "sha1": "baddf7fd1cd651276ce1c0d91183a1896d0d5e76",
          "md5": "4fcb75f039d25774f3cfdfbd7dd3c1ce"
        }
      ]
    }
  ]
}
