{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251109/testhelper-20251109.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251109",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchosX64Main-20251109.klib",
          "url": "testhelper-watchosx64-20251109.klib",
          "size": 6109,
          "sha512": "aff6ca0f7d81c1cf05719fd2106f01836c29c6490d19028ba34068f01b6bc99f01ed98152ef7f1b160c99b73b5f4cb47200990fb600e33e09f562c5c79ad4df8",
          "sha256": "58ddc2fbbd28aa027c5598534da4dd5c09a71bf1c8b7cf2372565c069b683dcc",
          "sha1": "7d0c588a91adcee445dcad1ffcfe7a75810cf983",
          "md5": "bb7121f1e77ee1b5cfb633852ab8583d"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-watchosx64-20251109-sources.jar",
          "url": "testhelper-watchosx64-20251109-sources.jar",
          "size": 1902,
          "sha512": "8f27b92df640bbecc9d8771250ed6417cd599122c29aeaa933cc9b0e9abf940fd2b18dcb9ba6a987bd9194126754086cdeb636ab6e7e753f8249c009bd4a1daa",
          "sha256": "7981816a42d6576d07d8f97f050362b74fe493f922920aea76e4380bb1a88359",
          "sha1": "110602155ed315f0e39e8e051b44f2f3889b8965",
          "md5": "610cdf0354d6fcf246b8da993123b920"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchosx64-20251109-metadata.jar",
          "url": "testhelper-watchosx64-20251109-metadata.jar",
          "size": 261,
          "sha512": "6c0a76c069258c0e30ae6d100f6c935173f1ea208b8f6815e8c9be5f3780e032a9eba693f32a06cd70af2d6b6d2dd8a783f63a1bb4074fe373e212cbda9c9dad",
          "sha256": "ed35cb1256ed5be9452524e67c91fa0c6fda832339935bc384916061abb1f7bf",
          "sha1": "82ebe9c71e46de6e6ab653d0e1ff19cab63d8037",
          "md5": "ea7f96ffcb01dd077418f463e0de2438"
        }
      ]
    }
  ]
}
