{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251114/testhelper-20251114.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-macosArm64Main-20251114.klib",
          "url": "testhelper-macosarm64-20251114.klib",
          "size": 6089,
          "sha512": "eb859af19fdb4d6019aab87a14ef7419cb65e295ea8b651f4355945adac3f42c11758fce2653038a1e0dc46c6c3d796293e77c345baa216444045cdae0673ed2",
          "sha256": "6b3d673beeb780d09a4b6b5f098ee2fa5a4949fc11c56c1da39adb52ea9750e5",
          "sha1": "18ef73e6326546cc2a4e51f4b9a07e87abdaa425",
          "md5": "111c927092ebe198934b15ca41eedf90"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-macosarm64-20251114-sources.jar",
          "url": "testhelper-macosarm64-20251114-sources.jar",
          "size": 1904,
          "sha512": "bd842e951e1948add275390a812ebd26b506fb40106ec18a6e7343c1d2821f8a5b394b904a1e69a2286c3bf21d539fbd201869035e0f7afb78f24af61f1c28c9",
          "sha256": "d12dcb3885666f306f614dad3a117c956e7b840f6b5eadb07fd3d67c826c3980",
          "sha1": "ad77c36734533482b09fefd2e2232a80a9e77f84",
          "md5": "363076ecde671a07182e5316cf6e3c8d"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-macosarm64-20251114-metadata.jar",
          "url": "testhelper-macosarm64-20251114-metadata.jar",
          "size": 261,
          "sha512": "496140a1b8712773b136158f315962c5ac8acbbf9d6e0dc058766606db8eefbd0ed04a5ddf9bb8480fb657c91ba7547eb03576da659c66ad2cf3190e84d30acc",
          "sha256": "eb430ca0659c4c16af3ed54f92be38cd9087d548d6c7d754f70539af2af9d22c",
          "sha1": "cf60fe3ae54540715e6e7483d5df0177be483ae0",
          "md5": "de1265c3620a80dec48bfe5fdeaaecb6"
        }
      ]
    }
  ]
}
