{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-koin/6.0.0-LOCAL/kotest-extensions-koin-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-extensions-koin",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-koin-mingwX64Main-6.0.0-LOCAL.klib",
          "url": "kotest-extensions-koin-mingwx64-6.0.0-LOCAL.klib",
          "size": 9807,
          "sha512": "18950fb97bf5151302488d5aefcab3a4dde5f37d0e6017a71241116b60a445b26dc76f90a7f62f7f2fc9ba932c858bfd400c5bd219a541d7ea6c229652f74826",
          "sha256": "f0c856eb4658e2abad6ae4884e1604e14f13f79e994a67ceb2bef16656c0e618",
          "sha1": "109cdab9c0a628169781fdabad634f7264e41cb3",
          "md5": "7dabadaf69ba1e15b27a1e87573f14c7"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-extensions-koin-mingwx64-6.0.0-LOCAL-sources.jar",
          "url": "kotest-extensions-koin-mingwx64-6.0.0-LOCAL-sources.jar",
          "size": 1914,
          "sha512": "d24b705b1e846c21232846f56774368cfe714df6f42b41ef69fbcc10e781e1a6c7d4d8175a340a8b4cd987e437dc8797d84ebb373cdaeb2d2869f323ded03c44",
          "sha256": "969a405501f838614b715e11b14f19f12fceb6cf5a992d43adc1a19e0564f908",
          "sha1": "1ecdff34977c560614b258fd47225b380be410a5",
          "md5": "513a077f681c429e302f50e55dc28ef1"
        }
      ]
    }
  ]
}
