{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-extensions-koin",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-koin-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-koin-6.0.0-LOCAL.jar",
          "size": 3233,
          "sha512": "86a44486e060e5103f97b593ff58a10f58279cf070875500eb7d7291b7e2dd10c2a5c00bc676d2ade5122f266a731b7baf1b9ed4da0a1688aaf2f0e4667776e5",
          "sha256": "9eca0d69e8f8d598e06b3252df060f0896d7313fd9ac716c57c106bf26d8c311",
          "sha1": "115e964b8289cfad721a9f41679055f705a01b5e",
          "md5": "1fbff80c6e0df912833c61d2c5e78811"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-extensions-koin-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-extensions-koin-6.0.0-LOCAL-sources.jar",
          "size": 1921,
          "sha512": "90abf70609469a92a4d21efe1e3450939678a685c5c59e2293ba6bda8c7618a8a13522139b7a9c9cb2e873c71fac2297385d0671e078c5bbc7cb80c124446589",
          "sha256": "005c8e142c3177baedc3130fb2ed2067171fa388a1b9c2218ad848d94516147b",
          "sha1": "587d26289d3c20e40b135a90ba4fd791758f6ba0",
          "md5": "f412afa78e5f7c5fd02cb0b819ccda38"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-extensions-koin-js/6.0.0-LOCAL/kotest-extensions-koin-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-extensions-koin-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-extensions-koin-js/6.0.0-LOCAL/kotest-extensions-koin-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-extensions-koin-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-extensions-koin-js/6.0.0-LOCAL/kotest-extensions-koin-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-extensions-koin-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-extensions-koin-jvm/6.0.0-LOCAL/kotest-extensions-koin-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-extensions-koin-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-extensions-koin-jvm/6.0.0-LOCAL/kotest-extensions-koin-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-extensions-koin-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-extensions-koin-jvm/6.0.0-LOCAL/kotest-extensions-koin-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-extensions-koin-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-extensions-koin-wasm-js/6.0.0-LOCAL/kotest-extensions-koin-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-extensions-koin-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-extensions-koin-wasm-js/6.0.0-LOCAL/kotest-extensions-koin-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-extensions-koin-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-extensions-koin-wasm-js/6.0.0-LOCAL/kotest-extensions-koin-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-extensions-koin-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
