{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-shared/6.0.0-LOCAL-PRE/kotest-assertions-shared-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-assertions-shared",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-jvm-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-assertions-shared-jvm-6.0.0-LOCAL-PRE.jar",
          "size": 683088,
          "sha512": "dd884b4fb6590f6f5e65973900dc46211ede600d63ec5bfe24ec33613f92866ce2518f9c5787ee6b5261e3633a1a80e608afcf6ef62e1006d15ce1784ba50de9",
          "sha256": "3ec7d0618fdd89ff7a17b9101376ce7ffa4b3aa195976a57c587e171c76e1cfb",
          "sha1": "a13a5f6d6bd90562512247a14da79184b5b0404b",
          "md5": "8902f648b7f310be42ce05945d769893"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.java-diff-utils",
          "module": "java-diff-utils",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-jvm-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-assertions-shared-jvm-6.0.0-LOCAL-PRE.jar",
          "size": 683088,
          "sha512": "dd884b4fb6590f6f5e65973900dc46211ede600d63ec5bfe24ec33613f92866ce2518f9c5787ee6b5261e3633a1a80e608afcf6ef62e1006d15ce1784ba50de9",
          "sha256": "3ec7d0618fdd89ff7a17b9101376ce7ffa4b3aa195976a57c587e171c76e1cfb",
          "sha1": "a13a5f6d6bd90562512247a14da79184b5b0404b",
          "md5": "8902f648b7f310be42ce05945d769893"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-assertions-shared-jvm-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-shared-jvm-6.0.0-LOCAL-PRE-sources.jar",
          "size": 84115,
          "sha512": "c56e0df3817eddfbecdaa7e1c2993f5331cbd42ea5ab7eda3a3f5cd7241334c2d48ed68a13443c430216675b4328e60de8af71b9f7050c7a0d759f51e900fe81",
          "sha256": "af0046646c74edd47bab655cd3610e77e0cf15274057292bae7aa0efa228139d",
          "sha1": "04380968c4e4cdd34749a90bb08cf193253cc22a",
          "md5": "f8532540b3faf3f259ad398c281ba85c"
        }
      ]
    }
  ]
}
