{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-konform/6.0.0-LOCAL-PRE/kotest-assertions-konform-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-assertions-konform",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.konform",
          "module": "konform",
          "version": {
            "requires": "0.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-konform-tvosArm64Main-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-assertions-konform-tvosarm64-6.0.0-LOCAL-PRE.klib",
          "size": 7487,
          "sha512": "d46510d282fc8e33754e8d45dbf7671cd1b52591fcff76bb8bca3b69df0d4826a57a04b3fe067a0014ab5f98f80257f9b2cbe94686f3f28bb993e3d53eefe1fa",
          "sha256": "c0dbc723d7d8750d567233071e9f1b17d44cbceb0a4fc24080821d5fcb12f3cc",
          "sha1": "d04094a2c53afdfc272d2546fe76ee1db64089aa",
          "md5": "b15e38ae77677bef7022c9c1fc4ecb3b"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-assertions-konform-tvosarm64-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-konform-tvosarm64-6.0.0-LOCAL-PRE-sources.jar",
          "size": 1533,
          "sha512": "9dad5d7b6c8e098f3760c41c47d91557ed0185eb3bb32a238014c33b5f8c4543bf2147a98d8f7e953daac7112553968cbf2ad5c098380a7b012a3999d1e1555d",
          "sha256": "bd40aba3ef3bd047b26e471f5b0430581b6ee0f926a0682f52c4e6a72859edd9",
          "sha1": "50c182a4d8f0c2b3641def2caa1d4eee44bd7dce",
          "md5": "2bff17d389f5a20f65fc89fe38a4bb60"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.konform",
          "module": "konform",
          "version": {
            "requires": "0.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-konform-tvosarm64-6.0.0-LOCAL-PRE-metadata.jar",
          "url": "kotest-assertions-konform-tvosarm64-6.0.0-LOCAL-PRE-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
