{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "20251017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-20251017.jar",
          "url": "k2-20251017.jar",
          "size": 182532,
          "sha512": "4a0f0fe12b2df84b96fb3f816d2726da9a4729ec683db7e57b9fd079f423b090192ebbf1e085edf0d24f2dd80e22f65d572ce467a1f00a22f6ccbd5d7165c7d1",
          "sha256": "ecef017ddecdec80a47b5413426235f296ecb6001afafeeb908c071565f49843",
          "sha1": "0e8ca9fe6eeda860a14a3ae3b2d48d3528701325",
          "md5": "44b31db66ddc514dd537b2f41bfc5e66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-20251017.jar",
          "url": "k2-20251017.jar",
          "size": 182532,
          "sha512": "4a0f0fe12b2df84b96fb3f816d2726da9a4729ec683db7e57b9fd079f423b090192ebbf1e085edf0d24f2dd80e22f65d572ce467a1f00a22f6ccbd5d7165c7d1",
          "sha256": "ecef017ddecdec80a47b5413426235f296ecb6001afafeeb908c071565f49843",
          "sha1": "0e8ca9fe6eeda860a14a3ae3b2d48d3528701325",
          "md5": "44b31db66ddc514dd537b2f41bfc5e66"
        }
      ]
    }
  ]
}
