{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "20251017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-20251017.jar",
          "url": "k2-20251017.jar",
          "size": 182999,
          "sha512": "463e244d9ea7d41e46d6a9a1c1d26ff6bf1c8968a80f101bba578bb9865a4c3dc90715203726404338b33e488600be21765016d0822dae7d4d0866f8ef6e50d4",
          "sha256": "dcfae8ba44761c71253a4deb6861b2a46511b25a7de90a67f5df7f6b26fed6c6",
          "sha1": "438dd3fa8da361071330e397924910bc320780aa",
          "md5": "9cde786769362eeb440c5f5d6827b5f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-20251017.jar",
          "url": "k2-20251017.jar",
          "size": 182999,
          "sha512": "463e244d9ea7d41e46d6a9a1c1d26ff6bf1c8968a80f101bba578bb9865a4c3dc90715203726404338b33e488600be21765016d0822dae7d4d0866f8ef6e50d4",
          "sha256": "dcfae8ba44761c71253a4deb6861b2a46511b25a7de90a67f5df7f6b26fed6c6",
          "sha1": "438dd3fa8da361071330e397924910bc320780aa",
          "md5": "9cde786769362eeb440c5f5d6827b5f5"
        }
      ]
    }
  ]
}
