{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250727/kmpotest-20250727.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250727",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosX64Main-20250727.klib",
          "url": "kmpotest-watchosx64-20250727.klib",
          "size": 39684,
          "sha512": "69491639c6309a63742e293240ec40a87054afedc033fb927935901d9a2f10b3323479da375bd61b79ddd422335e693dfb1d9a86940d846c0dc56be3c49444f8",
          "sha256": "7246c2661f798496f377e1334f5de63367dda4403df9f051a290380c742a45ed",
          "sha1": "00b3302b2615b6915846dca047466823e3bf6423",
          "md5": "0ab012f51e7dc3d41eec86d94957ac6b"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-watchosx64-20250727-sources.jar",
          "url": "kmpotest-watchosx64-20250727-sources.jar",
          "size": 4318,
          "sha512": "4efedb19eebccb7e9d9f01493ab38db99e42e16c1e96044a6821f0408222f86ed7058e28bdea672894c03a342c9651211f84bf233ef416d097ee98ea0445695b",
          "sha256": "084e4ff16c5d909d7b4a3e5cbe017bc65a0d080b4d218d80051b1e4329b34faf",
          "sha1": "ad0a105a97ab0025310865b5950132dcaf875b17",
          "md5": "9a8fede8f7440d238d894ad1a77ff59f"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosx64-20250727-metadata.jar",
          "url": "kmpotest-watchosx64-20250727-metadata.jar",
          "size": 261,
          "sha512": "2a4260c9d79d8e4dd39e0187f6d219445f0fd34a99c8db3f729b6410d8e2f99cbd8a5b865bfc50e5906c598c80dc2d4478452d652cf36ac50b5cb0d04b405601",
          "sha256": "f769d810faa79bc92a4765ca2a57205014fd9d3c11aec0be9c56e321a896cbfd",
          "sha1": "5bbeffd764749c87767ac7370fa4e51d8c9bad86",
          "md5": "846ae59db10f4db5af7fd832cf01b879"
        }
      ]
    }
  ]
}
