{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.1.20+20250409",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.20-1.0.31"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.20+20250409.jar",
          "url": "k2-2.1.20+20250409.jar",
          "size": 162030,
          "sha512": "97ff5b6389a901088c2f8d27b51f1616c716af89280bf57ea49dabb92e506170db5fdefa084d9e949335bfe2fddf2e7ce5faa2f4532d29b62e9dc1d413bbf40b",
          "sha256": "39cfd5ea49b27f87cfdd152f3684def7c3cc393e3410fa881ca063481db1f67a",
          "sha1": "11d0998b16af43401022a9b8c28ed1f9b03082a6",
          "md5": "6267ca8446d0e2595a811e76e6c4b4c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.20-1.0.31"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.20+20250409.jar",
          "url": "k2-2.1.20+20250409.jar",
          "size": 162030,
          "sha512": "97ff5b6389a901088c2f8d27b51f1616c716af89280bf57ea49dabb92e506170db5fdefa084d9e949335bfe2fddf2e7ce5faa2f4532d29b62e9dc1d413bbf40b",
          "sha256": "39cfd5ea49b27f87cfdd152f3684def7c3cc393e3410fa881ca063481db1f67a",
          "sha1": "11d0998b16af43401022a9b8c28ed1f9b03082a6",
          "md5": "6267ca8446d0e2595a811e76e6c4b4c7"
        }
      ]
    }
  ]
}
