{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-abstractions/0.6.2-K2.2.20-SNAPSHOT/testBalloon-framework-abstractions-0.6.2-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-abstractions",
    "version": "0.6.2-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-abstractions-jvm-0.6.2-K2.2.20-SNAPSHOT.jar",
          "url": "testBalloon-framework-abstractions-jvm-0.6.2-K2.2.20-SNAPSHOT.jar",
          "size": 12451,
          "sha512": "7215fdf68c53196827285efee0c48ef7e976fc3afff15881de21e27f3ec26f2c98fb95b8626a2754e2c52c71bd4fa7ab5290a4f9a1db8fd741512c39efc53018",
          "sha256": "f5674840847af7750676d65f395c002b0dc6bed629f39a373454c12b227090a1",
          "sha1": "4be8d5339bda43e576e1ce334e2e9a3853ce833a",
          "md5": "e0ee3a545c1fc98a105af7f0e7b14979"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-abstractions-jvm-0.6.2-K2.2.20-SNAPSHOT.jar",
          "url": "testBalloon-framework-abstractions-jvm-0.6.2-K2.2.20-SNAPSHOT.jar",
          "size": 12451,
          "sha512": "7215fdf68c53196827285efee0c48ef7e976fc3afff15881de21e27f3ec26f2c98fb95b8626a2754e2c52c71bd4fa7ab5290a4f9a1db8fd741512c39efc53018",
          "sha256": "f5674840847af7750676d65f395c002b0dc6bed629f39a373454c12b227090a1",
          "sha1": "4be8d5339bda43e576e1ce334e2e9a3853ce833a",
          "md5": "e0ee3a545c1fc98a105af7f0e7b14979"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "testBalloon-framework-abstractions-jvm-0.6.2-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-abstractions-jvm-0.6.2-K2.2.20-SNAPSHOT-sources.jar",
          "size": 4485,
          "sha512": "42335bf895d62c60cd54de1e78ac4e40e866f964e1062241f535f8b9c344a387d7e777cad621c5cb80957b8a41b4e34849267af87fe77959f9969bccad2abe9b",
          "sha256": "4382afccd7fa6898884ec9fe2dede57b841a3eecf446fe1c91f0deb4d9f96fb5",
          "sha1": "8ca47ceb50e2e391cdcc35f56020386337353c00",
          "md5": "e72cc5198d7bce9b8acff403bbd70dc3"
        }
      ]
    }
  ]
}
