{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-abstractions/0.6.3-K2.2.20-SNAPSHOT/testBalloon-framework-abstractions-0.6.3-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-abstractions",
    "version": "0.6.3-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-abstractions-androidNativeArm32Main-0.6.3-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-framework-abstractions-androidnativearm32-0.6.3-K2.2.20-SNAPSHOT.klib",
          "size": 14928,
          "sha512": "0e83947c2b4db00d352a80476a34da0e722327002bb0f4c594f7cf1ae2a7d4519ed59ba4d6fe8f17e83528ff8b95ffc51a00b971fb33d2063ca228fa0749d930",
          "sha256": "c6aef3a277efdf17a285a389766e407aa203c6eb7f06f4392a6fd99d9809f2a0",
          "sha1": "4622d8c6475b747770ba38e3b238e4830547e5a2",
          "md5": "0a39df10d99cfefd4427a157681f8146"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-framework-abstractions-androidnativearm32-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-abstractions-androidnativearm32-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "size": 4544,
          "sha512": "770f8a49918581f1ae4ac5ec5a8f843e667b664ec0b2866671e347129d7472132f99969491334f6a6983c8b89728733e64b8a4047cd78702ea7b41010322338c",
          "sha256": "c90328f3b88d6f1934c713b76d42238c5c175aa4a954ea3b979b166497a1c87f",
          "sha1": "b33957d811ade4793d0444ebbcbe3c21b12a487c",
          "md5": "ef9e584c7898ed13e7aaa0ce4fe9bc78"
        }
      ]
    }
  ]
}
