{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.0.20+20241029",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20241029"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.20-1.0.25"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.20+20241029.jar",
          "url": "k2-2.0.20+20241029.jar",
          "size": 10771,
          "sha512": "49fb4c9c5ad5bb2c37473db55a838e692531c5906f832c7de70a7a6ae9581ebf89643baa3ecc4fa5ab0f84491274b258d6c7a0e28588175cf6d074c8726c1db6",
          "sha256": "587351e73b6dcd4b63379cd253361221339b090fc91e197ad9f210d5fff64bb3",
          "sha1": "782525cecf37847a3005b1c09bc7508d981fbb98",
          "md5": "7e985ebbc5867a2080f474cd888c363b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20241029"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.20-1.0.25"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.20+20241029.jar",
          "url": "k2-2.0.20+20241029.jar",
          "size": 10771,
          "sha512": "49fb4c9c5ad5bb2c37473db55a838e692531c5906f832c7de70a7a6ae9581ebf89643baa3ecc4fa5ab0f84491274b258d6c7a0e28588175cf6d074c8726c1db6",
          "sha256": "587351e73b6dcd4b63379cd253361221339b090fc91e197ad9f210d5fff64bb3",
          "sha1": "782525cecf37847a3005b1c09bc7508d981fbb98",
          "md5": "7e985ebbc5867a2080f474cd888c363b"
        }
      ]
    }
  ]
}
