{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.0.20+20241029",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20241029"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.20-1.0.25"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.20+20241029.jar",
          "url": "k2-2.0.20+20241029.jar",
          "size": 10771,
          "sha512": "e5a4609e01710af9f0825d9cc920df909ff08c06bf8029ac85464948171ec5501ae6e941359df78671e4e08771e8a29f4db1a4c5f98fe6ef4cdd733c6662c38b",
          "sha256": "8f857ee984bcd336a68f67b82f6c1147d1a03af16db18255ed234dcc10f1ef09",
          "sha1": "f127428343e6f9a38d95fcc7fa111ab3e5509e53",
          "md5": "4071e23aae610c3336eaf7b5accad5d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20241029"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.20-1.0.25"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.20+20241029.jar",
          "url": "k2-2.0.20+20241029.jar",
          "size": 10771,
          "sha512": "e5a4609e01710af9f0825d9cc920df909ff08c06bf8029ac85464948171ec5501ae6e941359df78671e4e08771e8a29f4db1a4c5f98fe6ef4cdd733c6662c38b",
          "sha256": "8f857ee984bcd336a68f67b82f6c1147d1a03af16db18255ed234dcc10f1ef09",
          "sha1": "f127428343e6f9a38d95fcc7fa111ab3e5509e53",
          "md5": "4071e23aae610c3336eaf7b5accad5d2"
        }
      ]
    }
  ]
}
