{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250713+2/kmpotest-20250713+2.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250713+2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosArm32Main-20250713+2.klib",
          "url": "kmpotest-watchosarm32-20250713+2.klib",
          "size": 38195,
          "sha512": "04bba8c0558b56521291508896fddbc510a6ae39fb1c1a47e8918e8128b2f395faff4262f2f7b160aa2a7ba9f9d6c6519a3e25aab930992fb613ff6017cb5aaf",
          "sha256": "39136dd5baa13c0041039f1876ad0b262e6c045b9c419d7b6be1022eb5233370",
          "sha1": "1ca59f171c8b694a27b94fde5274277e54491e39",
          "md5": "d29c3065e61f099213839168b75c7665"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-watchosarm32-20250713+2-sources.jar",
          "url": "kmpotest-watchosarm32-20250713+2-sources.jar",
          "size": 3886,
          "sha512": "a6ec9538b8a722f2d0f47774cc5b9fbd5fcf02129d22c1e03ba7047061c3ec2e478bdc0168131c655fb536dc69935fd92986e8d615eda57ae4b7081407733cea",
          "sha256": "ee4582eb56c209e7e29e553c9da6bac272ad6891c040c75b2eeab7b4f76d8b1c",
          "sha1": "507431a6228b3a080f4e0799ea8545c4350519d6",
          "md5": "7b3f4dee141de6c719e7f69398f42ef2"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosarm32-20250713+2-metadata.jar",
          "url": "kmpotest-watchosarm32-20250713+2-metadata.jar",
          "size": 261,
          "sha512": "8b08f9f3ae72bc9c1f13422be5e01b9299ea7461d471c407d7bd7a9dbd5e2ecfb1a03a57aa800eed0010b40191fbc18effb1e78b50a268ae4df5965701915700",
          "sha256": "2f9534c3b3dda95b997818d3992c894d9c5ab7f53e083a212422054d1aa97ecc",
          "sha1": "1f0d2cacc5d0f3049281629246e0760a0a1762bd",
          "md5": "c9fde5bb3011684a054cbe439a42ff4f"
        }
      ]
    }
  ]
}
