{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-kotlinx-datetime",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-assertions-kotlinx-datetime-6.0.0-LOCAL.jar",
          "size": 3876,
          "sha512": "41fe6ac4a14691e4084be953ef4197f1d0a30e0f38305915f810ff1ab20f1c2e1eceb09f2e333e715e7ea2aec2d019258ddde6ef18ffe6232d4f84279e293744",
          "sha256": "5693b4f83170030d4b1d3209dfa71b045dae9c97c0805e0f41919537dfc22c34",
          "sha1": "a0d1d02582292949018bd1d425a34ac4a639a9f9",
          "md5": "5de4a1586d826eb080fa5b21a5dd0268"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-kotlinx-datetime-6.0.0-LOCAL-sources.jar",
          "size": 5894,
          "sha512": "3c4de6915eb75ce5c779ab644be50368f319599a32a90792083f2b01924a992cab4482e49850a3a4e2594e20cc5e3743eb31b6d0689d44ea02917db3e172b86a",
          "sha256": "caa4b864e009f1f040b1bbb4a76f0a4ed698f5625cc56a93553bc5730cd63822",
          "sha1": "c35d27219f982a289125ae27434b952f613c7b43",
          "md5": "b5e5cf5e1e0de91477301be67a048bf5"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-js/6.0.0-LOCAL/kotest-assertions-kotlinx-datetime-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-js/6.0.0-LOCAL/kotest-assertions-kotlinx-datetime-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-js/6.0.0-LOCAL/kotest-assertions-kotlinx-datetime-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-jvm/6.0.0-LOCAL/kotest-assertions-kotlinx-datetime-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-jvm/6.0.0-LOCAL/kotest-assertions-kotlinx-datetime-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-jvm/6.0.0-LOCAL/kotest-assertions-kotlinx-datetime-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-wasm-js/6.0.0-LOCAL/kotest-assertions-kotlinx-datetime-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-wasm-js/6.0.0-LOCAL/kotest-assertions-kotlinx-datetime-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-wasm-js/6.0.0-LOCAL/kotest-assertions-kotlinx-datetime-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
