{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "20250712",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-20250712.jar",
          "url": "k2-20250712.jar",
          "size": 179684,
          "sha512": "d54c05325e9bd101d53b8a23664f2703b72b6ec388a6ee12c99cde017901588f908cf98a613e799cc11f869b78ff8116247ec54d2c7c1fbbc96fb67e0e1390a4",
          "sha256": "f956cd1bf30d3ab357baef21ce9313e69124933b512dd86f1059ce64c15fa4e1",
          "sha1": "e5e364eba121d350de3a57cdf391fd23d8966403",
          "md5": "1df97d4f805fb33deab6219eef4ef56c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-20250712.jar",
          "url": "k2-20250712.jar",
          "size": 179684,
          "sha512": "d54c05325e9bd101d53b8a23664f2703b72b6ec388a6ee12c99cde017901588f908cf98a613e799cc11f869b78ff8116247ec54d2c7c1fbbc96fb67e0e1390a4",
          "sha256": "f956cd1bf30d3ab357baef21ce9313e69124933b512dd86f1059ce64c15fa4e1",
          "sha1": "e5e364eba121d350de3a57cdf391fd23d8966403",
          "md5": "1df97d4f805fb33deab6219eef4ef56c"
        }
      ]
    }
  ]
}
