{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-arrow",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-assertions-arrow-6.0.0-LOCAL.jar",
          "size": 6356,
          "sha512": "e535769d85bd144c71a704c35381aa756fd7cd227379ffdd72fa62cfc5eaa632857b978e4dd0c718a51e3af1ba9349d63a3c30aac3e9bc732ac37ec600dde498",
          "sha256": "6b983448c762777984e61181106adb7ede9acb763ddaf40978b7ae5e08e30a64",
          "sha1": "ea469ff61ede6bdfca6145bff40fd407cb40301e",
          "md5": "675d4e000cb8892693b8edbee4ca8d42"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-arrow-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-arrow-6.0.0-LOCAL-sources.jar",
          "size": 5886,
          "sha512": "47f310168f28a95b4891a58033e2d2f033c378cf1df484945f61e2246699c7a28d7f88b3ac756dec60b4eeeed90896f4320c7b8b11887ff1f20e5dbc5eb6f376",
          "sha256": "c79bc48d7979091cdee82371143e7d9d6aee6075362a6cac7928162e416fce25",
          "sha1": "4326d6be6dea17da849809ee10b7d03f17366b05",
          "md5": "1b8fe5fcd85a859b5d4532f68c7d1e4f"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-js/6.0.0-LOCAL/kotest-assertions-arrow-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-js/6.0.0-LOCAL/kotest-assertions-arrow-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-js/6.0.0-LOCAL/kotest-assertions-arrow-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-jvm/6.0.0-LOCAL/kotest-assertions-arrow-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-jvm/6.0.0-LOCAL/kotest-assertions-arrow-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-jvm/6.0.0-LOCAL/kotest-assertions-arrow-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-wasm-js/6.0.0-LOCAL/kotest-assertions-arrow-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-wasm-js/6.0.0-LOCAL/kotest-assertions-arrow-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-wasm-js/6.0.0-LOCAL/kotest-assertions-arrow-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
