{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.0.20+20240904",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240904"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.20-1.0.24"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.1564-20240722.131423-1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.20+20240904.jar",
          "url": "k2-2.0.20+20240904.jar",
          "size": 10759,
          "sha512": "04aa29b8d259d20a1765aafe56044588faebf11744526f7f4598dde3db63ae210b2d5a17fc86266d670775f72e5d6a078f85b2f7e7d9a080cac0b59649182eeb",
          "sha256": "da39a19e8c7920e07467fe829715f798180c7ce057bd53b8399a3df219f91a16",
          "sha1": "56258882a6984d964ca571206d5f5750276ed69f",
          "md5": "71b616ece36af16d621faaa1f22066c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240904"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.20-1.0.24"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.1564-20240722.131423-1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.20+20240904.jar",
          "url": "k2-2.0.20+20240904.jar",
          "size": 10759,
          "sha512": "04aa29b8d259d20a1765aafe56044588faebf11744526f7f4598dde3db63ae210b2d5a17fc86266d670775f72e5d6a078f85b2f7e7d9a080cac0b59649182eeb",
          "sha256": "da39a19e8c7920e07467fe829715f798180c7ce057bd53b8399a3df219f91a16",
          "sha1": "56258882a6984d964ca571206d5f5750276ed69f",
          "md5": "71b616ece36af16d621faaa1f22066c4"
        }
      ]
    }
  ]
}
