{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-iosX64Main-202509019.klib",
          "url": "testballoon-shim-iosx64-202509019.klib",
          "size": 18956,
          "sha512": "a8d1eb59c0ec0b51292eb44987052506dcd1a73b1ee7500e8f296d09550f914fa401b1a5b6be4af7b4f0faaa4b1208efb31fda4d6097aea71f32ee2369d59f98",
          "sha256": "e8f5d1e4c3415c78da5b111f501257bb9f6869de999208b36c0c798f8eb8a92d",
          "sha1": "695724f2f3785bbd4dd523d6301c6e3d90b25841",
          "md5": "f2c31feec2247fde6850ac6e7d5f17e0"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-iosx64-202509019-sources.jar",
          "url": "testballoon-shim-iosx64-202509019-sources.jar",
          "size": 3156,
          "sha512": "5efa5f2c0e892e004320bd520f400834a87560edb1dc27ab732b960d010d66a080be8a56de6292a8a26cdf1911203f2eb291300a7981451ff2e7910650b7475f",
          "sha256": "7f85a8a21176503a2dfca306c8e6ab46ca044158c80486df0bac4eebd90613a7",
          "sha1": "1333170c0d95d4ceb7d4bf69e63d78eca02e55fc",
          "md5": "9eddef7d236c4a9f0bc0da7c7de6c177"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-iosx64-202509019-metadata.jar",
          "url": "testballoon-shim-iosx64-202509019-metadata.jar",
          "size": 261,
          "sha512": "27876c5e3738688750e35bef0e679bd7ec5268a90d9c5015b93c85aba83752b2067b34c3690ef0cfa1731ccc79494419b1644f55389cd0f01f7984444ebdaf04",
          "sha256": "cf1892fd078a057e01ca293a81d1b3461672639de55efa1c985e782cf9b9fc9b",
          "sha1": "ca758db0bc062adc8d5fd7d4d57d11234e2216bc",
          "md5": "2f6f7575675a3c3e7335c4b2526efd51"
        }
      ]
    }
  ]
}
