{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-watchosArm32Main-202509019.klib",
          "url": "testballoon-shim-watchosarm32-202509019.klib",
          "size": 18147,
          "sha512": "1d235f29c276656ab95e60915a87219cd7fc25463e823e47975be72c66fb00b7a627376d8fc77379e98b4954307ee5c2dbcd7c35aabf45f4eb36b71b0c145374",
          "sha256": "228a387a351f9d8c18849dc1477714f639da565fe39a6bd89f97e4d672e571c4",
          "sha1": "9dcbb93fc08fc52294077639813f5ace874d6760",
          "md5": "652338d975d17fcc8ce6a49a0148e611"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-watchosarm32-202509019-sources.jar",
          "url": "testballoon-shim-watchosarm32-202509019-sources.jar",
          "size": 3080,
          "sha512": "4a8720ce0287fae06205ed76e3504b0ef007bd20827944030bb432dbd2ce01e0c78c7c22e73bf2a68a77191ba748263b203bbf2336223edbf6ff9b9de492e32a",
          "sha256": "df9e17ea2ea9828de26b299a1f0d2e33b91092b9e275fc3758f88ebfd05ec199",
          "sha1": "93d3ec78a1a7caaf3035868b653caff0bdff9c8d",
          "md5": "4d2df95f064433b53d7b3e068db7f8c2"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-watchosarm32-202509019-metadata.jar",
          "url": "testballoon-shim-watchosarm32-202509019-metadata.jar",
          "size": 261,
          "sha512": "8150b4e2db93abec8485081aa4794a672ac7a4ea86cf9ae62a594f3b632cbe6c0b0b20d921b4991073296947a2cce16fb9080fb9c7428959dc5534943779f841",
          "sha256": "83af040cafbdfcb87cc57afc41cd4692f7b2ecd5bb2150564168e0e3b9ed9709",
          "sha1": "d6e9b0d48c27f321d27aae74e274edc84b72900f",
          "md5": "dec28724b236c478939bef9b18fe84bf"
        }
      ]
    }
  ]
}
