{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-framework-engine/6.0.0-LOCAL-PRE/kotest-framework-engine-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-framework-engine",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-js-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-framework-engine-js-6.0.0-LOCAL-PRE.klib",
          "size": 911687,
          "sha512": "1ad672bdccc4a2953814586b9e3a63f963ed2d023edca480f15d9bd4ccbe23592873aab31d66715f661d2f6fd2265865e456ee0f971c34ff2a622e1e868a1c88",
          "sha256": "3f302df30b80775ca61e10c1afe44b7394a7c1928adbb0e0fcd9e8af193b5ead",
          "sha1": "0aad5dfa58f1ec1c7f5d95a0d0eedf70cc7da5ac",
          "md5": "bcfaf9a794099bca67afcf7bb5e903ed"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-js-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-framework-engine-js-6.0.0-LOCAL-PRE.klib",
          "size": 911687,
          "sha512": "1ad672bdccc4a2953814586b9e3a63f963ed2d023edca480f15d9bd4ccbe23592873aab31d66715f661d2f6fd2265865e456ee0f971c34ff2a622e1e868a1c88",
          "sha256": "3f302df30b80775ca61e10c1afe44b7394a7c1928adbb0e0fcd9e8af193b5ead",
          "sha1": "0aad5dfa58f1ec1c7f5d95a0d0eedf70cc7da5ac",
          "md5": "bcfaf9a794099bca67afcf7bb5e903ed"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotest-framework-engine-js-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-framework-engine-js-6.0.0-LOCAL-PRE-sources.jar",
          "size": 259760,
          "sha512": "fe39f3115e8549414e8e02a03d2990810c25813350076c4db0c7ca05884a7bf7dca15840d3388e0e19c76a14a35f84648d902b311247bb88e97b950c0cf6a52b",
          "sha256": "81c3cb9af0c037b984685fa330dcf41280e4e7ac024cd99a0b09b395c04cf30b",
          "sha1": "58e9caec0aabe89f94dd3f07158fec7a3c061803",
          "md5": "98af850246754fa0dcec3700e1ec61f8"
        }
      ]
    }
  ]
}
