{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "1.9.23+20240430",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240430"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240430.jar",
          "url": "k2-1.9.23+20240430.jar",
          "size": 10383,
          "sha512": "cc8484f2b8605f41335c19d42df75293deeef8da4460739e7bb3481b3f97c492545c5b7d6b9fffb144ccb697d83dd6c7148dbd98d95a73abf03eb89ae8377648",
          "sha256": "079c3f3ec5d6025b5d3a73239a12a899a56b819929f443930b9553d5eb38d3ec",
          "sha1": "63004700a75e6bc270f1db9d7e7f29b3309d338b",
          "md5": "e14587e7d82e1ab5da46f44590bbd927"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240430"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240430.jar",
          "url": "k2-1.9.23+20240430.jar",
          "size": 10383,
          "sha512": "cc8484f2b8605f41335c19d42df75293deeef8da4460739e7bb3481b3f97c492545c5b7d6b9fffb144ccb697d83dd6c7148dbd98d95a73abf03eb89ae8377648",
          "sha256": "079c3f3ec5d6025b5d3a73239a12a899a56b819929f443930b9553d5eb38d3ec",
          "sha1": "63004700a75e6bc270f1db9d7e7f29b3309d338b",
          "md5": "e14587e7d82e1ab5da46f44590bbd927"
        }
      ]
    }
  ]
}
