{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.0.0+20240604+1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240604+1"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.0-1.0.21"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "strictly": "5.9.0",
            "requires": "5.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.0+20240604+1.jar",
          "url": "k2-2.0.0+20240604+1.jar",
          "size": 10723,
          "sha512": "2e3e55728294bebd35eac13fbd8a0b220ca439353f0d91bfeb2a7142edf835d730982676964ad38100778b1a5cd0089c4901d5ce42a335b39dc8b0d95a17d753",
          "sha256": "d0eb800a82461f5d8e745e66e2343b7efc2300e4dced651a6b022ea57b272bdb",
          "sha1": "8639a053cb626969638259474244fa3450641448",
          "md5": "8a33cdfa6af0a7e086f05263c7c36788"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240604+1"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.0-1.0.21"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "strictly": "5.9.0",
            "requires": "5.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.0+20240604+1.jar",
          "url": "k2-2.0.0+20240604+1.jar",
          "size": 10723,
          "sha512": "2e3e55728294bebd35eac13fbd8a0b220ca439353f0d91bfeb2a7142edf835d730982676964ad38100778b1a5cd0089c4901d5ce42a335b39dc8b0d95a17d753",
          "sha256": "d0eb800a82461f5d8e745e66e2343b7efc2300e4dced651a6b022ea57b272bdb",
          "sha1": "8639a053cb626969638259474244fa3450641448",
          "md5": "8a33cdfa6af0a7e086f05263c7c36788"
        }
      ]
    }
  ]
}
