{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-abstractions/0.6.2-K2.2.20-SNAPSHOT/testBalloon-framework-abstractions-0.6.2-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-abstractions",
    "version": "0.6.2-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-abstractions-linuxX64Main-0.6.2-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-framework-abstractions-linuxx64-0.6.2-K2.2.20-SNAPSHOT.klib",
          "size": 12986,
          "sha512": "9cf8f032839a4a84aa45f4581224e3bc4b18d46db6905846e3c2cb45011b1c8de829ab7f24d33b0fcea44ab0bc08793b86aae8c8f26c9192fd08b2ff12c8880f",
          "sha256": "1eaa6b7de9313a540d70554545adeca782d8f1320d87deda094d741bb5d278ab",
          "sha1": "37f66ce940c13fbeb475186764272703c050a07b",
          "md5": "381f455a08c05a824589d0849cdba60f"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-framework-abstractions-linuxx64-0.6.2-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-abstractions-linuxx64-0.6.2-K2.2.20-SNAPSHOT-sources.jar",
          "size": 4485,
          "sha512": "42335bf895d62c60cd54de1e78ac4e40e866f964e1062241f535f8b9c344a387d7e777cad621c5cb80957b8a41b4e34849267af87fe77959f9969bccad2abe9b",
          "sha256": "4382afccd7fa6898884ec9fe2dede57b841a3eecf446fe1c91f0deb4d9f96fb5",
          "sha1": "8ca47ceb50e2e391cdcc35f56020386337353c00",
          "md5": "e72cc5198d7bce9b8acff403bbd70dc3"
        }
      ]
    }
  ]
}
