{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-core/6.0.0-LOCAL-PRE/kotest-assertions-core-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-assertions-core",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-core-tvosArm64Main-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-assertions-core-tvosarm64-6.0.0-LOCAL-PRE.klib",
          "size": 532081,
          "sha512": "ab17d3dbe9cc18f089a7405c762355e0fdec7286e242d5efb876d6ea4d1ff8d8abae0dcb86fc3fbad43f19c7ec348e20112d0f69a31bd30611963ac7763a3f8e",
          "sha256": "1c9e71b1e5e13d7b7c1554edfa3ee8ada110aa670f06102e097f0561bf725cff",
          "sha1": "41b663e0482d35310296499206dae0c8cbb656e5",
          "md5": "79a51835150b1e8f6ed1b785e7e0708e"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-assertions-core-tvosarm64-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-core-tvosarm64-6.0.0-LOCAL-PRE-sources.jar",
          "size": 109376,
          "sha512": "ad4a435f76f66d310f8b2da246a2dad397b9be01a7cf475635a63e3f026078a7142e7b090e8183b026e48764324048d5d7ba855f5df840ef3b618dd7ce9c3f2d",
          "sha256": "2114d96ccc5ffc3bbc016e4eff19af3788d6748eff9c622607e1c1f6ac34936e",
          "sha1": "5d47dfa994b84d99bb3b1a5341dea75686a197dd",
          "md5": "845cda9bece8a927f987244bbba5d4cb"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-core-tvosarm64-6.0.0-LOCAL-PRE-metadata.jar",
          "url": "kotest-assertions-core-tvosarm64-6.0.0-LOCAL-PRE-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
