{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-json",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-json-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-assertions-json-6.0.0-LOCAL.jar",
          "size": 18205,
          "sha512": "4104a98df06780d956e06dbe3235333a0993360d94b0b01180cf35aed8b45d1b2f7a33b99ef83fb3ad47b3f782502e0ff7c045dc7ce093be9b27c595561a7550",
          "sha256": "0ba53dd7de0c4bb2661cacc6a5eb81d29d1a98e4d1a97b8369315fcd7a210f42",
          "sha1": "2beaaf7acd2fd0b657afb4356f4cfd3092bee627",
          "md5": "9315122a1e1ba48a8e61e813172c645a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-json-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-json-6.0.0-LOCAL-sources.jar",
          "size": 20443,
          "sha512": "eb8ebd7a643ae6f5902e5ad4e6f6b753755cf0478289fbb2f4fd880e3eaa0f58add77816bc2a0ce44de8fa4ff73596fee093e52d3e735244f97f4f41b6c78d63",
          "sha256": "f3d8a5977f9e66616c5fef08b2efb4aa9c41a634c83f279e4128afc5bd88c269",
          "sha1": "2527d6f2c4e9218f0948c09665b16bf2df036100",
          "md5": "ec89d3f3d2f941bb3a864d85b529cb72"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-json-js/6.0.0-LOCAL/kotest-assertions-json-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-json-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-json-js/6.0.0-LOCAL/kotest-assertions-json-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-json-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-json-js/6.0.0-LOCAL/kotest-assertions-json-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-json-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-json-jvm/6.0.0-LOCAL/kotest-assertions-json-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-json-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-json-jvm/6.0.0-LOCAL/kotest-assertions-json-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-json-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-json-jvm/6.0.0-LOCAL/kotest-assertions-json-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-json-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-json-wasm-js/6.0.0-LOCAL/kotest-assertions-json-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-json-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-json-wasm-js/6.0.0-LOCAL/kotest-assertions-json-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-json-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-json-wasm-js/6.0.0-LOCAL/kotest-assertions-json-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-json-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
