{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-watchosX64Main-202509019.klib",
          "url": "testballoon-shim-watchosx64-202509019.klib",
          "size": 18965,
          "sha512": "0093e514cb8f39d0146f3ef226396b722cc1add02b198bdcbddbb94cee3c1c4a2f03061c12d2ae3e5bc2a8c7040f1809c410e450fc55165bf3b762f3b89a9a2c",
          "sha256": "02ae933fce9f163770cbdc047dd81d21db4505413c2473b73bb0ccd2a21ebd98",
          "sha1": "def0ff2702f5bba2c20619dfb19197e91932967f",
          "md5": "711a2d460e296f6ad8876d51756b8c10"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-watchosx64-202509019-sources.jar",
          "url": "testballoon-shim-watchosx64-202509019-sources.jar",
          "size": 3200,
          "sha512": "77ce0b468201ae48d89470afb2ab3f73498f11d9c3b4dc95bafb8c513dc7fe4f616d3e345294c307a07929d64ba55c339a3d10682aba49af3bdc963166160197",
          "sha256": "2eab2efbc828c363ef878c7800581b01fb99a7f10ee9aef91e198715a4c30b53",
          "sha1": "c4c25d32a07802e522a1fcba7278ae0f96fa5edf",
          "md5": "44c84cd398c2d9938df0653b5f8d2c6e"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-watchosx64-202509019-metadata.jar",
          "url": "testballoon-shim-watchosx64-202509019-metadata.jar",
          "size": 261,
          "sha512": "343f6f53dbb4a429361794becbc88a7e5f464715c159edc8b1470172244ee1d003d2d59627f0cdecdb9a9f627e52858c65e42755b4c467ab3a87a39340d0ecd7",
          "sha256": "18ec017043ebe746750fa81844c5f780f41aba9435ec54a16eae0d9c4fcf983a",
          "sha1": "44dbfbba96bd37b0047b1764485791bc94b2fac3",
          "md5": "51ddb1fc86bc1c234e8131e55b1a4a8c"
        }
      ]
    }
  ]
}
