{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-watchosX64Main-202509019.klib",
          "url": "testballoon-shim-watchosx64-202509019.klib",
          "size": 18134,
          "sha512": "785daccb047146f78c329fac2776e1df66910d058dbe203608b50b3981afbdb0698316a6f72ab1a6dc1240968d91e41e37c990cedbc9a5f5e145cd5dbbade146",
          "sha256": "d23cfdc61ebe59544771ab928a2983bf58b0ceecdf2ae46c05bf6dcfb1a4a68f",
          "sha1": "73ff8c565178dccf54d0f72da1e2116a658a37c0",
          "md5": "dc77abc380a83b75ec2b1f755fa32932"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-watchosx64-202509019-sources.jar",
          "url": "testballoon-shim-watchosx64-202509019-sources.jar",
          "size": 3058,
          "sha512": "ef9ffd11854454de397161e08c92d7db6305452189ad12320cbc3776b18344afd2c4e23bbc123b08c5ee4c57d2c9dd637ee683c841d2faa70f5e723ca72a1daa",
          "sha256": "92af351163dfd5f71c13f1bf506d5e82a79de4df1901e887986e29e43d2ad819",
          "sha1": "1db51f300f287759724b07fce0e893a994216267",
          "md5": "0eeafabc1725f66b244bf5b5e9a92184"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-watchosx64-202509019-metadata.jar",
          "url": "testballoon-shim-watchosx64-202509019-metadata.jar",
          "size": 261,
          "sha512": "8150b4e2db93abec8485081aa4794a672ac7a4ea86cf9ae62a594f3b632cbe6c0b0b20d921b4991073296947a2cce16fb9080fb9c7428959dc5534943779f841",
          "sha256": "83af040cafbdfcb87cc57afc41cd4692f7b2ecd5bb2150564168e0e3b9ed9709",
          "sha1": "d6e9b0d48c27f321d27aae74e274edc84b72900f",
          "md5": "dec28724b236c478939bef9b18fe84bf"
        }
      ]
    }
  ]
}
