{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-arrow",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-metadata-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-assertions-arrow-6.0.0-LOCAL-PRE.jar",
          "size": 6654,
          "sha512": "71f97e6bbbf03c0fe30868715f7cc9b2a6d5671d7f8d2dd2f9ab9393eb3547470a4f5b9df410429f2b8a40e3310a5648f666f4ee33f3c8ce904a0cbfa2972f03",
          "sha256": "e8a997dd16138c09276da7d0a17629e06e4962bd50da217160383719ba7c1281",
          "sha1": "8700c680af74486614d9cbd917338daa894a5f85",
          "md5": "c180306c5b412988af962c8d67a636ea"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-arrow-kotlin-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-arrow-6.0.0-LOCAL-PRE-sources.jar",
          "size": 5886,
          "sha512": "47f310168f28a95b4891a58033e2d2f033c378cf1df484945f61e2246699c7a28d7f88b3ac756dec60b4eeeed90896f4320c7b8b11887ff1f20e5dbc5eb6f376",
          "sha256": "c79bc48d7979091cdee82371143e7d9d6aee6075362a6cac7928162e416fce25",
          "sha1": "4326d6be6dea17da849809ee10b7d03f17366b05",
          "md5": "1b8fe5fcd85a859b5d4532f68c7d1e4f"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iosarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-iosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-iosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iosarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-iosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-iosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iosarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-iosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-iosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-iossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-iossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-iossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-iossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-iossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-iossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iosx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-iosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-iosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iosx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-iosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-iosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iosx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-iosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-iosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-js/6.0.0-LOCAL-PRE/kotest-assertions-arrow-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-js/6.0.0-LOCAL-PRE/kotest-assertions-arrow-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-js/6.0.0-LOCAL-PRE/kotest-assertions-arrow-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-jvm/6.0.0-LOCAL-PRE/kotest-assertions-arrow-jvm-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-jvm",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-jvm/6.0.0-LOCAL-PRE/kotest-assertions-arrow-jvm-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-jvm",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-jvm/6.0.0-LOCAL-PRE/kotest-assertions-arrow-jvm-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-jvm",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-linuxarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-linuxarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-linuxarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-linuxarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-linuxarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-linuxarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-linuxx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-linuxx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-linuxx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-linuxx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-linuxx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-linuxx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-macosarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-macosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-macosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-macosarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-macosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-macosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-macosarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-macosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-macosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-macosx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-macosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-macosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-macosx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-macosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-macosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-macosx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-macosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-macosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-mingwx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-mingwx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-mingwx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-mingwx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-mingwx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-mingwx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvosarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-tvosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-tvosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvosarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-tvosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-tvosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvosarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-tvosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-tvosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-tvossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-tvossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-tvossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-tvossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-tvossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-tvossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvosx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-tvosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-tvosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvosx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-tvosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-tvosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvosx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-tvosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-tvosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-wasm-js/6.0.0-LOCAL-PRE/kotest-assertions-arrow-wasm-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-wasm-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-wasm-js/6.0.0-LOCAL-PRE/kotest-assertions-arrow-wasm-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-wasm-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-wasm-js/6.0.0-LOCAL-PRE/kotest-assertions-arrow-wasm-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-wasm-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosarm32/6.0.0-LOCAL-PRE/kotest-assertions-arrow-watchosarm32-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-watchosarm32",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosarm32/6.0.0-LOCAL-PRE/kotest-assertions-arrow-watchosarm32-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-watchosarm32",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosarm32/6.0.0-LOCAL-PRE/kotest-assertions-arrow-watchosarm32-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-watchosarm32",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-watchosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-watchosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-watchosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-watchosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-watchosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-watchosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-watchossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-watchossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-watchossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-watchossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-watchossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-watchossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-watchosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-watchosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-watchosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-watchosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosx64/6.0.0-LOCAL-PRE/kotest-assertions-arrow-watchosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-arrow-watchosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    }
  ]
}
