{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-tvosArm64Main-202509019.klib",
          "url": "testballoon-shim-tvosarm64-202509019.klib",
          "size": 18985,
          "sha512": "02c9e1e456caf2433429d387c228899d35dee3fd9e8708cc980eebc88c011960d4de7f28dfce3372b40bd26d75711a6e5865c9bb694d11cd58085d55bbc1b00c",
          "sha256": "b9754404d197e9b482537ef8a59805f2d69b5a3508af5d2641aa98271ba92f60",
          "sha1": "87456013540f128f0dfb0e9ac3e25f7745bbfcd7",
          "md5": "af972113b17d368b61ebecdc3660b263"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-tvosarm64-202509019-sources.jar",
          "url": "testballoon-shim-tvosarm64-202509019-sources.jar",
          "size": 3189,
          "sha512": "8d08de553ee81439d66496c04fc1d0260823745ce9f6e0b997ebe01bdf2908d0d1c42939b6fb4f5144a3da5f4e7bb8bee92b3352093d160b80815401800221d6",
          "sha256": "387623f4bc75a90d1e3dcfa53a081dff43ba0f1e18c4a858a4d34cc6f21e8dd8",
          "sha1": "242161eda1a5bbee378159a8d874e04c88a3090b",
          "md5": "63bef48ba2eb483ef95cd819f594104f"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-tvosarm64-202509019-metadata.jar",
          "url": "testballoon-shim-tvosarm64-202509019-metadata.jar",
          "size": 261,
          "sha512": "7c0c0e9bfb43d97beea34244fc1e893c67a3271642698bf1a90554f371e255f399aa425edceab35a0f0cefcdf968b27267ceae8cadc78a0c75bc3cdf13134f36",
          "sha256": "8b5ce1903a03897d41c8a1585537d832fe67c7cee830683d3d7a6acaaddb1d60",
          "sha1": "a81d4b6ecd23032950486b23f06b00eab981f286",
          "md5": "7a955626c6b3d425892e08d7801b71e9"
        }
      ]
    }
  ]
}
