{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-property-arrow/6.0.0-LOCAL-PRE/kotest-property-arrow-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-property-arrow",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-optics",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-functions",
          "version": {
            "requires": "2.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-arrow-iosArm64Main-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-property-arrow-iosarm64-6.0.0-LOCAL-PRE.klib",
          "size": 22656,
          "sha512": "aca2ef839740e8767842d9ba319ac12700769c8b8e6f2f5ab6e4c1ca9dbb586c8fed9b14efea003d59c4e566cc43244acd45be2a6edd156beb39cf33f9a8a785",
          "sha256": "015d1925fb3d1751eeffd28de752598d3bb4be701ea9ddbe4396cde032ce24b4",
          "sha1": "b26c4fc42e03d49e48e5f6749adbc409118651a1",
          "md5": "8dfa03bad9adaff0c3dea5b1a250919c"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-property-arrow-iosarm64-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-property-arrow-iosarm64-6.0.0-LOCAL-PRE-sources.jar",
          "size": 5869,
          "sha512": "01f2332f8fea760472bb4d9f2bb4f81ab3f3b16c43dc8072b40dfbe961e012ed461c69ea1937149f93305e5760994280d12babb4370643bfa618bc597f293ad8",
          "sha256": "946d2d763280f02406abe7958afbb3f815ee3b18ee5ec78b5be170aa853a4589",
          "sha1": "c50319cf0fedf615e37bf79dccde5b9ed1c5cdc6",
          "md5": "1f4faa4bf55fcdb1f135020333f718e6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-optics",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-functions",
          "version": {
            "requires": "2.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-arrow-iosarm64-6.0.0-LOCAL-PRE-metadata.jar",
          "url": "kotest-property-arrow-iosarm64-6.0.0-LOCAL-PRE-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
