{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-junitxml/6.0.0-LOCAL/kotest-extensions-junitxml-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-extensions-junitxml",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-junitxml-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-junitxml-jvm-6.0.0-LOCAL.jar",
          "size": 13039,
          "sha512": "deb54cf9345395ca060ba292f7ed912d0a30e07833b3c26e2e0d7cfebfc945272afd199506339ad9a59eed1515520a2959c8662d6ebcd6ea677fdeb9c1edf00e",
          "sha256": "36ac2048a101c889d58eefd6c33394bfd87459cad80f85d7ce68810d92b6db0d",
          "sha1": "c475df7a266ab8046bac113dc18239ef7d7953e2",
          "md5": "61c1461c1bbbe561586bc324899fea2d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-junitxml-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-junitxml-jvm-6.0.0-LOCAL.jar",
          "size": 13039,
          "sha512": "deb54cf9345395ca060ba292f7ed912d0a30e07833b3c26e2e0d7cfebfc945272afd199506339ad9a59eed1515520a2959c8662d6ebcd6ea677fdeb9c1edf00e",
          "sha256": "36ac2048a101c889d58eefd6c33394bfd87459cad80f85d7ce68810d92b6db0d",
          "sha1": "c475df7a266ab8046bac113dc18239ef7d7953e2",
          "md5": "61c1461c1bbbe561586bc324899fea2d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-extensions-junitxml-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-extensions-junitxml-jvm-6.0.0-LOCAL-sources.jar",
          "size": 3459,
          "sha512": "b38c09dd73bd1b7d896a8e1f0abd4295d187efc2af13de3675e0884cbf27a3c2428d7ad971defb256d0ea629f35a70e4564365ec1512ea529140a8662de4111a",
          "sha256": "02c8922f985069565b88714e912152ebe62f52eb38627ed23305af39d92c9660",
          "sha1": "677e6bd4166a4026bc9521571eca277638410907",
          "md5": "471dba22d0fc984354e593f9c85b7283"
        }
      ]
    }
  ]
}
