{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-kotlinx-datetime/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-assertions-kotlinx-datetime",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-wasm-js-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-assertions-kotlinx-datetime-wasm-js-6.0.0-LOCAL-PRE.klib",
          "size": 23751,
          "sha512": "dd75eaa6d611dbd00c2b7d6464bfc283d6476a4958c5753a5dc5608f3fd064a44cf7d04ce5782bf6bf05130ada57d2c65a0537cf4caed41e620102cc0832b1a4",
          "sha256": "bcbf90dce8273777e90ffabf0a71c86b5e14f317ffdd92a5c0bd19d518655555",
          "sha1": "b299b2c041453002433846e07946271cf9fd4ac1",
          "md5": "ddc6558bc5aff5d43fd79d58bc95ee7b"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-wasm-js-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-assertions-kotlinx-datetime-wasm-js-6.0.0-LOCAL-PRE.klib",
          "size": 23751,
          "sha512": "dd75eaa6d611dbd00c2b7d6464bfc283d6476a4958c5753a5dc5608f3fd064a44cf7d04ce5782bf6bf05130ada57d2c65a0537cf4caed41e620102cc0832b1a4",
          "sha256": "bcbf90dce8273777e90ffabf0a71c86b5e14f317ffdd92a5c0bd19d518655555",
          "sha1": "b299b2c041453002433846e07946271cf9fd4ac1",
          "md5": "ddc6558bc5aff5d43fd79d58bc95ee7b"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-wasm-js-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-kotlinx-datetime-wasm-js-6.0.0-LOCAL-PRE-sources.jar",
          "size": 5894,
          "sha512": "3c4de6915eb75ce5c779ab644be50368f319599a32a90792083f2b01924a992cab4482e49850a3a4e2594e20cc5e3743eb31b6d0689d44ea02917db3e172b86a",
          "sha256": "caa4b864e009f1f040b1bbb4a76f0a4ed698f5625cc56a93553bc5730cd63822",
          "sha1": "c35d27219f982a289125ae27434b952f613c7b43",
          "md5": "b5e5cf5e1e0de91477301be67a048bf5"
        }
      ]
    }
  ]
}
