{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-framework-engine/6.0.0-LOCAL/kotest-framework-engine-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-framework-engine",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-debug",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-framework-engine-jvm-6.0.0-LOCAL.jar",
          "size": 1665384,
          "sha512": "a49b9d773bb1c855c9e5b4d4cb06a7bcbeeed6dc703fff033c49d962521244699f4c4fc92b63baf80822196675466b942e515d1d867579d5682958e36bcbebc7",
          "sha256": "95ffbfd5e747c4b883a3a618b1509d1b409e1bdfbd5c846957f96301c08969bc",
          "sha1": "a73f28358a34014ede63bf13d94a37286bf512fa",
          "md5": "e7b966abc01698c290d9cc7726b89d4c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-debug",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-framework-engine-jvm-6.0.0-LOCAL.jar",
          "size": 1665384,
          "sha512": "a49b9d773bb1c855c9e5b4d4cb06a7bcbeeed6dc703fff033c49d962521244699f4c4fc92b63baf80822196675466b942e515d1d867579d5682958e36bcbebc7",
          "sha256": "95ffbfd5e747c4b883a3a618b1509d1b409e1bdfbd5c846957f96301c08969bc",
          "sha1": "a73f28358a34014ede63bf13d94a37286bf512fa",
          "md5": "e7b966abc01698c290d9cc7726b89d4c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-framework-engine-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-framework-engine-jvm-6.0.0-LOCAL-sources.jar",
          "size": 280482,
          "sha512": "b58a10c8e0e67aaf891bc992bf0393ece3cb1f9b44b8134b08a82c4274e57e8ec42e33ca8042c8d1ff6567274d6de3dbdd8cb323cecb96ef81a955205d1fef31",
          "sha256": "86f534cc2ac91cfff7374a36d35b4ac4494ad22a650645c1372358c96c6c835e",
          "sha1": "dc1391d5623da2f0359d6f48beb126c971fc56e1",
          "md5": "1926c0d352a30d2810b45bdf9f252b41"
        }
      ]
    }
  ]
}
