{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-androidNativeX64Main-202509019.klib",
          "url": "testballoon-shim-androidnativex64-202509019.klib",
          "size": 18960,
          "sha512": "0ad18347092cb414d2a2a600a848b1b9aea78fabe472929ebb291a0f23d97cb19857d3baf41968ae86c0c99db1eec352700b031258ef26bb39a75492f8109844",
          "sha256": "8ad7852db83e031f8380ce0caaee698461dc125ce6de81ac88612d1dd182f857",
          "sha1": "456fb1516b2ab76ed33dba309604fcfee8ac2f5f",
          "md5": "56e27ec691cb1c0ac6cf3388842df607"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-androidnativex64-202509019-sources.jar",
          "url": "testballoon-shim-androidnativex64-202509019-sources.jar",
          "size": 3266,
          "sha512": "df493c216d8c7011ec0c9479d04139e576aa25f43f4f156bc352826404bee8613f7ec467ab0e491b1ef17034f8353d27668ee6af1b395ddc9f2b7ff7e1eb1005",
          "sha256": "ef08fc955b2c182f4343e5986fbbce97cbb8ad1905e69ca7c45fc1fbc374ee2b",
          "sha1": "347dab8f62bb5a3c281b9516ba022d21f013661e",
          "md5": "4082fbe1b6d2c4d39836ab5ab539c325"
        }
      ]
    }
  ]
}
