{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "20251114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-20251114.jar",
          "url": "k2-20251114.jar",
          "size": 183360,
          "sha512": "88880c78488e3e52957d5e5f5f7e6214ff50ef10596d62a4ffaca174eeee1e102856e8f0aa920118ca0b972d3ca2a314c751a5d68e7027daa6554053956f8960",
          "sha256": "5d78739557fdec554c25bf1e10ec75b3614c15303de5df7f807d56b3d81803d7",
          "sha1": "03284fdf52eb6d477474e850684aaed72a6acb69",
          "md5": "12b5e923fb41351b90b634ab330a628c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-20251114.jar",
          "url": "k2-20251114.jar",
          "size": 183360,
          "sha512": "88880c78488e3e52957d5e5f5f7e6214ff50ef10596d62a4ffaca174eeee1e102856e8f0aa920118ca0b972d3ca2a314c751a5d68e7027daa6554053956f8960",
          "sha256": "5d78739557fdec554c25bf1e10ec75b3614c15303de5df7f807d56b3d81803d7",
          "sha1": "03284fdf52eb6d477474e850684aaed72a6acb69",
          "md5": "12b5e923fb41351b90b634ab330a628c"
        }
      ]
    }
  ]
}
