{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-mockserver/6.0.0-LOCAL/kotest-extensions-mockserver-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-extensions-mockserver",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.mock-server",
          "module": "mockserver-netty",
          "version": {
            "requires": "5.15.0"
          }
        },
        {
          "group": "org.mock-server",
          "module": "mockserver-client-java",
          "version": {
            "requires": "5.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-mockserver-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-mockserver-jvm-6.0.0-LOCAL.jar",
          "size": 7737,
          "sha512": "89f2a0e37d7166fbee803a9533c605b95690becb387cdd9465bbffa2fdd3fe35ef9abe6f85f93c2d6f7079e402235ce302afda0c3cfce24aefcf4172d9b20ca6",
          "sha256": "1cf640b5d48436a4813dcd38d95f9c2c149a03ca2737e1c365a1c307fbfdc3cb",
          "sha1": "8a456e8e619066da7a9d240cdc8120f06e3a28b9",
          "md5": "9728c5accf014c15e4e1bee05e0bd56d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.mock-server",
          "module": "mockserver-netty",
          "version": {
            "requires": "5.15.0"
          }
        },
        {
          "group": "org.mock-server",
          "module": "mockserver-client-java",
          "version": {
            "requires": "5.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-mockserver-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-mockserver-jvm-6.0.0-LOCAL.jar",
          "size": 7737,
          "sha512": "89f2a0e37d7166fbee803a9533c605b95690becb387cdd9465bbffa2fdd3fe35ef9abe6f85f93c2d6f7079e402235ce302afda0c3cfce24aefcf4172d9b20ca6",
          "sha256": "1cf640b5d48436a4813dcd38d95f9c2c149a03ca2737e1c365a1c307fbfdc3cb",
          "sha1": "8a456e8e619066da7a9d240cdc8120f06e3a28b9",
          "md5": "9728c5accf014c15e4e1bee05e0bd56d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-extensions-mockserver-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-extensions-mockserver-jvm-6.0.0-LOCAL-sources.jar",
          "size": 2312,
          "sha512": "c3cd01ad622286760eaa840401787c297e6b2dfe78539596662a41d33d8b099953164214e9fdaeae2364c54fc37821d58d5c1100d9001f3ba328d0a8e5a5ac22",
          "sha256": "a6dc77f07129c82e713e35621adbaa000255c2de6d8efdc729c5673af2349ac9",
          "sha1": "e875fe6df346ac88bf6fd106ca563499cf22ce41",
          "md5": "668512ab7d910597a9b1ff550888b39d"
        }
      ]
    }
  ]
}
