{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-json/6.0.0-LOCAL-PRE/kotest-assertions-json-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-assertions-json",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-json-mingwX64Main-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-assertions-json-mingwx64-6.0.0-LOCAL-PRE.klib",
          "size": 119977,
          "sha512": "c1cc9652a2f6ab407b688467b56f7d34be45811fc016e2796e000db1cbaea388ad9617e53fe627a773ebccfbd89bcfe85529dea46a66adf8e873b659bf82c122",
          "sha256": "472eed7008a01157fc54f240b26217262cb7f288ca9c8837c05a50f6356d681f",
          "sha1": "fe8f6c811effddb3e26fc125dca18b1f73599c70",
          "md5": "17a806e7ebcf98e82176c9505aa1487e"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-assertions-json-mingwx64-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-json-mingwx64-6.0.0-LOCAL-PRE-sources.jar",
          "size": 20443,
          "sha512": "eb8ebd7a643ae6f5902e5ad4e6f6b753755cf0478289fbb2f4fd880e3eaa0f58add77816bc2a0ce44de8fa4ff73596fee093e52d3e735244f97f4f41b6c78d63",
          "sha256": "f3d8a5977f9e66616c5fef08b2efb4aa9c41a634c83f279e4128afc5bd88c269",
          "sha1": "2527d6f2c4e9218f0948c09665b16bf2df036100",
          "md5": "ec89d3f3d2f941bb3a864d85b529cb72"
        }
      ]
    }
  ]
}
