{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "conventions",
    "version": "1.9.22+20240213",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "conventions-1.9.22+20240213.jar",
          "url": "conventions-1.9.22+20240213.jar",
          "size": 106844,
          "sha512": "6dd2f90501cf09c27a6c4370db28757a83e87a9dd698362dd5a7b67872afa101a6c81fdd78f89c28c7c2d77747b9b1e15a83d1081db0569d5210b09a762fbdc0",
          "sha256": "48d96031b6451bb7b8df110028cc25b7c947c3df9848b6cef91821dbdb90b42b",
          "sha1": "e863a5bd95043130c41741e2bc724fcd86d538f9",
          "md5": "98916eec7106d6ec7c5d88a2b590cd96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "conventions-1.9.22+20240213.jar",
          "url": "conventions-1.9.22+20240213.jar",
          "size": 106844,
          "sha512": "6dd2f90501cf09c27a6c4370db28757a83e87a9dd698362dd5a7b67872afa101a6c81fdd78f89c28c7c2d77747b9b1e15a83d1081db0569d5210b09a762fbdc0",
          "sha256": "48d96031b6451bb7b8df110028cc25b7c947c3df9848b6cef91821dbdb90b42b",
          "sha1": "e863a5bd95043130c41741e2bc724fcd86d538f9",
          "md5": "98916eec7106d6ec7c5d88a2b590cd96"
        }
      ]
    }
  ]
}
