{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/20251017/testballoon-shim-20251017.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-tvosSimulatorArm64Main-20251017.klib",
          "url": "testballoon-shim-tvossimulatorarm64-20251017.klib",
          "size": 19926,
          "sha512": "1b3c0d945df987a6e53d05a1ff3fc8a8ceac2e23012906611f5b9d7b0fcb138fa0a16bab17263a6363507b9e890b596f0c2a593fbd07726ab52d797bce1d0c00",
          "sha256": "f717bb0c49f497c41c5044bbb3f36c4c45cf450826698d454b93f0171d452259",
          "sha1": "ae2accc80001980c06e20d4cd3ae9b367c8490e9",
          "md5": "8a35ba7ca2629b06e084e9bd088b4294"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-tvossimulatorarm64-20251017-sources.jar",
          "url": "testballoon-shim-tvossimulatorarm64-20251017-sources.jar",
          "size": 3450,
          "sha512": "620d0d72342254423420f6f27e19b7b2399db89bdfae12aadc92ca6fa0fea7f93f6c4f7785018d5280a299f440ba6d6d5d38c6609fad9e5cfd7fb3cf5c9ae50f",
          "sha256": "7c7aba2cd9fada91b7004669624b9be6b20af258d2fc15fde854ae781af68aa4",
          "sha1": "ff297d3a3e5a1e2af515e6cf62b84de3f6e3e5f6",
          "md5": "375003aa4a2977fbd0f389e190e23a38"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-tvossimulatorarm64-20251017-metadata.jar",
          "url": "testballoon-shim-tvossimulatorarm64-20251017-metadata.jar",
          "size": 261,
          "sha512": "31bacefa30f4fc1985b37ba141ecdd9ee342ef79bc8e24bc3a4d5550b7f42447fa8acbe49f6193e54d688c8a7c3ef8ccdf9112f58acf7de688a791b3e2f0ce88",
          "sha256": "4e71414c2d14d6203b5e8100879350c94f1e1d04f68cbe1fe9a333d658c9df40",
          "sha1": "1790cb474f2001eec55586ea6651c02a81c920d0",
          "md5": "681328b72f70227f287f57d113ed9047"
        }
      ]
    }
  ]
}
