{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/20251017/testballoon-shim-20251017.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-tvosSimulatorArm64Main-20251017.klib",
          "url": "testballoon-shim-tvossimulatorarm64-20251017.klib",
          "size": 18041,
          "sha512": "fc9208a297dedd621c147865112e5bea443f84249b2b999e11db062507df538ae96d8dc958c1f54bdad35648738096300f7394ff362229363163de661b209b1d",
          "sha256": "e961f958983a34f38a6afa2755e1804bdc67979a4a0d4e3b1b541c639fe05e5f",
          "sha1": "2a0b5c9fa0e30cd21ded193e01d462005a05683c",
          "md5": "2f5f55e089f0c5bbabc2041d362483f8"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-tvossimulatorarm64-20251017-sources.jar",
          "url": "testballoon-shim-tvossimulatorarm64-20251017-sources.jar",
          "size": 3237,
          "sha512": "ac3cb706649a9c484f6d043e8e2233b303d900d498ae6807e39bed7ee8f4041d0e8459e3e9e9e9bd722c5ffde8e14a9b81b76d3e04bc5c161f2cb0f9cd12fb43",
          "sha256": "c25c6b0a2d4a3fb0fa2c8c28daeb57873d5e00c76fcf4ce2f3322af3abb84aa3",
          "sha1": "e9959950bad194c5ef2126465501ed3864cb8820",
          "md5": "2b8224775dca5daddf1f7d6b058faefb"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-tvossimulatorarm64-20251017-metadata.jar",
          "url": "testballoon-shim-tvossimulatorarm64-20251017-metadata.jar",
          "size": 261,
          "sha512": "65e87c2f548a31ec43852fcf26bd7b5290b81ae5521f29eadae3c944032a594f8bd90e3e2f14ce3ba3550c7c827ff3ff4a27bdc9255a05179546225f1e68d858",
          "sha256": "36a27e5c57a451fb7912c0ff8d5ae0bfbffb846f4344e956549c4fe91ccc2bfb",
          "sha1": "7826fa2e2ef61f66d79cb968eb26c0da4183b863",
          "md5": "dde17a0d34282d4f7b93bfccc0864e24"
        }
      ]
    }
  ]
}
