{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251114/testhelper-20251114.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchosArm32Main-20251114.klib",
          "url": "testhelper-watchosarm32-20251114.klib",
          "size": 6100,
          "sha512": "74c18cd708e267fd959d911e019f84cc3621fd48e96b8aad63d0b7dfd5c909fbe689500c10d98c9f1a263a459dbd6ab260a5984524e361de56c4eb2b3068c878",
          "sha256": "7083390ba1b4959f8de8f54ac819cc4f3bd2dba71cc29aa963bb0421337f1e8a",
          "sha1": "aebebd26a549385f338035f5a4f8e86c46162c03",
          "md5": "9b561fc440a31ceaecdc533a9219f783"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-watchosarm32-20251114-sources.jar",
          "url": "testhelper-watchosarm32-20251114-sources.jar",
          "size": 1926,
          "sha512": "e34bc7de3e320e5e4e5bc9111d9a6f2ccd8c66f9d281eb2119e99c35982a4cbcb7d2cdd441a34453df3fe63749780be1465bee911960f522c54176207af7b986",
          "sha256": "d9535b9926c20a6eb3925f446d3b3cfb1d3f6da87ece3ece7681e3d231dc5ff1",
          "sha1": "62d06333a78a302d4f891257d94da002c12efce8",
          "md5": "972a4ebd30ba96fe682279b20456a31e"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchosarm32-20251114-metadata.jar",
          "url": "testhelper-watchosarm32-20251114-metadata.jar",
          "size": 261,
          "sha512": "a6d3b112dbe7c3c0e4d3a191fbcee6000d0c14dba9fdd1823f414d421bd72641f1d076f96d4938bd7058c81caafc46ab5498033c52c3a2f9978d7ab7a24a3e6f",
          "sha256": "5d4e630e8ad270150dda33fbff0ea9cdfdb4798e29c6e47e3a2aada790962760",
          "sha1": "89904b12b1c600d46eb4f1b98717324ce6d82d38",
          "md5": "8e80af8e9953bd0e38e0462ebdf3d3da"
        }
      ]
    }
  ]
}
