{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "1.9.23+20240409+1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240409+1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.19"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240409+1.jar",
          "url": "k2-1.9.23+20240409+1.jar",
          "size": 10384,
          "sha512": "076f025edb7a98a172484e88ec291037000bbb1c2197c15a179a83e33a94e346a02df9862d971b9665d3e395cfa0b34422873c051e5986c8d49cb69e0b9b7f68",
          "sha256": "041e1370a60f19b0b5244f21cc66a80c8afd866542d892f5a536a27af2ad39d1",
          "sha1": "c34e4a8c582bb4500bbde331c0cca8348a14d0be",
          "md5": "4d872e6df591cc20b0cc53ee96b6089a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240409+1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.19"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240409+1.jar",
          "url": "k2-1.9.23+20240409+1.jar",
          "size": 10384,
          "sha512": "076f025edb7a98a172484e88ec291037000bbb1c2197c15a179a83e33a94e346a02df9862d971b9665d3e395cfa0b34422873c051e5986c8d49cb69e0b9b7f68",
          "sha256": "041e1370a60f19b0b5244f21cc66a80c8afd866542d892f5a536a27af2ad39d1",
          "sha1": "c34e4a8c582bb4500bbde331c0cca8348a14d0be",
          "md5": "4d872e6df591cc20b0cc53ee96b6089a"
        }
      ]
    }
  ]
}
