{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.1.20+20250708-pupilid",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.20-1.0.31"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.20+20250708-pupilid.jar",
          "url": "k2-2.1.20+20250708-pupilid.jar",
          "size": 158383,
          "sha512": "e6ee14a5065d4fb283d5b9f96475c871e901f463a37d6c491f67c93ea8c3c4e003f2110282225ba1e18a30e84e2752e619f8a954e01f950df03501ecaea79d91",
          "sha256": "cdb2d0653e3a5c5145dfba16e86f117340084d1fe0bd9afc3b6f5093cdcc5e70",
          "sha1": "4a08083c5beec6c9a14373a9823317d6d08e35c0",
          "md5": "a67a5c67e1e06fed8c8b088bbaf485dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.20-1.0.31"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.20+20250708-pupilid.jar",
          "url": "k2-2.1.20+20250708-pupilid.jar",
          "size": 158383,
          "sha512": "e6ee14a5065d4fb283d5b9f96475c871e901f463a37d6c491f67c93ea8c3c4e003f2110282225ba1e18a30e84e2752e619f8a954e01f950df03501ecaea79d91",
          "sha256": "cdb2d0653e3a5c5145dfba16e86f117340084d1fe0bd9afc3b6f5093cdcc5e70",
          "sha1": "4a08083c5beec6c9a14373a9823317d6d08e35c0",
          "md5": "a67a5c67e1e06fed8c8b088bbaf485dc"
        }
      ]
    }
  ]
}
