{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-core/6.0.0-LOCAL-PRE/kotest-assertions-core-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-assertions-core",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-core-mingwX64Main-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-assertions-core-mingwx64-6.0.0-LOCAL-PRE.klib",
          "size": 532076,
          "sha512": "23e3a7caca5a0582a3a353a41de4a6dd4dc378e7387c20ebc9256f59bdfa070ad7ec18e844369e850da9b2cf021d7087ec167ef46ae4a37578b9f98a07e397c0",
          "sha256": "dce7e8f55d2ba135b785248ce1eaf46e016c512b505f424bdf088bff1f78628c",
          "sha1": "78f2dfcb57ecb30e0008a3f7cf7c99f6dca58ec4",
          "md5": "f2bee8117b9c718449c6a6380bae4945"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-assertions-core-mingwx64-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-core-mingwx64-6.0.0-LOCAL-PRE-sources.jar",
          "size": 109376,
          "sha512": "ad4a435f76f66d310f8b2da246a2dad397b9be01a7cf475635a63e3f026078a7142e7b090e8183b026e48764324048d5d7ba855f5df840ef3b618dd7ce9c3f2d",
          "sha256": "2114d96ccc5ffc3bbc016e4eff19af3788d6748eff9c622607e1c1f6ac34936e",
          "sha1": "5d47dfa994b84d99bb3b1a5341dea75686a197dd",
          "md5": "845cda9bece8a927f987244bbba5d4cb"
        }
      ]
    }
  ]
}
