{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.1.20-Beta1+20250107",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20250107"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20-Beta1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.20-Beta1-1.0.29"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.20-Beta1+20250107.jar",
          "url": "k2-2.1.20-Beta1+20250107.jar",
          "size": 10775,
          "sha512": "82e6ecbe6f579913242102d86f2d965430a00ffbe947864c0408fa9a92e1b8d46ed4faf54d1716d1d53ea1cf4ae370bb0c641996f18b11336132a5efd7f0fd7a",
          "sha256": "613aa2cc3c65809ec205ae34632d2dbb5b9ad08c09b54e2600083a71deeaab6e",
          "sha1": "75c432a445cb51acb3fec691ed910f1945a1eab8",
          "md5": "8fe96db33c985bd163a9f36a396bff97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20250107"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20-Beta1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.20-Beta1-1.0.29"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.20-Beta1+20250107.jar",
          "url": "k2-2.1.20-Beta1+20250107.jar",
          "size": 10775,
          "sha512": "82e6ecbe6f579913242102d86f2d965430a00ffbe947864c0408fa9a92e1b8d46ed4faf54d1716d1d53ea1cf4ae370bb0c641996f18b11336132a5efd7f0fd7a",
          "sha256": "613aa2cc3c65809ec205ae34632d2dbb5b9ad08c09b54e2600083a71deeaab6e",
          "sha1": "75c432a445cb51acb3fec691ed910f1945a1eab8",
          "md5": "8fe96db33c985bd163a9f36a396bff97"
        }
      ]
    }
  ]
}
