{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "1.9.22+202400301",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+202400301"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.22+202400301.jar",
          "url": "k2-1.9.22+202400301.jar",
          "size": 10204,
          "sha512": "f4dc3e05ec103cbb634b2a5810228c7b5ae8617886e6b1ffb76914e7600d343b1c99637ff6585bd86e3e182689ecdd150a55d4b75c5af151168ec0110947cf99",
          "sha256": "578df44a21eaad5cb9b900e7cf1b6548bfa79743c91ec3f859e5bc7262484df2",
          "sha1": "c8aec3bb5b2ac1a3b01c0f4291729b7b32b6d2b9",
          "md5": "c8b13cf18af8282f93c8ccfe252da841"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+202400301"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.22+202400301.jar",
          "url": "k2-1.9.22+202400301.jar",
          "size": 10204,
          "sha512": "f4dc3e05ec103cbb634b2a5810228c7b5ae8617886e6b1ffb76914e7600d343b1c99637ff6585bd86e3e182689ecdd150a55d4b75c5af151168ec0110947cf99",
          "sha256": "578df44a21eaad5cb9b900e7cf1b6548bfa79743c91ec3f859e5bc7262484df2",
          "sha1": "c8aec3bb5b2ac1a3b01c0f4291729b7b32b6d2b9",
          "md5": "c8b13cf18af8282f93c8ccfe252da841"
        }
      ]
    }
  ]
}
