{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-watchosDeviceArm64Main-202509019.klib",
          "url": "testballoon-shim-watchosdevicearm64-202509019.klib",
          "size": 18231,
          "sha512": "27d16423c8f5b19c9629159ba5f4b5495dad06de4f8272767937ab06392912c1ade5d373690fed22818e4534e7ca9ae120b74e8c05a9813915d69f4aa742149c",
          "sha256": "70bf6da140576227250a75b4b84450e2225972ac2bc41e1f20451bd4bc812f76",
          "sha1": "36858c054578051d746654b41477187895ec128f",
          "md5": "641a0909473bc5c13245cb548ffa1413"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-watchosdevicearm64-202509019-sources.jar",
          "url": "testballoon-shim-watchosdevicearm64-202509019-sources.jar",
          "size": 3184,
          "sha512": "fde40ca4dd4e310898aa7181e412197bd23c531ad94cfda9811a7c8c4e480c28e2978404ffccecb77e69c3ade1527e07515a981407f2258aff0dc3bb213449ff",
          "sha256": "3078fbf11b8b4fc07f71dae4915ad849023b9ad52e4ef63366ae71dede2f630f",
          "sha1": "8dfd28620ce80443c51b3d193909746b00325655",
          "md5": "172e66a0426f4e73793f2878025b4218"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-watchosdevicearm64-202509019-metadata.jar",
          "url": "testballoon-shim-watchosdevicearm64-202509019-metadata.jar",
          "size": 261,
          "sha512": "8150b4e2db93abec8485081aa4794a672ac7a4ea86cf9ae62a594f3b632cbe6c0b0b20d921b4991073296947a2cce16fb9080fb9c7428959dc5534943779f841",
          "sha256": "83af040cafbdfcb87cc57afc41cd4692f7b2ecd5bb2150564168e0e3b9ed9709",
          "sha1": "d6e9b0d48c27f321d27aae74e274edc84b72900f",
          "md5": "dec28724b236c478939bef9b18fe84bf"
        }
      ]
    }
  ]
}
