{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250715-SNAPSHOT/kmpotest-20250715-SNAPSHOT.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250715-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-linuxX64Main-20250715-SNAPSHOT.klib",
          "url": "kmpotest-linuxx64-20250715-SNAPSHOT.klib",
          "size": 38204,
          "sha512": "d82f89135e1aec1756337124aaff8eec4ff4f659c54ab401f0516b82fed6f4fe169150b0efb635624bb461f20608c9a9fe8c124ee200e15150385f6da2ad0bcc",
          "sha256": "0047733583cb533184a4add0c79ad878af2e9e6b7a2fdbc2b03d18b9f7187d4e",
          "sha1": "61c199ed8bed396efaa5c324493a5819286d0464",
          "md5": "e7cfa18d39d87e2dc15f3828e4e6d9d3"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-linuxx64-20250715-SNAPSHOT-sources.jar",
          "url": "kmpotest-linuxx64-20250715-SNAPSHOT-sources.jar",
          "size": 4458,
          "sha512": "e807216c0cd3db7824e9e15f38b2e8f745e34aca63b5518ba666f52bc1860ac84b248b1b071237122aec87c917b5d479c490cb7f30c5bb4d236ddac73572faaf",
          "sha256": "2ce30bafff1de9527caa3386ab1bef9727efceb9fb4f8c775ce6b3253d5e5bcc",
          "sha1": "7707fc905dd78100966996f86bf41395e2e4d3c4",
          "md5": "68d177fdc72b81d60a0433be4020a8ea"
        }
      ]
    }
  ]
}
