{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-property-lifecycle",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-lifecycle-metadata-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-property-lifecycle-6.0.0-LOCAL-PRE.jar",
          "size": 2514,
          "sha512": "f84ec692c609c2e9f713151e5229aa2dd15b306d3cd3071f12c36fc75ea183dbce53dbed981ee59d7ea900814f1ab5421653582a1dd83984be88d1f6e4eb380a",
          "sha256": "74f3ef412a6f247b1e4b7da687dcf95ef7cd81d13fd259fb9ea558d399fd4926",
          "sha1": "eb52bde310dae586e3b82538a8c7c7fd35002df0",
          "md5": "43ae83ca23b0e4d5b3084d1cd5385113"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-property-lifecycle-kotlin-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-property-lifecycle-6.0.0-LOCAL-PRE-sources.jar",
          "size": 1468,
          "sha512": "5fd4c3a0d24c6ab27b1f5c7b919250e5298e46898761cc580f968acd43750ea4fcdc8b52dd27fa6a538213d284a20817bef28033a3803053952e6b4cf976ae8a",
          "sha256": "b2b9bb642a3d1afd9ee3eb87edd7f05fccdf517920ff842c2b7bb933e1d6553f",
          "sha1": "324e1892502cbc265df9584ef96a809645e66c78",
          "md5": "cea07e4c53ee2523bdead40b73eeefb9"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-property-lifecycle-js/6.0.0-LOCAL-PRE/kotest-property-lifecycle-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-property-lifecycle-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-property-lifecycle-js/6.0.0-LOCAL-PRE/kotest-property-lifecycle-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-property-lifecycle-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-property-lifecycle-js/6.0.0-LOCAL-PRE/kotest-property-lifecycle-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-property-lifecycle-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-property-lifecycle-jvm/6.0.0-LOCAL-PRE/kotest-property-lifecycle-jvm-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-property-lifecycle-jvm",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-property-lifecycle-jvm/6.0.0-LOCAL-PRE/kotest-property-lifecycle-jvm-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-property-lifecycle-jvm",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-property-lifecycle-jvm/6.0.0-LOCAL-PRE/kotest-property-lifecycle-jvm-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-property-lifecycle-jvm",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-property-lifecycle-wasm-js/6.0.0-LOCAL-PRE/kotest-property-lifecycle-wasm-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-property-lifecycle-wasm-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-property-lifecycle-wasm-js/6.0.0-LOCAL-PRE/kotest-property-lifecycle-wasm-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-property-lifecycle-wasm-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-property-lifecycle-wasm-js/6.0.0-LOCAL-PRE/kotest-property-lifecycle-wasm-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-property-lifecycle-wasm-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    }
  ]
}
