{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "legacy",
    "version": "1.9.10+20241024",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.10-1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-1.9.10+20241024.jar",
          "url": "legacy-1.9.10+20241024.jar",
          "size": 149999,
          "sha512": "0d99de4487ced1984c87d2dabbdee7670f2cb9cda422fea14e396c3bf72387057486260eea494a081a5ab410b82d5255a67a0aba016edcb9ae0eb60e276fd608",
          "sha256": "ddb5e9c68fb30046f799981925ed3461b2df4dbce69a3a81a2a84fc03c17c9a3",
          "sha1": "6652c500ea2305f01e0041b48fd2f755438c4853",
          "md5": "24442a5bb0fa2f5b062841b7983b6aa6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.10-1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-1.9.10+20241024.jar",
          "url": "legacy-1.9.10+20241024.jar",
          "size": 149999,
          "sha512": "0d99de4487ced1984c87d2dabbdee7670f2cb9cda422fea14e396c3bf72387057486260eea494a081a5ab410b82d5255a67a0aba016edcb9ae0eb60e276fd608",
          "sha256": "ddb5e9c68fb30046f799981925ed3461b2df4dbce69a3a81a2a84fc03c17c9a3",
          "sha1": "6652c500ea2305f01e0041b48fd2f755438c4853",
          "md5": "24442a5bb0fa2f5b062841b7983b6aa6"
        }
      ]
    }
  ]
}
