{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-property/6.0.0-LOCAL-PRE/kotest-property-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-property",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-mingwX64Main-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-property-mingwx64-6.0.0-LOCAL-PRE.klib",
          "size": 783050,
          "sha512": "de50cb07966d995b382a909a9a737f8747bfbe8f5618c075ff6ce3bb9f6b9be143c358af6401b8457fe9ba71d4b45d8200d877307534dafec3d420446c9d85fe",
          "sha256": "8febf900b7c08e11ab2ef1d5a0ff0d700790f1e9594caef2771b08ef60e36d4a",
          "sha1": "698e14f9b085c7977bdffb67de01c100cae0452c",
          "md5": "f948a66b6c4a879ce46b26789041b69a"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-property-mingwx64-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-property-mingwx64-6.0.0-LOCAL-PRE-sources.jar",
          "size": 104410,
          "sha512": "e8bb801cddb72452ed072e8b781c464e067cf6e0180468b15e6b4fdd34fb83564c69fc32e98ea547353487237299e094ff14e58207673f2c894b0875ce4cb20e",
          "sha256": "fc649612ac43a12d2f5131f36adc73328b4747e5e658e7d224c5783ee6f40ee2",
          "sha1": "6b9f3cc7d279ebb9bb635410452140525df6eed4",
          "md5": "9e2593e855c104fa9eb0fa0fc29ad305"
        }
      ]
    }
  ]
}
