{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-blocking-detection/0.6.2-K2.2.20-SNAPSHOT/testBalloon-integration-blocking-detection-0.6.2-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-blocking-detection",
    "version": "0.6.2-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection.aar",
          "url": "testBalloon-integration-blocking-detection-android-0.6.2-K2.2.20-SNAPSHOT.aar",
          "size": 3017,
          "sha512": "79de541e9287467e9eff32093cd6ba7ac497e82a29adb8dc0cdcac14b7406965400bbf3770bd6c5c861664a0e1761cd00c6536346758863ec069be1cbe969f96",
          "sha256": "54e5ffa2e36b4357ea8d3e0f8ad51f5dca94603a2ab3a8ed971c1ec046712060",
          "sha1": "cfc679c4f7aeac1a8bf374a38ab0efbc9ba415da",
          "md5": "8700048cfecdcc20a77df265b835ffdc"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection.aar",
          "url": "testBalloon-integration-blocking-detection-android-0.6.2-K2.2.20-SNAPSHOT.aar",
          "size": 3017,
          "sha512": "79de541e9287467e9eff32093cd6ba7ac497e82a29adb8dc0cdcac14b7406965400bbf3770bd6c5c861664a0e1761cd00c6536346758863ec069be1cbe969f96",
          "sha256": "54e5ffa2e36b4357ea8d3e0f8ad51f5dca94603a2ab3a8ed971c1ec046712060",
          "sha1": "cfc679c4f7aeac1a8bf374a38ab0efbc9ba415da",
          "md5": "8700048cfecdcc20a77df265b835ffdc"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-android-0.6.2-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-blocking-detection-android-0.6.2-K2.2.20-SNAPSHOT-sources.jar",
          "size": 2961,
          "sha512": "8ba37efddc662492f16105e06002aea68d5bd64b41a1c218a2f79248f0b55417c095a76f8592dff187df82313c83381313bb916697cbadb1c8ec48c7e4907141",
          "sha256": "b20453dbef2a86f3a9a8fad7b35ca41686e54996c729a190296090bad4fd8798",
          "sha1": "be048349dcadd0e44db91aa70703b5c4e34a7de5",
          "md5": "34e7dad7a567ffceecf0dd29f68dd357"
        }
      ]
    }
  ]
}
