{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-arrow-fx-coroutines/6.0.0-LOCAL/kotest-assertions-arrow-fx-coroutines-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-assertions-arrow-fx-coroutines",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-arrow",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-fx-coroutines",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-fx-coroutines-macosArm64Main-6.0.0-LOCAL.klib",
          "url": "kotest-assertions-arrow-fx-coroutines-macosarm64-6.0.0-LOCAL.klib",
          "size": 24174,
          "sha512": "f8a463122a6f0dd91a80b85dfbe1ac5d130b457c870fab632710cae7947ef960f01a47f740340e09fc4d3192a04dd8da49d0c33156971556a7c23e903cfa3e0e",
          "sha256": "b1bc47a0cb0eac8deae8ba454e1c81b91d50f937bc4eddac0a8fb8c224cf1175",
          "sha1": "550eb56ae0eb3c25d3cfcebe928b9ae732c2129a",
          "md5": "1d7cdbfe0bce1d71b15a7412b7ef6d93"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-assertions-arrow-fx-coroutines-macosarm64-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-arrow-fx-coroutines-macosarm64-6.0.0-LOCAL-sources.jar",
          "size": 5182,
          "sha512": "97b35792098da52be5ab07d619a60f04798ededce71a7e0cd892310abcbdd4c028eac84dacf1f9dfed4861d10c8282a83152f62f28e551fc2d2a8e1a80973548",
          "sha256": "6929929f1d5c6a03094dc1e1e38a8f5be54df790235e94a5d9a9cd55ed4142ae",
          "sha1": "233e5f770f464a77f489a78280a762a4b20bc822",
          "md5": "d794af342155e408c597894a98027777"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-arrow",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-fx-coroutines",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-fx-coroutines-macosarm64-6.0.0-LOCAL-metadata.jar",
          "url": "kotest-assertions-arrow-fx-coroutines-macosarm64-6.0.0-LOCAL-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
