{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-202509019.jar",
          "url": "k2-202509019.jar",
          "size": 171988,
          "sha512": "75ef70df21ad1b068fabddeb1c780c6c6c18dfd89dc459e7bb5f18d065b87d76919ea4e88638b38b5734b65dd169ed742ebe4aaeb35cf7ad06c90f5c90c0eca2",
          "sha256": "f7626ada87ce20a3e514394a9d2f06cb265dc8766f36a4eead59016e06500b5e",
          "sha1": "3ca679be386313bce53f8ac0d7a3aa237db6c64d",
          "md5": "42c19ceba36554789caa8a06e87276cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-202509019.jar",
          "url": "k2-202509019.jar",
          "size": 171988,
          "sha512": "75ef70df21ad1b068fabddeb1c780c6c6c18dfd89dc459e7bb5f18d065b87d76919ea4e88638b38b5734b65dd169ed742ebe4aaeb35cf7ad06c90f5c90c0eca2",
          "sha256": "f7626ada87ce20a3e514394a9d2f06cb265dc8766f36a4eead59016e06500b5e",
          "sha1": "3ca679be386313bce53f8ac0d7a3aa237db6c64d",
          "md5": "42c19ceba36554789caa8a06e87276cf"
        }
      ]
    }
  ]
}
