{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-202509019.jar",
          "url": "k2-202509019.jar",
          "size": 173301,
          "sha512": "4b7e86febabb6262e114c60778f950421111d6be8ea47ca17f76583eaae01ff12bdb9cdd7e6fca7d133e419449eaa380d8814879e8aae0d3cbb02330226d7197",
          "sha256": "2bc62d4984d1a6580190e7f1dc282bda74c229180ba64b49248aa914111b088d",
          "sha1": "f13e9dfd3eed4e3dee797af6df49b34b9686c0d5",
          "md5": "7a7cdad1b2dff832b4ef646182c2049c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-202509019.jar",
          "url": "k2-202509019.jar",
          "size": 173301,
          "sha512": "4b7e86febabb6262e114c60778f950421111d6be8ea47ca17f76583eaae01ff12bdb9cdd7e6fca7d133e419449eaa380d8814879e8aae0d3cbb02330226d7197",
          "sha256": "2bc62d4984d1a6580190e7f1dc282bda74c229180ba64b49248aa914111b088d",
          "sha1": "f13e9dfd3eed4e3dee797af6df49b34b9686c0d5",
          "md5": "7a7cdad1b2dff832b4ef646182c2049c"
        }
      ]
    }
  ]
}
