{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "conventions",
    "version": "1.9.20+20231114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.6"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.20-1.0.14"
          }
        }
      ],
      "files": [
        {
          "name": "conventions-1.9.20+20231114.jar",
          "url": "conventions-1.9.20+20231114.jar",
          "size": 106816,
          "sha512": "6ad55c591bba24477aad1b3332751e0c0e0a0238fdd0a3bc9bb307125e57f3f913e79442b225295747181dc72f6bc79a645f91622447c3c796b8014c1a774cbe",
          "sha256": "20cc200d053b160159c8dc6774eaa0c8ef804d76b34101290668384689a5ace3",
          "sha1": "53a880b301c48dfc8d4049b1f15661cc3fdb096d",
          "md5": "51b9e454662389b7e34e2e623cc7d448"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.6"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.20-1.0.14"
          }
        }
      ],
      "files": [
        {
          "name": "conventions-1.9.20+20231114.jar",
          "url": "conventions-1.9.20+20231114.jar",
          "size": 106816,
          "sha512": "6ad55c591bba24477aad1b3332751e0c0e0a0238fdd0a3bc9bb307125e57f3f913e79442b225295747181dc72f6bc79a645f91622447c3c796b8014c1a774cbe",
          "sha256": "20cc200d053b160159c8dc6774eaa0c8ef804d76b34101290668384689a5ace3",
          "sha1": "53a880b301c48dfc8d4049b1f15661cc3fdb096d",
          "md5": "51b9e454662389b7e34e2e623cc7d448"
        }
      ]
    }
  ]
}
