{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/20251017/testballoon-shim-20251017.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-macosArm64Main-20251017.klib",
          "url": "testballoon-shim-macosarm64-20251017.klib",
          "size": 17968,
          "sha512": "b5b902aadfec0f0b80cd3d7f5eec8c9316c49be631181c32f218d5fa6bdb92b9e7ff140d3e685349ed153cb86b950bddcc8a10ca95cec1bbbbd21da956964649",
          "sha256": "999bcf53c185aa0e1a2f856777b8a41f6368029826380fc68feaf7e982a8e4c4",
          "sha1": "10e2d74697143d692a6ad0e6f89421a772e8dfeb",
          "md5": "7b9ca30c6691e2fa78d512ec361cf62c"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-macosarm64-20251017-sources.jar",
          "url": "testballoon-shim-macosarm64-20251017-sources.jar",
          "size": 3152,
          "sha512": "3254ebf74e28606f6a7f9d9a7666e26a1617d3b61399d24a233abfb938f051fa97afaebfdccf7a92ad0a53497da5c6d1d7e5e2544fb964e47b7cc15fd900d0ce",
          "sha256": "41cb468e56e9365112ad0b74f119607cce21e5ddf4d1fc2849ad6094539bc652",
          "sha1": "d0f03017fe786bc6e6e987f5c0b7b1cfb0bcb357",
          "md5": "83bc8d030f1b6543771c26d98fbafcc0"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-macosarm64-20251017-metadata.jar",
          "url": "testballoon-shim-macosarm64-20251017-metadata.jar",
          "size": 261,
          "sha512": "65e87c2f548a31ec43852fcf26bd7b5290b81ae5521f29eadae3c944032a594f8bd90e3e2f14ce3ba3550c7c827ff3ff4a27bdc9255a05179546225f1e68d858",
          "sha256": "36a27e5c57a451fb7912c0ff8d5ae0bfbffb846f4344e956549c4fe91ccc2bfb",
          "sha1": "7826fa2e2ef61f66d79cb968eb26c0da4183b863",
          "md5": "dde17a0d34282d4f7b93bfccc0864e24"
        }
      ]
    }
  ]
}
