{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250715-SNAPSHOT/kmpotest-20250715-SNAPSHOT.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250715-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-macosArm64Main-20250715-SNAPSHOT.klib",
          "url": "kmpotest-macosarm64-20250715-SNAPSHOT.klib",
          "size": 38193,
          "sha512": "a4d3e9f36857be981662fefd2bda46d25c0aeb54094684544f0c219f65029909a18befb6920f8d89fd8cf3f597c3b1f42e7b98cad61bb0c5a9017328fc51d3d8",
          "sha256": "ff3c1ffdb98828b3faeb5aac410755a2cbbcc573a2b2e43a821a694e3925cb5f",
          "sha1": "606842543d1b864ed6849e5922cda86525d0d827",
          "md5": "ade04cba6d5eb0c4e26839ac36d7bc2f"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-macosarm64-20250715-SNAPSHOT-sources.jar",
          "url": "kmpotest-macosarm64-20250715-SNAPSHOT-sources.jar",
          "size": 4488,
          "sha512": "9f10f7535ee27d8382fb16490bf3cb6610341be0c2b904cbcd4063d6fcc823448f9f9a2e0fa3a7f5f25145bc4f01015bce6cdd12e7a2396c01e6952aad024660",
          "sha256": "f05db3f2f0e3ab5dde92369b6450a5a89336df68881ea489c84e04562f9adc41",
          "sha1": "3505f17d6159b3675cbeeade613a77273eaec54a",
          "md5": "58bfe10172e666cdc07d7980f4d40330"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-macosarm64-20250715-SNAPSHOT-metadata.jar",
          "url": "kmpotest-macosarm64-20250715-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "0376374e7f5875594cfda2800cfada7f9dc8836ec9821306b36894bb941db4e2ff0f9b7642e581cfbb23074a45007438b3cbd8e5436a570e301a28e89a5514d1",
          "sha256": "e9fd60b6f5a663d0c36d0beee1ad4958eec1c59b81da3070bdd631c9f5a9459b",
          "sha1": "45e9476fab8c4e832fb109a5843348ffbe800043",
          "md5": "0cb6006000ed989616652e190480378b"
        }
      ]
    }
  ]
}
