{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-watchosArm64Main-202509019.klib",
          "url": "testballoon-shim-watchosarm64-202509019.klib",
          "size": 18981,
          "sha512": "6e66dd5c3592820893ee855964e475c993230d44b6e0f436eb21953a2510ec00d4e389f6141c494fdad1616f02bb2270a7d569a3021d32e5920133e15b6564d7",
          "sha256": "122237657ab95d7d681c56b0d53f5a74d400ec4d9b6127e4547c553ad6cc6f83",
          "sha1": "24b9031628a81b89f8a0d3ad205e93800f6347ca",
          "md5": "52343ee4886a28a7bde948a4a01eff04"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-watchosarm64-202509019-sources.jar",
          "url": "testballoon-shim-watchosarm64-202509019-sources.jar",
          "size": 3222,
          "sha512": "984ae2c26662c6ebc6d5ab84a1db53bf73b0ac9be6603b90469c7d5c3b92600bba5f1442582fa153352f375a0da5c214664edc8a025cb1e874e07e6669bd19f6",
          "sha256": "c0ea0ce1319b4132d5ae85e8dd0621f626966c2f3e711c7166d68f92f89e2c96",
          "sha1": "ef36835cacf47db0aaa939629cdfc039f1359728",
          "md5": "90f2a755590c52c67ad57a39856638b4"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-watchosarm64-202509019-metadata.jar",
          "url": "testballoon-shim-watchosarm64-202509019-metadata.jar",
          "size": 261,
          "sha512": "661cedce0f727efcae0a5aa8b1d29328806de84188e7b0fd5f086d199fa8f97f0bab508762277d24bf72e268f6cd3a8b99c6bd72d5508416564d1f2a42cbc2ec",
          "sha256": "ed288edfb4a40d3bcb61bfddee95fddb2cd52514ca05d948b6ab14fbb09a2a5a",
          "sha1": "659c386fa611a44e3eb0bfb24fe88242c24fbd22",
          "md5": "6cabdf8ccf52df4d49402098eaceaeb3"
        }
      ]
    }
  ]
}
