{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-core",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-core-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-assertions-core-6.0.0-LOCAL.jar",
          "size": 79877,
          "sha512": "205aa5389dd5c2f4a1b071868cd4209c110f750ca0f10a1b0ceb5c969894d5284d28d226a2d4992f3c9999fcc9abfa56c2fc9434d49c0e7b75f440b3f0e74a4a",
          "sha256": "92f62ae45ca3d6940c8f87eef9a3278f399cb5adb208ab342840bd3cd037d8a4",
          "sha1": "71ad69c2a9069317ba0fc4142ddafb340f363b5f",
          "md5": "88cff98724da1a47f64611d614264db0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-core-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-core-6.0.0-LOCAL-sources.jar",
          "size": 109376,
          "sha512": "ad4a435f76f66d310f8b2da246a2dad397b9be01a7cf475635a63e3f026078a7142e7b090e8183b026e48764324048d5d7ba855f5df840ef3b618dd7ce9c3f2d",
          "sha256": "2114d96ccc5ffc3bbc016e4eff19af3788d6748eff9c622607e1c1f6ac34936e",
          "sha1": "5d47dfa994b84d99bb3b1a5341dea75686a197dd",
          "md5": "845cda9bece8a927f987244bbba5d4cb"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativearm32/6.0.0-LOCAL/kotest-assertions-core-androidnativearm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativearm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativearm32/6.0.0-LOCAL/kotest-assertions-core-androidnativearm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativearm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativearm64/6.0.0-LOCAL/kotest-assertions-core-androidnativearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativearm64/6.0.0-LOCAL/kotest-assertions-core-androidnativearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativex64/6.0.0-LOCAL/kotest-assertions-core-androidnativex64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativex64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativex64/6.0.0-LOCAL/kotest-assertions-core-androidnativex64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativex64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativex86/6.0.0-LOCAL/kotest-assertions-core-androidnativex86-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativex86",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativex86/6.0.0-LOCAL/kotest-assertions-core-androidnativex86-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativex86",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-js/6.0.0-LOCAL/kotest-assertions-core-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-js/6.0.0-LOCAL/kotest-assertions-core-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-js/6.0.0-LOCAL/kotest-assertions-core-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-jvm/6.0.0-LOCAL/kotest-assertions-core-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-jvm/6.0.0-LOCAL/kotest-assertions-core-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-jvm/6.0.0-LOCAL/kotest-assertions-core-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-wasm-js/6.0.0-LOCAL/kotest-assertions-core-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-wasm-js/6.0.0-LOCAL/kotest-assertions-core-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-wasm-js/6.0.0-LOCAL/kotest-assertions-core-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
