{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.1.0-Beta1+20240918",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240918"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0-20240905.065253-61"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.0-Beta1+20240918.jar",
          "url": "k2-2.1.0-Beta1+20240918.jar",
          "size": 10785,
          "sha512": "c26ec0e0240847c9efbddd737a196eeb93db29ae1e7f84f6069e3a1f9b7c7d99a1da3454b10af56455331577a92dd2bfd6184737ffe1603ea445a4b1fec20171",
          "sha256": "e18da1a7a0815b3855a6e309767eb2c7352395bbca00d9d55e67686f5ac6f750",
          "sha1": "84f9dd070350813760eb39ef47102dba218a48f8",
          "md5": "1d42bf19e8a455057c2d76ea44d55271"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240918"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0-20240905.065253-61"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.0-Beta1+20240918.jar",
          "url": "k2-2.1.0-Beta1+20240918.jar",
          "size": 10785,
          "sha512": "c26ec0e0240847c9efbddd737a196eeb93db29ae1e7f84f6069e3a1f9b7c7d99a1da3454b10af56455331577a92dd2bfd6184737ffe1603ea445a4b1fec20171",
          "sha256": "e18da1a7a0815b3855a6e309767eb2c7352395bbca00d9d55e67686f5ac6f750",
          "sha1": "84f9dd070350813760eb39ef47102dba218a48f8",
          "md5": "1d42bf19e8a455057c2d76ea44d55271"
        }
      ]
    }
  ]
}
