{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250714/kmpotest-20250714.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250714",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-tvosArm64Main-20250714.klib",
          "url": "kmpotest-tvosarm64-20250714.klib",
          "size": 38170,
          "sha512": "991d73a6a9740745c8316a52d22a4bf10960981e6a74ca274f59e1589c3babe7c463da53f8fad258b7ce4797ae210f05d2ac2a7dd59c98f71ff964675a9c997a",
          "sha256": "3aca7f8de2f743794d00381ff5f499c16b936fe9fb49552e5005a0c4fa78ee6b",
          "sha1": "4522858d82755efaeac00d75d30a52ee156945ee",
          "md5": "450b8c551c842306541a187643a626d0"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-tvosarm64-20250714-sources.jar",
          "url": "kmpotest-tvosarm64-20250714-sources.jar",
          "size": 3853,
          "sha512": "273c76c061ddeaf1641691cac950b95331d253c4c9bd96fb3b480df5a5481ca373618702fc763dec799e3202c5df224fcbc599420629de57c8f34ca4ce49accd",
          "sha256": "bef9ec8bbb96be60f5b791ee1622f689625c9ce5a25bd81cab9ebaf2e63b0dde",
          "sha1": "e88adb27aafbc7f53b4c5da51fac13c6632037ba",
          "md5": "8e85c4e5001daa6d63bce8445661af20"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-tvosarm64-20250714-metadata.jar",
          "url": "kmpotest-tvosarm64-20250714-metadata.jar",
          "size": 261,
          "sha512": "6a3b40f06db19e8028e9bc49e73733c6af46c6d890c50bb2a54a4e19827a50f57aaaa1e1c39b7cda26a585263f2a76a172afc6e5693e41bb4d14fa591695b1e9",
          "sha256": "2ae9be181f223ac925eb09bbea8fb785d2bedafb5d83aeccc463f7677a1c6d77",
          "sha1": "4e37bb5d43b1cd870963642552c722711bde20fd",
          "md5": "700dca09fa09950a235fb3f1405bcb58"
        }
      ]
    }
  ]
}
