{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-framework-engine/6.0.0-LOCAL/kotest-framework-engine-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-framework-engine",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-wasm-js-6.0.0-LOCAL.klib",
          "url": "kotest-framework-engine-wasm-js-6.0.0-LOCAL.klib",
          "size": 911551,
          "sha512": "49031be8bdaa1ed3c081ad187bc76b5479abc07516720421364f13846c17cc1fb7c75bb9473b555dff7b81f5d290933fc704d921f79d5bbed459072ca033ceb7",
          "sha256": "af18adea62701a8f6569720b8e3f6139f9879d89d543f3e955109912db785a29",
          "sha1": "f25cb4c693388795eb4b713f015f102284de557a",
          "md5": "e4228c00efeecea5f60e681b60bbdcbe"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-wasm-js-6.0.0-LOCAL.klib",
          "url": "kotest-framework-engine-wasm-js-6.0.0-LOCAL.klib",
          "size": 911551,
          "sha512": "49031be8bdaa1ed3c081ad187bc76b5479abc07516720421364f13846c17cc1fb7c75bb9473b555dff7b81f5d290933fc704d921f79d5bbed459072ca033ceb7",
          "sha256": "af18adea62701a8f6569720b8e3f6139f9879d89d543f3e955109912db785a29",
          "sha1": "f25cb4c693388795eb4b713f015f102284de557a",
          "md5": "e4228c00efeecea5f60e681b60bbdcbe"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotest-framework-engine-wasm-js-6.0.0-LOCAL-sources.jar",
          "url": "kotest-framework-engine-wasm-js-6.0.0-LOCAL-sources.jar",
          "size": 258981,
          "sha512": "edc485a4c81698721eb78779188ab06b019748a35bc768fc33225fdb8d1c2be420318394e8db79762c4e573b10408ce4792c3636efb0b9dfa38d0f9b4941fd2d",
          "sha256": "10744d950e16795fcb9e482f3543ecd6b09ad0f1d413254643a3ebd1f6794a50",
          "sha1": "862f22d75c9eefcf33ca1d67d083870a95dde937",
          "md5": "9b2b60689acaf8f4e932d89412694050"
        }
      ]
    }
  ]
}
