{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.1.0-Beta1+20240920",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240920"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.0-Beta1-1.0.25"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0-20240918.002009-71"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.0-Beta1+20240920.jar",
          "url": "k2-2.1.0-Beta1+20240920.jar",
          "size": 10785,
          "sha512": "b571d287eac9382974e8f279c0bb0c38f9b5411267cddd652de0a20fc38728bc420e7f86d3d752fc1fc549ca5bf27ea67ef35485e95f6981a176c4ff5e88ab37",
          "sha256": "ddacb60c3ae0717a4e6d37740986323af2584747d1e69d943b25b34514536be1",
          "sha1": "8b8e6bf4026cdc128852b34a12a5f5bf2f48c4a0",
          "md5": "8e0852b8a6835a20e32e8b336d5d8911"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240920"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.0-Beta1-1.0.25"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0-20240918.002009-71"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.0-Beta1+20240920.jar",
          "url": "k2-2.1.0-Beta1+20240920.jar",
          "size": 10785,
          "sha512": "b571d287eac9382974e8f279c0bb0c38f9b5411267cddd652de0a20fc38728bc420e7f86d3d752fc1fc549ca5bf27ea67ef35485e95f6981a176c4ff5e88ab37",
          "sha256": "ddacb60c3ae0717a4e6d37740986323af2584747d1e69d943b25b34514536be1",
          "sha1": "8b8e6bf4026cdc128852b34a12a5f5bf2f48c4a0",
          "md5": "8e0852b8a6835a20e32e8b336d5d8911"
        }
      ]
    }
  ]
}
