{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-property-arrow",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-optics",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-arrow-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-property-arrow-6.0.0-LOCAL.jar",
          "size": 6796,
          "sha512": "b88f64492c865c983a9390e03605b9da5743c3c6da49d3fdb2735914ef6ac97ebc12b5c615475b138b038052c68d698e2a3fd6ba81d0ccb32bccc9dd9dc58bee",
          "sha256": "d31a6cba029a1ea807c51d032cede60726825b703305ae7710c930ad26ed191b",
          "sha1": "d8ab8e8aeb18c130a8020ce7700eed97972f0590",
          "md5": "88d5fa8fedbfe8151b92bf5df0014278"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-property-arrow-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-property-arrow-6.0.0-LOCAL-sources.jar",
          "size": 5869,
          "sha512": "01f2332f8fea760472bb4d9f2bb4f81ab3f3b16c43dc8072b40dfbe961e012ed461c69ea1937149f93305e5760994280d12babb4370643bfa618bc597f293ad8",
          "sha256": "946d2d763280f02406abe7958afbb3f815ee3b18ee5ec78b5be170aa853a4589",
          "sha1": "c50319cf0fedf615e37bf79dccde5b9ed1c5cdc6",
          "md5": "1f4faa4bf55fcdb1f135020333f718e6"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-property-arrow-js/6.0.0-LOCAL/kotest-property-arrow-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-arrow-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-property-arrow-js/6.0.0-LOCAL/kotest-property-arrow-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-arrow-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-property-arrow-js/6.0.0-LOCAL/kotest-property-arrow-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-arrow-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-property-arrow-jvm/6.0.0-LOCAL/kotest-property-arrow-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-arrow-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-property-arrow-jvm/6.0.0-LOCAL/kotest-property-arrow-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-arrow-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-property-arrow-jvm/6.0.0-LOCAL/kotest-property-arrow-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-arrow-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-property-arrow-wasm-js/6.0.0-LOCAL/kotest-property-arrow-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-arrow-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-property-arrow-wasm-js/6.0.0-LOCAL/kotest-property-arrow-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-arrow-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-property-arrow-wasm-js/6.0.0-LOCAL/kotest-property-arrow-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-arrow-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
