{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-koin/6.0.0-LOCAL/kotest-extensions-koin-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-extensions-koin",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-koin-wasm-js-6.0.0-LOCAL.klib",
          "url": "kotest-extensions-koin-wasm-js-6.0.0-LOCAL.klib",
          "size": 9614,
          "sha512": "c84ad86046f0e442515ad4f0b6c8587d1f77519622dd05246f4646e9948fba1b150acbfc7b97f20ef81443c0721279b0c2daa159bf424a634fc03e0829ceb0c0",
          "sha256": "8d256b6950f31864ce01d8680d4cfa92b390ce3c5768d834603ef06ebbff6a9d",
          "sha1": "f82e56f68d8e0257992c356d0655e6a5c03dc3bf",
          "md5": "267c71534cdd68f93cb92435860b4d52"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-koin-wasm-js-6.0.0-LOCAL.klib",
          "url": "kotest-extensions-koin-wasm-js-6.0.0-LOCAL.klib",
          "size": 9614,
          "sha512": "c84ad86046f0e442515ad4f0b6c8587d1f77519622dd05246f4646e9948fba1b150acbfc7b97f20ef81443c0721279b0c2daa159bf424a634fc03e0829ceb0c0",
          "sha256": "8d256b6950f31864ce01d8680d4cfa92b390ce3c5768d834603ef06ebbff6a9d",
          "sha1": "f82e56f68d8e0257992c356d0655e6a5c03dc3bf",
          "md5": "267c71534cdd68f93cb92435860b4d52"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotest-extensions-koin-wasm-js-6.0.0-LOCAL-sources.jar",
          "url": "kotest-extensions-koin-wasm-js-6.0.0-LOCAL-sources.jar",
          "size": 1921,
          "sha512": "90abf70609469a92a4d21efe1e3450939678a685c5c59e2293ba6bda8c7618a8a13522139b7a9c9cb2e873c71fac2297385d0671e078c5bbc7cb80c124446589",
          "sha256": "005c8e142c3177baedc3130fb2ed2067171fa388a1b9c2218ad848d94516147b",
          "sha1": "587d26289d3c20e40b135a90ba4fd791758f6ba0",
          "md5": "f412afa78e5f7c5fd02cb0b819ccda38"
        }
      ]
    }
  ]
}
