{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-koin/6.0.0-LOCAL/kotest-extensions-koin-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-extensions-koin",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-koin-wasm-js-6.0.0-LOCAL.klib",
          "url": "kotest-extensions-koin-wasm-js-6.0.0-LOCAL.klib",
          "size": 9599,
          "sha512": "199bde2148e3ff0b4003b2766bc9b5e1562d83a871cf0fd016537fe10b0a41d59816ac621b460f39e4fc803018a260e7d4e2d7ec37983b7b6345248a15aa9108",
          "sha256": "57db608ceb65177900dda4cd24f9088db467ca804dd7f7c7bc259e8b18bde0ad",
          "sha1": "0e5396c930efa622a6a606724be947cb3bd182fa",
          "md5": "4c9d7b6ace7ee85a3c7c496b8c96a034"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-koin-wasm-js-6.0.0-LOCAL.klib",
          "url": "kotest-extensions-koin-wasm-js-6.0.0-LOCAL.klib",
          "size": 9599,
          "sha512": "199bde2148e3ff0b4003b2766bc9b5e1562d83a871cf0fd016537fe10b0a41d59816ac621b460f39e4fc803018a260e7d4e2d7ec37983b7b6345248a15aa9108",
          "sha256": "57db608ceb65177900dda4cd24f9088db467ca804dd7f7c7bc259e8b18bde0ad",
          "sha1": "0e5396c930efa622a6a606724be947cb3bd182fa",
          "md5": "4c9d7b6ace7ee85a3c7c496b8c96a034"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotest-extensions-koin-wasm-js-6.0.0-LOCAL-sources.jar",
          "url": "kotest-extensions-koin-wasm-js-6.0.0-LOCAL-sources.jar",
          "size": 1914,
          "sha512": "d24b705b1e846c21232846f56774368cfe714df6f42b41ef69fbcc10e781e1a6c7d4d8175a340a8b4cd987e437dc8797d84ebb373cdaeb2d2869f323ded03c44",
          "sha256": "969a405501f838614b715e11b14f19f12fceb6cf5a992d43adc1a19e0564f908",
          "sha1": "1ecdff34977c560614b258fd47225b380be410a5",
          "md5": "513a077f681c429e302f50e55dc28ef1"
        }
      ]
    }
  ]
}
