{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-yaml",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-yaml-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-assertions-yaml-6.0.0-LOCAL.jar",
          "size": 2438,
          "sha512": "dcdab53e41d797c3b0e6eca898d5ae8bf7e400dd2c2c78bef93e349a16908655bad9ce9cb031921892c77cfaded37e0434307871bec4be9282dddab035a46b6e",
          "sha256": "3f5d7e901c0539ecddfc8a9e663b495e981c49a8b3aeb49f44a8e5bcf2dfd5cd",
          "sha1": "1e29524a0285a1882e167feb1436051cf89a1d48",
          "md5": "78a9b5239310f1f2231049e9bcd9fab5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-yaml-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-yaml-6.0.0-LOCAL-sources.jar",
          "size": 1756,
          "sha512": "7c4df3857b3bec2081b35b3415adc081030f8720f8bea9bfe89f19f79ce10aa6baaf393d56d0384cb19387dc005874a5c743e96ef3fc5216827fb61c2f6412d2",
          "sha256": "c6bcc40dd3d8d253f046d136ca2a1bcf25bf1e16e71159d5bb7db36073c3d7ab",
          "sha1": "fe24caacc606dcffe382770e9ad3bb97138dca17",
          "md5": "97c9b6e287b878d83cc3fbcb567e48d7"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-yaml-js/6.0.0-LOCAL/kotest-assertions-yaml-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-yaml-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-yaml-js/6.0.0-LOCAL/kotest-assertions-yaml-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-yaml-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-yaml-js/6.0.0-LOCAL/kotest-assertions-yaml-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-yaml-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-yaml-jvm/6.0.0-LOCAL/kotest-assertions-yaml-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-yaml-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-yaml-jvm/6.0.0-LOCAL/kotest-assertions-yaml-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-yaml-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-yaml-jvm/6.0.0-LOCAL/kotest-assertions-yaml-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-yaml-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-yaml-wasm-js/6.0.0-LOCAL/kotest-assertions-yaml-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-yaml-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-yaml-wasm-js/6.0.0-LOCAL/kotest-assertions-yaml-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-yaml-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-yaml-wasm-js/6.0.0-LOCAL/kotest-assertions-yaml-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-assertions-yaml-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
