{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251109/testhelper-20251109.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251109",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-macosX64Main-20251109.klib",
          "url": "testhelper-macosx64-20251109.klib",
          "size": 6098,
          "sha512": "a9721d4e343cbceb7081d90f4302b66e8c4f957c40c29285bc9794ff9629efac0cd555e46f17d91e18467cf76d1286dcf666df3bde918530453021364423756b",
          "sha256": "972c269d996295b0f35e0839ac6268034bcfe74c7d742c18a7b29f44d9dcf69d",
          "sha1": "31ce632b78ea8c16214d2b3a1c650727cd7bcc38",
          "md5": "d30aca561f51440678f6d9c51e2bdd2b"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-macosx64-20251109-sources.jar",
          "url": "testhelper-macosx64-20251109-sources.jar",
          "size": 1883,
          "sha512": "a0c7cd3b3b28351e8ca472900b8d4766b7500519ee07d1afeebc10f68677266ab9be7d4c775fe10aacba9ee168e36a999600b00b30a5e12ec550966614b2c7d7",
          "sha256": "62b8fda7e77997d88add60ff5e498859e5c6626ab710fcaf4a5842fa0e8d9849",
          "sha1": "191ec1bea72b8bf42746a070783ffe2fa42ab055",
          "md5": "5553b412f52f7eec93e436d8042f47b3"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-macosx64-20251109-metadata.jar",
          "url": "testhelper-macosx64-20251109-metadata.jar",
          "size": 261,
          "sha512": "0181e8c6a726479c64faa1b3e1d97dd17d2c2eda86b5ebc5de1f9efec1aaa4dd4814656877d5c93b7250a7bf486e5cdb64f4e6a029bc48fbff6cbb377b061b4a",
          "sha256": "2ea53908854525fae7978186d41581731c703a406355a2fb4393e25ba316b520",
          "sha1": "8e40d6d73a4673a07814c9dbfae5fe7610b1905d",
          "md5": "71af01ef3c3219a3a74d3eedef3385d3"
        }
      ]
    }
  ]
}
