{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-tvosSimulatorArm64Main-202509019.klib",
          "url": "testballoon-shim-tvossimulatorarm64-202509019.klib",
          "size": 19065,
          "sha512": "f5d587cefa2ddd865113600aea7c0c6662c5fc4fb68740bb9f88bdc5c2db22472a52669ce9062a35f9e103e62a6a47e6bb3164100019e5a5ab7e22744fe5050f",
          "sha256": "25c4ed0729e7e530fc16ede88ad25c714545848c972aa7eacf9c5c647ca690c2",
          "sha1": "c7482179f26d9703033dff5dcd9ecb57b8023f01",
          "md5": "74c811e2ca01da03b0dddbe4e37fe44f"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-tvossimulatorarm64-202509019-sources.jar",
          "url": "testballoon-shim-tvossimulatorarm64-202509019-sources.jar",
          "size": 3285,
          "sha512": "25965f47454727d6152fe07aad5e140baa6edf59ec5bd4a4c800b8d41f967696b6f277c7d224c61fa09a586ba50f724f478ed8d68987a0cbf60e4866016a5f95",
          "sha256": "0c874457974d72fa1e45c0437bc030ff66578cf89d7ca71a3f239a12a8ce2c93",
          "sha1": "8bc3cab41765290e8e566bdcb6e304d84d06cb94",
          "md5": "340215075cc69c80d35af427e0c834d8"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-tvossimulatorarm64-202509019-metadata.jar",
          "url": "testballoon-shim-tvossimulatorarm64-202509019-metadata.jar",
          "size": 261,
          "sha512": "7c0c0e9bfb43d97beea34244fc1e893c67a3271642698bf1a90554f371e255f399aa425edceab35a0f0cefcdf968b27267ceae8cadc78a0c75bc3cdf13134f36",
          "sha256": "8b5ce1903a03897d41c8a1585537d832fe67c7cee830683d3d7a6acaaddb1d60",
          "sha1": "a81d4b6ecd23032950486b23f06b00eab981f286",
          "md5": "7a955626c6b3d425892e08d7801b71e9"
        }
      ]
    }
  ]
}
