{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-core/0.6.3-K2.2.20-SNAPSHOT/testBalloon-framework-core-0.6.3-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-core",
    "version": "0.6.3-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-abstractions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-core-js-0.6.3-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-framework-core-js-0.6.3-K2.2.20-SNAPSHOT.klib",
          "size": 133885,
          "sha512": "72de22daa6bbc22d1dbad3c0ef8da7a0f86b50ab9ef689154b32b3d10592d9569822648cc57b1f3cad00939b3f231b4ab95efa935794e42e555fa59435c2840a",
          "sha256": "9ca5514065abdc4fcfc960214c7222651a87e65d95a3c84c8c8cce318c504781",
          "sha1": "bc3223d07ce5e48913051c0d548ede574eae7939",
          "md5": "d74df01367e51b28ce176a1388601385"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-abstractions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-core-js-0.6.3-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-framework-core-js-0.6.3-K2.2.20-SNAPSHOT.klib",
          "size": 133885,
          "sha512": "72de22daa6bbc22d1dbad3c0ef8da7a0f86b50ab9ef689154b32b3d10592d9569822648cc57b1f3cad00939b3f231b4ab95efa935794e42e555fa59435c2840a",
          "sha256": "9ca5514065abdc4fcfc960214c7222651a87e65d95a3c84c8c8cce318c504781",
          "sha1": "bc3223d07ce5e48913051c0d548ede574eae7939",
          "md5": "d74df01367e51b28ce176a1388601385"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "testBalloon-framework-core-js-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-core-js-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "size": 39583,
          "sha512": "ec3ce8664be5323465197ac9577a75b12cc09066e09ca5a79d8ff3e0ea76106e4814e22628d26f022274d57563bea5c802cf4aa28fc70916c3075689dc252ab0",
          "sha256": "614db0f3c49c1404697067ca1d6fecf6312d45c4f074655f455535d45a981b41",
          "sha1": "e37992d0a19f7ffabf30f35ba5874fa3017230eb",
          "md5": "6ade27f18b3465006bf3f6bec6911f61"
        }
      ]
    }
  ]
}
