{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "1.9.23+20240319+1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240319+1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.19"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240319+1.jar",
          "url": "k2-1.9.23+20240319+1.jar",
          "size": 10231,
          "sha512": "583c0c7a43a05e13aa403526c8d40468131b5e3fae58ecfc5c110a2e52ac5308276454d6d21fe4db8e60f4463d81cbe37fd4794357b0cca2edb7a32c15e7b6a4",
          "sha256": "8cdcf626e9db58b674fb440b3fed29033451ca8309e08011465096270bce5fe8",
          "sha1": "e4107b7975f687d0a0929508dea0faa5829864e3",
          "md5": "463d8b926fb9fea84c94ba5dd3debf74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240319+1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.23-1.0.19"
          }
        }
      ],
      "files": [
        {
          "name": "k2-1.9.23+20240319+1.jar",
          "url": "k2-1.9.23+20240319+1.jar",
          "size": 10231,
          "sha512": "583c0c7a43a05e13aa403526c8d40468131b5e3fae58ecfc5c110a2e52ac5308276454d6d21fe4db8e60f4463d81cbe37fd4794357b0cca2edb7a32c15e7b6a4",
          "sha256": "8cdcf626e9db58b674fb440b3fed29033451ca8309e08011465096270bce5fe8",
          "sha1": "e4107b7975f687d0a0929508dea0faa5829864e3",
          "md5": "463d8b926fb9fea84c94ba5dd3debf74"
        }
      ]
    }
  ]
}
