{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250727/kmpotest-20250727.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250727",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-tvosX64Main-20250727.klib",
          "url": "kmpotest-tvosx64-20250727.klib",
          "size": 39658,
          "sha512": "127583ea5a8279a6f04454d866cbfa03d7b2537653734f78a1f8857b6d498f8e4f9e1abe83de72572a1cb514f4ad6241669a07080493d1b79a844d53787c5751",
          "sha256": "8d7c561019130f78c9cbfb3968ba975f7ab8a44e2f28358aca216bb872ed734a",
          "sha1": "9e72b807b72fd2906bae231590982f7a1f2b953c",
          "md5": "72b5e8cd05bd12e823b5c46a7308f3dc"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-tvosx64-20250727-sources.jar",
          "url": "kmpotest-tvosx64-20250727-sources.jar",
          "size": 4285,
          "sha512": "b9cbce2327751f819cde9a84b9cb07bf5dcd2ce30b9a86398b05bc86921226ee329dce970ef5461407bfbf9e14d63768181d8a7fe490bab3231cfd4f7ea93fa9",
          "sha256": "8efb7ef74cbffbfec16310ce926fad125a119cb640f7483989a690741700162f",
          "sha1": "f09950f3c46a7b2803b63ca83fdef804960de892",
          "md5": "3e6ede11a88614221fbc653719283349"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-tvosx64-20250727-metadata.jar",
          "url": "kmpotest-tvosx64-20250727-metadata.jar",
          "size": 261,
          "sha512": "6daf8557542e22b03cee3413849e6ded51cea06e10e04d323e73c7ec06a5c53ef389aa1f34bf43dce56513dcf81b6e89637f4e887668f2d5515f0e1826f9dd8c",
          "sha256": "8ebd35f232015196cb343a75b0a50d2ff3616250e22641b6b8a89955a8e3ec29",
          "sha1": "a54eee17550cee317689477ab513b78e27ec445a",
          "md5": "c4c1872b155e7284ee106972da1ae8db"
        }
      ]
    }
  ]
}
