{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/20251017/testballoon-shim-20251017.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-macosX64Main-20251017.klib",
          "url": "testballoon-shim-macosx64-20251017.klib",
          "size": 19843,
          "sha512": "4023f0ac9c2f792f40f3c8d5f3f1c9381d8104a149694fc97af6b631f0f8246bc4f53ef7255c45ff5e65860b38ce86ffdc1ed69c364ad85723420b716c7dc43e",
          "sha256": "6f28bdf495800bb310cfd0d1fdb3df9e53f6033ad7f6edd16dc4ab5fcb26445f",
          "sha1": "847168c1ea3f360f942417446555b572db972af0",
          "md5": "f5afe6e0458c577fd13c605b72a63cfa"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-macosx64-20251017-sources.jar",
          "url": "testballoon-shim-macosx64-20251017-sources.jar",
          "size": 3341,
          "sha512": "1680f907191ef133e290c5abc2199043a3d281e79c91e8eed691071b209119cc9efd7dce60f0f599b37d54c10040f570c2a40e6a7aa0a7ac2384788333f4c8f4",
          "sha256": "8b7d6bace87c2f759c04c48a5147d59a6ac5374d69465c59b1d5763357cc4263",
          "sha1": "8aae1ac4981c2800b8f2f7ca2b48275341371500",
          "md5": "ed6c424ee53234ac28ed858f2b8694fb"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-macosx64-20251017-metadata.jar",
          "url": "testballoon-shim-macosx64-20251017-metadata.jar",
          "size": 261,
          "sha512": "dbd48b7acf6c7ae5ef247829bb8bb39674e274a4dad82de61fee323fe44639086bae80274722c098e85bfb1b78fb6c06084454066cdaa31d3ef5cfa3c05ef43c",
          "sha256": "13ebc23a385b0f9f50ece87f0365289f775f79e716e56dd89d9f00b06fb83a40",
          "sha1": "31d64c4647380c2dd9096b7cdd3a755396a0d75c",
          "md5": "2c5424d567aea51e0f9996ab4b5c331f"
        }
      ]
    }
  ]
}
