{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.0.0+20240609",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240609"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.0-1.0.22"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "strictly": "5.9.1",
            "requires": "5.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.0+20240609.jar",
          "url": "k2-2.0.0+20240609.jar",
          "size": 10753,
          "sha512": "e1c3d0ca56c6eeba2ad194ca0b4f362b5153e64451284a67fb4be1a11fa28f7070a7330c465f03fbe839fd1c1e32c93772c0e7d2a606ee88921cb987f3fa7724",
          "sha256": "1fe3cbbef808c3abb395510ab18fa6f5d00df9957517108bc1930270d2aab5d8",
          "sha1": "e4134160c8bb865b7711b08c40b997460821d2eb",
          "md5": "b062478ea049e096c0eced5200789294"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240609"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.0-1.0.22"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "strictly": "5.9.1",
            "requires": "5.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.0+20240609.jar",
          "url": "k2-2.0.0+20240609.jar",
          "size": 10753,
          "sha512": "e1c3d0ca56c6eeba2ad194ca0b4f362b5153e64451284a67fb4be1a11fa28f7070a7330c465f03fbe839fd1c1e32c93772c0e7d2a606ee88921cb987f3fa7724",
          "sha256": "1fe3cbbef808c3abb395510ab18fa6f5d00df9957517108bc1930270d2aab5d8",
          "sha1": "e4134160c8bb865b7711b08c40b997460821d2eb",
          "md5": "b062478ea049e096c0eced5200789294"
        }
      ]
    }
  ]
}
