{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-js-202509019.klib",
          "url": "testballoon-shim-js-202509019.klib",
          "size": 19137,
          "sha512": "b46030eb09d07a9988d2ae02e254a98620ff193d6c3c8a8be5ae331ccc4ce1b4925b0475ecf8a07dd7f197d6455ddf26bf806b6b30a35683e8eabded39981231",
          "sha256": "0f3c2396d750fd8520254af26cbd9b7fccd60d86960602ec318cde64afeb99d2",
          "sha1": "f1b37fed706afe0af1e7b3ec7345a674dc569359",
          "md5": "fd0a5272d419aa58abae8bf6aa6e6726"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-js-202509019.klib",
          "url": "testballoon-shim-js-202509019.klib",
          "size": 19137,
          "sha512": "b46030eb09d07a9988d2ae02e254a98620ff193d6c3c8a8be5ae331ccc4ce1b4925b0475ecf8a07dd7f197d6455ddf26bf806b6b30a35683e8eabded39981231",
          "sha256": "0f3c2396d750fd8520254af26cbd9b7fccd60d86960602ec318cde64afeb99d2",
          "sha1": "f1b37fed706afe0af1e7b3ec7345a674dc569359",
          "md5": "fd0a5272d419aa58abae8bf6aa6e6726"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "testballoon-shim-js-202509019-sources.jar",
          "url": "testballoon-shim-js-202509019-sources.jar",
          "size": 3246,
          "sha512": "00eb32145bcda3673257b0d23a5ac6add2e4cdee2ae365981ff5bf50a3da6932de02243cfe51dc02190c57c615c4969bff35cdc260de7c169e885a370478f4a3",
          "sha256": "25237d21db2dc0c0fc94f6dc31f0d7936f9186dc8c0d756ab5224bc1dca2a4be",
          "sha1": "91e62918a94607a5187c39d649abb71276a5a7ec",
          "md5": "80661301e53689c279780ec0d33fa0fd"
        }
      ]
    }
  ]
}
