{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-js-202509019.klib",
          "url": "testballoon-shim-js-202509019.klib",
          "size": 18307,
          "sha512": "befa299e5be3e4e9889ef02be64ae7aa71d7d9a47ac679e4d9d1ecb77764edad1da1e94ef8bd85910565b39637e1de4c19ea537fc06504161ffa88d265aa30d3",
          "sha256": "3a3366920f039d24844996d695097e47b7207009696bc26541f125c70664afec",
          "sha1": "ab0abccb9adb62cbe7c7240385271900f45ef784",
          "md5": "68eab246650b467600f54e124562a76e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-js-202509019.klib",
          "url": "testballoon-shim-js-202509019.klib",
          "size": 18307,
          "sha512": "befa299e5be3e4e9889ef02be64ae7aa71d7d9a47ac679e4d9d1ecb77764edad1da1e94ef8bd85910565b39637e1de4c19ea537fc06504161ffa88d265aa30d3",
          "sha256": "3a3366920f039d24844996d695097e47b7207009696bc26541f125c70664afec",
          "sha1": "ab0abccb9adb62cbe7c7240385271900f45ef784",
          "md5": "68eab246650b467600f54e124562a76e"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "testballoon-shim-js-202509019-sources.jar",
          "url": "testballoon-shim-js-202509019-sources.jar",
          "size": 3104,
          "sha512": "71d577ad57ea51b2edad30d8e11159f8529aa330f28c8a5bd652e942c9529d0603eeda5f84f20809d4dde25c93472edcac9b3d5ed31fa33f7720b3a5c6199509",
          "sha256": "814daa2f71cbf23cee49949437c6e3df9c86522e755cf940fbdb04bb59269837",
          "sha1": "5267db24943a0549674b2fb85ee00301a8a87aad",
          "md5": "1ad1d5ac661084437489880a2002fbe6"
        }
      ]
    }
  ]
}
