{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-property-arrow/6.0.0-LOCAL/kotest-property-arrow-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-property-arrow",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "io.arrow-kt",
          "module": "arrow-optics",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-arrow-js-6.0.0-LOCAL.klib",
          "url": "kotest-property-arrow-js-6.0.0-LOCAL.klib",
          "size": 22617,
          "sha512": "5426b854a6a1829e8929a02b905dd38c416284891cce23e153d39349239780a83c9fc5f150b39c89f074d43d66d5c0a619eb45e359a31483408d3d5de40eeed7",
          "sha256": "bdb9c142d12f476112dfbc43cf15d8def5a5fda0da684d0c69022290c1b9463d",
          "sha1": "3e764ec449cce8fff706204108974240169cd724",
          "md5": "f29de00281c758313494fb5dea05a66f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "io.arrow-kt",
          "module": "arrow-optics",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-functions",
          "version": {
            "requires": "2.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-arrow-js-6.0.0-LOCAL.klib",
          "url": "kotest-property-arrow-js-6.0.0-LOCAL.klib",
          "size": 22617,
          "sha512": "5426b854a6a1829e8929a02b905dd38c416284891cce23e153d39349239780a83c9fc5f150b39c89f074d43d66d5c0a619eb45e359a31483408d3d5de40eeed7",
          "sha256": "bdb9c142d12f476112dfbc43cf15d8def5a5fda0da684d0c69022290c1b9463d",
          "sha1": "3e764ec449cce8fff706204108974240169cd724",
          "md5": "f29de00281c758313494fb5dea05a66f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotest-property-arrow-js-6.0.0-LOCAL-sources.jar",
          "url": "kotest-property-arrow-js-6.0.0-LOCAL-sources.jar",
          "size": 5869,
          "sha512": "01f2332f8fea760472bb4d9f2bb4f81ab3f3b16c43dc8072b40dfbe961e012ed461c69ea1937149f93305e5760994280d12babb4370643bfa618bc597f293ad8",
          "sha256": "946d2d763280f02406abe7958afbb3f815ee3b18ee5ec78b5be170aa853a4589",
          "sha1": "c50319cf0fedf615e37bf79dccde5b9ed1c5cdc6",
          "md5": "1f4faa4bf55fcdb1f135020333f718e6"
        }
      ]
    }
  ]
}
