{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "legacy",
    "version": "1.9.10+20240319+1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.10-1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-1.9.10+20240319+1.jar",
          "url": "legacy-1.9.10+20240319+1.jar",
          "size": 115966,
          "sha512": "baacd5073b3e8cc43c39bf1de30f3f7f8ff95997de4d8ff9caa67f6d55d45d8f46d481b1b12b6c8402362fe36c2fdf9f907302d3738aac4836db0685c46921ce",
          "sha256": "98f34d71d7ad2684d0140c2c790ca5ef6bf839339d070c2cffe233df714dad50",
          "sha1": "8780aecd4b9186568b847d4e07745ae035d93497",
          "md5": "04c34e7f1c43d867fc234a65cb42f66f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.10-1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-1.9.10+20240319+1.jar",
          "url": "legacy-1.9.10+20240319+1.jar",
          "size": 115966,
          "sha512": "baacd5073b3e8cc43c39bf1de30f3f7f8ff95997de4d8ff9caa67f6d55d45d8f46d481b1b12b6c8402362fe36c2fdf9f907302d3738aac4836db0685c46921ce",
          "sha256": "98f34d71d7ad2684d0140c2c790ca5ef6bf839339d070c2cffe233df714dad50",
          "sha1": "8780aecd4b9186568b847d4e07745ae035d93497",
          "md5": "04c34e7f1c43d867fc234a65cb42f66f"
        }
      ]
    }
  ]
}
