{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-spring/6.0.0-LOCAL-PRE/kotest-extensions-spring-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-extensions-spring",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-spring-jvm-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-extensions-spring-jvm-6.0.0-LOCAL-PRE.jar",
          "size": 29774,
          "sha512": "cff16d656b4a8ec4f6d6d4c819232656fb247702731618b4b37ee48e981f59e3732096aba19ad72b75a83186a8698efd61389645dd057175e9ece0e307406e22",
          "sha256": "bcbfb698d375b1c11e3a0be6f4d88f0caeedfbf2309acc862843053cbefc6b55",
          "sha1": "bbc1921056eb11623b1231cf5149caa406feef76",
          "md5": "1467f2e8f7f7f1af9bae6d5a9748ca93"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.15.11"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-spring-jvm-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-extensions-spring-jvm-6.0.0-LOCAL-PRE.jar",
          "size": 29774,
          "sha512": "cff16d656b4a8ec4f6d6d4c819232656fb247702731618b4b37ee48e981f59e3732096aba19ad72b75a83186a8698efd61389645dd057175e9ece0e307406e22",
          "sha256": "bcbfb698d375b1c11e3a0be6f4d88f0caeedfbf2309acc862843053cbefc6b55",
          "sha1": "bbc1921056eb11623b1231cf5149caa406feef76",
          "md5": "1467f2e8f7f7f1af9bae6d5a9748ca93"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-extensions-spring-jvm-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-extensions-spring-jvm-6.0.0-LOCAL-PRE-sources.jar",
          "size": 6595,
          "sha512": "7b3b217a9018382c66e8a99a233acac876df9b92217823e9ada4595773ee837e9179717f5285acb3f0ee30cb0af7be7dc5bd3d5890b229073318c03a04f908ab",
          "sha256": "151e0098bfc3624a533fb2c72fc2655cf4e31b172794828dfcad4813b7b66bbf",
          "sha1": "2d331060aa6751c5437da4f9d06d552ab16434fa",
          "md5": "064623f7eeeb781f48edbf776e31d97f"
        }
      ]
    }
  ]
}
