{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.1.20-Beta2+202500201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+202500201"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20-Beta2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.20-Beta2-1.0.29"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.20-Beta2+202500201.jar",
          "url": "k2-2.1.20-Beta2+202500201.jar",
          "size": 10775,
          "sha512": "3d3f554552534bb0d50bd0f048740121328b75230155f92481b817c070c740e480bae72c989bfafb7f4d9d542f450e4f68ed3f4f24b99ce783adc1dc236945e4",
          "sha256": "02a86663a0f16d014b9956b5864070c1ee8e60b75356d13eaf40e2181c45466d",
          "sha1": "bbcf2792a4375d3e58929b10b74ee8b210c9fddc",
          "md5": "00b174b725b582172b5aeb5d91a1dee1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+202500201"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20-Beta2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.20-Beta2-1.0.29"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.20-Beta2+202500201.jar",
          "url": "k2-2.1.20-Beta2+202500201.jar",
          "size": 10775,
          "sha512": "3d3f554552534bb0d50bd0f048740121328b75230155f92481b817c070c740e480bae72c989bfafb7f4d9d542f450e4f68ed3f4f24b99ce783adc1dc236945e4",
          "sha256": "02a86663a0f16d014b9956b5864070c1ee8e60b75356d13eaf40e2181c45466d",
          "sha1": "bbcf2792a4375d3e58929b10b74ee8b210c9fddc",
          "md5": "00b174b725b582172b5aeb5d91a1dee1"
        }
      ]
    }
  ]
}
