{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-kotlinx-datetime",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-metadata-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-assertions-kotlinx-datetime-6.0.0-LOCAL-PRE.jar",
          "size": 4170,
          "sha512": "95b305ea1ca2244af48a7c1ab9eed1a7d7c891083d250178d415b05210d719bb3137fa2948a48c368b51214b8f4af1fb239ec2983ead5ff29b26e6b839bdbd5f",
          "sha256": "468460dee7761896d6da9c03eef085202ce1a4628fbd4f37c478958583eb2148",
          "sha1": "a3940fb9e9158a1edced135cf3a91dfc9c38d9ce",
          "md5": "3ed6d803b97ffa987f82f0d63e5c0074"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-kotlin-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-kotlinx-datetime-6.0.0-LOCAL-PRE-sources.jar",
          "size": 5894,
          "sha512": "3c4de6915eb75ce5c779ab644be50368f319599a32a90792083f2b01924a992cab4482e49850a3a4e2594e20cc5e3743eb31b6d0689d44ea02917db3e172b86a",
          "sha256": "caa4b864e009f1f040b1bbb4a76f0a4ed698f5625cc56a93553bc5730cd63822",
          "sha1": "c35d27219f982a289125ae27434b952f613c7b43",
          "md5": "b5e5cf5e1e0de91477301be67a048bf5"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-iosarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-iosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-iosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-iosarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-iosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-iosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-iosarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-iosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-iosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-iossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-iossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-iossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-iossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-iossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-iossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-iossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-iossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-iossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-iosx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-iosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-iosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-iosx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-iosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-iosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-iosx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-iosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-iosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-js/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-js/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-js/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-jvm/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-jvm-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-jvm",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-jvm/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-jvm-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-jvm",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-jvm/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-jvm-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-jvm",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-linuxarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-linuxarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-linuxarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-linuxarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-linuxarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-linuxarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-linuxx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-linuxx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-linuxx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-linuxx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-linuxx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-linuxx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-macosarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-macosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-macosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-macosarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-macosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-macosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-macosarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-macosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-macosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-macosx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-macosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-macosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-macosx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-macosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-macosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-macosx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-macosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-macosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-mingwx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-mingwx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-mingwx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-mingwx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-mingwx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-mingwx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-tvosarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-tvosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-tvosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-tvosarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-tvosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-tvosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-tvosarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-tvosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-tvosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-tvossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-tvossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-tvossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-tvossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-tvossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-tvossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-tvossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-tvossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-tvossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-tvosx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-tvosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-tvosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-tvosx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-tvosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-tvosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-tvosx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-tvosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-tvosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-wasm-js/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-wasm-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-wasm-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-wasm-js/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-wasm-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-wasm-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-wasm-js/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-wasm-js-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-wasm-js",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-watchosarm32/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-watchosarm32-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-watchosarm32",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-watchosarm32/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-watchosarm32-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-watchosarm32",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-watchosarm32/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-watchosarm32-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-watchosarm32",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-watchosarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-watchosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-watchosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-watchosarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-watchosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-watchosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-watchosarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-watchosarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-watchosarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-watchossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-watchossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-watchossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-watchossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-watchossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-watchossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-watchossimulatorarm64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-watchossimulatorarm64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-watchossimulatorarm64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-watchosx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-watchosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-watchosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-watchosx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-watchosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-watchosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-kotlinx-datetime-watchosx64/6.0.0-LOCAL-PRE/kotest-assertions-kotlinx-datetime-watchosx64-6.0.0-LOCAL-PRE.module",
        "group": "io.kotest",
        "module": "kotest-assertions-kotlinx-datetime-watchosx64",
        "version": "6.0.0-LOCAL-PRE"
      }
    }
  ]
}
