{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.1.0+20241204",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20241204"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.0-1.0.29"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.0+20241204.jar",
          "url": "k2-2.1.0+20241204.jar",
          "size": 10771,
          "sha512": "b1457e6c33fb42d474badddd477eb35c47aa4dfda648b6aee9eb1225dec2c83e621909da7c64e4bab3ad978d32a193be53f71539232b986fc99080ef0d13cbe2",
          "sha256": "aabe6194c942de5d58ddf6e90d3ab37db7c4c549c4efb0ceda89bd695e920ad3",
          "sha1": "28bdbc2de0b4f05319662680a12ae3b82336c142",
          "md5": "0ddd3b781b801b550140c6f952a5b3cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20241204"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.0-1.0.29"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M1"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.0+20241204.jar",
          "url": "k2-2.1.0+20241204.jar",
          "size": 10771,
          "sha512": "b1457e6c33fb42d474badddd477eb35c47aa4dfda648b6aee9eb1225dec2c83e621909da7c64e4bab3ad978d32a193be53f71539232b986fc99080ef0d13cbe2",
          "sha256": "aabe6194c942de5d58ddf6e90d3ab37db7c4c549c4efb0ceda89bd695e920ad3",
          "sha1": "28bdbc2de0b4f05319662680a12ae3b82336c142",
          "md5": "0ddd3b781b801b550140c6f952a5b3cf"
        }
      ]
    }
  ]
}
