{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/0.0.1/kmpotest-0.0.1.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosSimulatorArm64Main-0.0.1.klib",
          "url": "kmpotest-watchossimulatorarm64-0.0.1.klib",
          "size": 38276,
          "sha512": "68dde07fc52a4107bdad9c8b7cd054c8f9e053b5290c1a896223dcf392f6a5da9052e0bbae56ef7fbbda537d2b502839fb9d1fe26317656f546ce3ed3c07b612",
          "sha256": "b177583974d245d21fdb7c4c88df7e2ea2f15d5846f1d838c58768f90a572d3e",
          "sha1": "89c0ddfa91f094764a8203a4096ac1244111ef83",
          "md5": "3a6c19d3c805f0905b058979a078a8bb"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-watchossimulatorarm64-0.0.1-sources.jar",
          "url": "kmpotest-watchossimulatorarm64-0.0.1-sources.jar",
          "size": 3982,
          "sha512": "cad967820e77fe89c50f77764fdb0d3a25c2347a200a2af4597d31cf7d9cca6a10a70692d625087fdcd22f628c86fe8fa21986912ccba4a4a2ebfff503edd80f",
          "sha256": "92531516c102a324d12904513c3847c9f941234c36a7b73d3101ec57654af903",
          "sha1": "43157be02a794a08788cec5c8f29ef44ed8f704b",
          "md5": "6af9320eb9e2aa8f598642cfa378acbc"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchossimulatorarm64-0.0.1-metadata.jar",
          "url": "kmpotest-watchossimulatorarm64-0.0.1-metadata.jar",
          "size": 261,
          "sha512": "dd06b5cf33d650b9af97146271ca1a6767acacd9ec92609cb58b8aec3fa5035364f933a52d60ce5c98136967454b814611f62cfd723d1f402ff46bb468886386",
          "sha256": "9343944a3e972171329d6cba02f7581aea926e3a0502d44494395f3b02c1be4f",
          "sha1": "29a5ccc38bf6cd1487730187ba2ed17e707216e0",
          "md5": "adadab6ca86ba612076933e09fc286e3"
        }
      ]
    }
  ]
}
