{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-core/0.6.3-K2.2.20-SNAPSHOT/testBalloon-framework-core-0.6.3-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-core",
    "version": "0.6.3-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-abstractions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-core-mingwX64Main-0.6.3-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-framework-core-mingwx64-0.6.3-K2.2.20-SNAPSHOT.klib",
          "size": 138361,
          "sha512": "8cd60570be125695ecdb464b271ccb8eb70af4a80d609087934d80267736bae384ea11eff303f7eef9f1e1b5f90e8ec5b03ebf8e05528611ef6db132e57b5944",
          "sha256": "1986590bfef1c8bcd0e91904de7f46851cc2111c580b21f85c9f18e86fff04dc",
          "sha1": "37164e2e7a72db2a946e1ecb85bf831d31e60849",
          "md5": "b5c98e55dd65825575a58361ff2b2cbd"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-framework-core-mingwx64-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-core-mingwx64-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "size": 34816,
          "sha512": "df10b18e845cf67e41ee7ebbe98638f9e3957ab38ffda931e68d8397e5fe7d66f782584265b5a28c6bb00013e032acb8c3c8b2986601465456c809caa311e438",
          "sha256": "58af33a24876bd7d8d4d803069f7122444c5ab77beed0d2f2b91131d300612e5",
          "sha1": "26bd26c13e5e85de90eda9004d774bcae10bdab9",
          "md5": "46e1e064c8e99bdc9080a42683fc2b59"
        }
      ]
    }
  ]
}
