{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250727/kmpotest-20250727.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250727",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosArm64Main-20250727.klib",
          "url": "kmpotest-watchosarm64-20250727.klib",
          "size": 39700,
          "sha512": "185c0807e0ef8399dad0d0a3cb519cfd664c21650c389d4ce2883f41a965baadf0e5b66de9e989f8e5bcc369155c410ab5b35f7f485057ffcf2dc553d0aa0b0c",
          "sha256": "a8536ef606039a9264098b04b7c74b72166f53ea9159b2152a62fd3a16afaa98",
          "sha1": "bcc537363677bd23aee041c4bea953e002bf452a",
          "md5": "85c5e9de4711ade42ee0a620f7b5d839"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-watchosarm64-20250727-sources.jar",
          "url": "kmpotest-watchosarm64-20250727-sources.jar",
          "size": 4340,
          "sha512": "469a7cfe157ec9a1265390c0d7a6723a963c54db5e3607916d0ccd3693db070fcb41ff8842d70d26671ba0d08b4219466344c29eb98bf7b9844066352aecf4a8",
          "sha256": "51361754bdcab17e98e5379617ab44b6ec911489478264b6bbd884fce5f9ad96",
          "sha1": "3c62683ddd2393127933ed992ca2112aa109f069",
          "md5": "53de685223b809172b41e1d28b2b35fa"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosarm64-20250727-metadata.jar",
          "url": "kmpotest-watchosarm64-20250727-metadata.jar",
          "size": 261,
          "sha512": "7d9558319d27a71e70e7bc1576543b3724856516cabc54944f051a2caa004e505d69e4f585b0e35875a63a252cce97ffb673d4f1eed298937e7d208afdb84bf0",
          "sha256": "1916f4af472e50ec6a46ca8843e21b2c6cd7e46ed78903d44f9173a09f59b21e",
          "sha1": "626f02b49cd4a58927795634da21d1eeedad7968",
          "md5": "2d28224cddf17cfed32eaa512718c084"
        }
      ]
    }
  ]
}
