{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250723+1/kmpotest-20250723+1.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250723+1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-tvosSimulatorArm64Main-20250723+1.klib",
          "url": "kmpotest-tvossimulatorarm64-20250723+1.klib",
          "size": 38249,
          "sha512": "ef65fa6c697eb6ea37769289fae35f500087ebdb016ca4e454b74563c7505e7ddad7de2c187fa89565cdcd910b52a4e223fca21ba5b782e482dadb4654646a76",
          "sha256": "0da1ddf81fe454428ab55cb141ff539537b62288ce390e328708f28e672fc3c6",
          "sha1": "bca4139866d84563d49f1261f2d8f45dc97ced3d",
          "md5": "fd67350f8afe8055c24075948bd4a2cc"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-tvossimulatorarm64-20250723+1-sources.jar",
          "url": "kmpotest-tvossimulatorarm64-20250723+1-sources.jar",
          "size": 3949,
          "sha512": "0a94bbd8401486ff558fa489db76d037db73020b3cc8ae34df8a40db8206574b305d0039a989ce7bfdf8e144973269364d5d6e4c1b6c68328df29414ec04a8d1",
          "sha256": "0982519d331f584f2638472516e9960a08fe056b1b7b826ba0cd7743fc4f60a3",
          "sha1": "fcc209adb9823d17439eedb6dfed89c0d8036f76",
          "md5": "b9f4ab3189d88acbb03ddf08e6cd77b6"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-tvossimulatorarm64-20250723+1-metadata.jar",
          "url": "kmpotest-tvossimulatorarm64-20250723+1-metadata.jar",
          "size": 261,
          "sha512": "a9a0fb031bd728908e8a747153faf2c78907802726c14c6c53eda0cf3f4dedac85e9355db4e87ee4035e91dc128fc88d6f4e69b2de24d9ae9e96ee6f8e4bb7d1",
          "sha256": "d2f8e6ec0da52ef36dd62260f1a0e7362827734b1d2d1644f47c40c9b36a27b5",
          "sha1": "621ae76dc46228b1ea88420010e8dc7efc1cfe0c",
          "md5": "26693c5e1053da3138eeadbff177f678"
        }
      ]
    }
  ]
}
