{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-release.aar",
          "url": "testballoon-shim-android-202509019.aar",
          "size": 24677,
          "sha512": "c6c92a32776416a8627d694c134ae8041ab8e49864e57028230c081cd68144c9ddba9c2ba90e8f6d85672c228e9204415882b6bfe37506a9241bddcc99f60b32",
          "sha256": "82e3d203cd02116c31a745ad73b24f8768045749a3ad8be17fe634d417e38ebd",
          "sha1": "b6f6d8c5f0d978b39e717d1b0679da5b075ef5e0",
          "md5": "d9265ed4be3990a516bef258db16c4f4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-release.aar",
          "url": "testballoon-shim-android-202509019.aar",
          "size": 24677,
          "sha512": "c6c92a32776416a8627d694c134ae8041ab8e49864e57028230c081cd68144c9ddba9c2ba90e8f6d85672c228e9204415882b6bfe37506a9241bddcc99f60b32",
          "sha256": "82e3d203cd02116c31a745ad73b24f8768045749a3ad8be17fe634d417e38ebd",
          "sha1": "b6f6d8c5f0d978b39e717d1b0679da5b075ef5e0",
          "md5": "d9265ed4be3990a516bef258db16c4f4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "testballoon-shim-android-202509019-sources.jar",
          "url": "testballoon-shim-android-202509019-sources.jar",
          "size": 3181,
          "sha512": "0a9bb8822c913ac8ed93117bf1575735786f9662f30acd1068a20d9c7a0065e3f327824a555523eb7106adb95a23b3e2d16795d8ee95b2be17c7af1d26768ade",
          "sha256": "596820e61f2072da40ed80844ebeb3afa309119886c3d3c858fb003ec414a9c6",
          "sha1": "4c4f76bd88e92071f5fcce70a20a5beb550f8d2b",
          "md5": "fac66adee902a1f17e977a6aa63d1578"
        }
      ]
    }
  ]
}
