{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-release.aar",
          "url": "testballoon-shim-android-202509019.aar",
          "size": 24470,
          "sha512": "e708a341f05960dc0de25253730d67a078bd73637dd010a1f67aba8a1bc632d7b1ec01050153110056b1d2f55429253c9dbda6062b778a9aca3fc1c5a7fe23eb",
          "sha256": "66e42cffdfa8b98955547a8d59a900fd5f046076c684cccc787785f1313268d8",
          "sha1": "b42292580e63eb6999dd5f3327c603a132781bd9",
          "md5": "9f8f4c5f7d90d851f095015db4421f5b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-release.aar",
          "url": "testballoon-shim-android-202509019.aar",
          "size": 24470,
          "sha512": "e708a341f05960dc0de25253730d67a078bd73637dd010a1f67aba8a1bc632d7b1ec01050153110056b1d2f55429253c9dbda6062b778a9aca3fc1c5a7fe23eb",
          "sha256": "66e42cffdfa8b98955547a8d59a900fd5f046076c684cccc787785f1313268d8",
          "sha1": "b42292580e63eb6999dd5f3327c603a132781bd9",
          "md5": "9f8f4c5f7d90d851f095015db4421f5b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "testballoon-shim-android-202509019-sources.jar",
          "url": "testballoon-shim-android-202509019-sources.jar",
          "size": 3039,
          "sha512": "dab29e0f3f6a1ed21d0685cab7304697cb4db063cc25a7a58976827e58bc79c41c883089a9d0ed821797d93a7559a8c555e122240df1a7bdc4b818582591d09b",
          "sha256": "9b0ef635742a07a2e612e819d31e224407d19d3359c8236499bdf6b09b463210",
          "sha1": "5b2f70c1cbb3c1830d18ac8fa6364032406da81a",
          "md5": "44ea9e5789bcbda55219cb2e2cb94544"
        }
      ]
    }
  ]
}
