{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-blocking-detection/0.6.2-K2.2.20-SNAPSHOT/testBalloon-integration-blocking-detection-0.6.2-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-blocking-detection",
    "version": "0.6.2-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-linuxX64Main-0.6.2-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-integration-blocking-detection-linuxx64-0.6.2-K2.2.20-SNAPSHOT.klib",
          "size": 5374,
          "sha512": "dcfeb26a3574f18cbd0ede467f8e2135d332a4d2ef0392752f99f31defc6aaac8c6607e0fdd072125aaf1498a1aa8ea4631d49e72b94c0cbe7a2e919b5820038",
          "sha256": "d47512c2fa855744efc8dcd1619159728a1926d0e7c0df0e3d4ba5d12f3da844",
          "sha1": "f7297ccdba6513cd39a487e24f293d9f12d03723",
          "md5": "b2f1bdd9f10004862516b37ec1e72cda"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-linuxx64-0.6.2-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-blocking-detection-linuxx64-0.6.2-K2.2.20-SNAPSHOT-sources.jar",
          "size": 2945,
          "sha512": "39e3fe2d09dea6d751c781c9d54c2842a097b0e2a250f1df01abef596da12daba9f9a32861f806a37955f2b86c658c90e0f6408a391dd83b23f3f0e98bce9450",
          "sha256": "dbafc44bb6acf30f004893b05f9105de88a0d9a62512048ce98f2a05fcdbb66c",
          "sha1": "18ff2f39110b3aef01c2c19e1a931081965bbd0a",
          "md5": "184265814655eb8c10190843abd92a1b"
        }
      ]
    }
  ]
}
