{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/0.0.1/kmpotest-0.0.1.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosArm32Main-0.0.1.klib",
          "url": "kmpotest-watchosarm32-0.0.1.klib",
          "size": 38195,
          "sha512": "04bba8c0558b56521291508896fddbc510a6ae39fb1c1a47e8918e8128b2f395faff4262f2f7b160aa2a7ba9f9d6c6519a3e25aab930992fb613ff6017cb5aaf",
          "sha256": "39136dd5baa13c0041039f1876ad0b262e6c045b9c419d7b6be1022eb5233370",
          "sha1": "1ca59f171c8b694a27b94fde5274277e54491e39",
          "md5": "d29c3065e61f099213839168b75c7665"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-watchosarm32-0.0.1-sources.jar",
          "url": "kmpotest-watchosarm32-0.0.1-sources.jar",
          "size": 3886,
          "sha512": "a6ec9538b8a722f2d0f47774cc5b9fbd5fcf02129d22c1e03ba7047061c3ec2e478bdc0168131c655fb536dc69935fd92986e8d615eda57ae4b7081407733cea",
          "sha256": "ee4582eb56c209e7e29e553c9da6bac272ad6891c040c75b2eeab7b4f76d8b1c",
          "sha1": "507431a6228b3a080f4e0799ea8545c4350519d6",
          "md5": "7b3f4dee141de6c719e7f69398f42ef2"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosarm32-0.0.1-metadata.jar",
          "url": "kmpotest-watchosarm32-0.0.1-metadata.jar",
          "size": 261,
          "sha512": "6f43a8be3ec6ee8c3279b89aa461909138b55817e4cd6ed8d77283b23b9038de00471d00b8b2f3c38017e1d6cc62ab37d6111b4757a2844bfdd4af75f4bc2afc",
          "sha256": "8b6cfcd8a89b0ed3787f1ded08816b1fbfdb1b225433b3fac6fd3e030970b566",
          "sha1": "6e130d912f3e34ba3ae3003a18da730d692dd0b5",
          "md5": "f94ace76507c1575cf061a70805d5946"
        }
      ]
    }
  ]
}
