{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251003",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-metadata-20251003.jar",
          "url": "testballoon-shim-20251003.jar",
          "size": 3994,
          "sha512": "8f26a120c8d0b0fabef75588d5ecf5b5f5fd4ebd7d4d039b05ed1a1a2f6c7e9681d8c83ebc769305febf4e6215d78acb6dfdec599a3a1f1699a74218ef364478",
          "sha256": "9b9fcc69f1e59c377023f539eab4d3625b9c669165a571ec6afef42feac9d775",
          "sha1": "c4bbb54b8f5bd64a5a121a6fd660842ff9d9e1e3",
          "md5": "24595e0b840e770a72ef3f6cb54277fd"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "testballoon-shim-kotlin-20251003-sources.jar",
          "url": "testballoon-shim-20251003-sources.jar",
          "size": 2405,
          "sha512": "04e19c0dba117bc0006c0bbbefad017818ba67ba693280d947036231d47fa8ce437f6c2c6feca33b6f2fe32b6cbb71593b88fe2282d39691722443b3ebf3d4c0",
          "sha256": "ae929e49f4c3ea56b15ece81bd8e5de22ec724ee5a46b89bddf4bcd7165f8f0c",
          "sha1": "5c158453afe42728619738a06b0c6c99c347b524",
          "md5": "5b8e87401699f5592440c344bdb5a373"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../testballoon-shim-android/20251003/testballoon-shim-android-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-android",
        "version": "20251003"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../testballoon-shim-android/20251003/testballoon-shim-android-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-android",
        "version": "20251003"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../testballoon-shim-android/20251003/testballoon-shim-android-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-android",
        "version": "20251003"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-androidnativearm32/20251003/testballoon-shim-androidnativearm32-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-androidnativearm32",
        "version": "20251003"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-androidnativearm32/20251003/testballoon-shim-androidnativearm32-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-androidnativearm32",
        "version": "20251003"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-androidnativearm64/20251003/testballoon-shim-androidnativearm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-androidnativearm64",
        "version": "20251003"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-androidnativearm64/20251003/testballoon-shim-androidnativearm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-androidnativearm64",
        "version": "20251003"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-androidnativex64/20251003/testballoon-shim-androidnativex64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-androidnativex64",
        "version": "20251003"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-androidnativex64/20251003/testballoon-shim-androidnativex64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-androidnativex64",
        "version": "20251003"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-androidnativex86/20251003/testballoon-shim-androidnativex86-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-androidnativex86",
        "version": "20251003"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-androidnativex86/20251003/testballoon-shim-androidnativex86-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-androidnativex86",
        "version": "20251003"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-iosarm64/20251003/testballoon-shim-iosarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-iosarm64",
        "version": "20251003"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-iosarm64/20251003/testballoon-shim-iosarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-iosarm64",
        "version": "20251003"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-iosarm64/20251003/testballoon-shim-iosarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-iosarm64",
        "version": "20251003"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-iossimulatorarm64/20251003/testballoon-shim-iossimulatorarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-iossimulatorarm64",
        "version": "20251003"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-iossimulatorarm64/20251003/testballoon-shim-iossimulatorarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-iossimulatorarm64",
        "version": "20251003"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-iossimulatorarm64/20251003/testballoon-shim-iossimulatorarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-iossimulatorarm64",
        "version": "20251003"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-iosx64/20251003/testballoon-shim-iosx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-iosx64",
        "version": "20251003"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-iosx64/20251003/testballoon-shim-iosx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-iosx64",
        "version": "20251003"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-iosx64/20251003/testballoon-shim-iosx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-iosx64",
        "version": "20251003"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../testballoon-shim-js/20251003/testballoon-shim-js-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-js",
        "version": "20251003"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../testballoon-shim-js/20251003/testballoon-shim-js-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-js",
        "version": "20251003"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../testballoon-shim-js/20251003/testballoon-shim-js-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-js",
        "version": "20251003"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../testballoon-shim-jvm/20251003/testballoon-shim-jvm-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-jvm",
        "version": "20251003"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../testballoon-shim-jvm/20251003/testballoon-shim-jvm-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-jvm",
        "version": "20251003"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../testballoon-shim-jvm/20251003/testballoon-shim-jvm-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-jvm",
        "version": "20251003"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-linuxarm64/20251003/testballoon-shim-linuxarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-linuxarm64",
        "version": "20251003"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-linuxarm64/20251003/testballoon-shim-linuxarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-linuxarm64",
        "version": "20251003"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-linuxx64/20251003/testballoon-shim-linuxx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-linuxx64",
        "version": "20251003"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-linuxx64/20251003/testballoon-shim-linuxx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-linuxx64",
        "version": "20251003"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-macosarm64/20251003/testballoon-shim-macosarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-macosarm64",
        "version": "20251003"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-macosarm64/20251003/testballoon-shim-macosarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-macosarm64",
        "version": "20251003"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-macosarm64/20251003/testballoon-shim-macosarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-macosarm64",
        "version": "20251003"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-macosx64/20251003/testballoon-shim-macosx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-macosx64",
        "version": "20251003"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-macosx64/20251003/testballoon-shim-macosx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-macosx64",
        "version": "20251003"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-macosx64/20251003/testballoon-shim-macosx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-macosx64",
        "version": "20251003"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-mingwx64/20251003/testballoon-shim-mingwx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-mingwx64",
        "version": "20251003"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-mingwx64/20251003/testballoon-shim-mingwx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-mingwx64",
        "version": "20251003"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-tvosarm64/20251003/testballoon-shim-tvosarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-tvosarm64",
        "version": "20251003"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-tvosarm64/20251003/testballoon-shim-tvosarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-tvosarm64",
        "version": "20251003"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-tvosarm64/20251003/testballoon-shim-tvosarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-tvosarm64",
        "version": "20251003"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-tvossimulatorarm64/20251003/testballoon-shim-tvossimulatorarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-tvossimulatorarm64",
        "version": "20251003"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-tvossimulatorarm64/20251003/testballoon-shim-tvossimulatorarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-tvossimulatorarm64",
        "version": "20251003"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-tvossimulatorarm64/20251003/testballoon-shim-tvossimulatorarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-tvossimulatorarm64",
        "version": "20251003"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-tvosx64/20251003/testballoon-shim-tvosx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-tvosx64",
        "version": "20251003"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-tvosx64/20251003/testballoon-shim-tvosx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-tvosx64",
        "version": "20251003"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-tvosx64/20251003/testballoon-shim-tvosx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-tvosx64",
        "version": "20251003"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../testballoon-shim-wasm-js/20251003/testballoon-shim-wasm-js-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-wasm-js",
        "version": "20251003"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../testballoon-shim-wasm-js/20251003/testballoon-shim-wasm-js-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-wasm-js",
        "version": "20251003"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../testballoon-shim-wasm-js/20251003/testballoon-shim-wasm-js-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-wasm-js",
        "version": "20251003"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchosarm32/20251003/testballoon-shim-watchosarm32-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchosarm32",
        "version": "20251003"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchosarm32/20251003/testballoon-shim-watchosarm32-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchosarm32",
        "version": "20251003"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchosarm32/20251003/testballoon-shim-watchosarm32-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchosarm32",
        "version": "20251003"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchosarm64/20251003/testballoon-shim-watchosarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchosarm64",
        "version": "20251003"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchosarm64/20251003/testballoon-shim-watchosarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchosarm64",
        "version": "20251003"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchosarm64/20251003/testballoon-shim-watchosarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchosarm64",
        "version": "20251003"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchosdevicearm64/20251003/testballoon-shim-watchosdevicearm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchosdevicearm64",
        "version": "20251003"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchosdevicearm64/20251003/testballoon-shim-watchosdevicearm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchosdevicearm64",
        "version": "20251003"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchosdevicearm64/20251003/testballoon-shim-watchosdevicearm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchosdevicearm64",
        "version": "20251003"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchossimulatorarm64/20251003/testballoon-shim-watchossimulatorarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchossimulatorarm64",
        "version": "20251003"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchossimulatorarm64/20251003/testballoon-shim-watchossimulatorarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchossimulatorarm64",
        "version": "20251003"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchossimulatorarm64/20251003/testballoon-shim-watchossimulatorarm64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchossimulatorarm64",
        "version": "20251003"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchosx64/20251003/testballoon-shim-watchosx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchosx64",
        "version": "20251003"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchosx64/20251003/testballoon-shim-watchosx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchosx64",
        "version": "20251003"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../testballoon-shim-watchosx64/20251003/testballoon-shim-watchosx64-20251003.module",
        "group": "at.asitplus.gradle",
        "module": "testballoon-shim-watchosx64",
        "version": "20251003"
      }
    }
  ]
}
