{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "legacy",
    "version": "1.9.10+20240717",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.10-1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-1.9.10+20240717.jar",
          "url": "legacy-1.9.10+20240717.jar",
          "size": 147809,
          "sha512": "83d0f8747afd292b587672b7611cc0583ef0d642b965ad965e03224cec8e578f11d1930c04e64440fd8eb71b0f4528c361af05d720820cdc1082fe8735dccac3",
          "sha256": "e47cf7bf50e856c66a8bd17df736705d2cd1e0e0f1186b00409a08ce6d525349",
          "sha1": "206ef4436e1f890809aa8d5ecd217d057fbe2894",
          "md5": "0b7e1cdab929d9ccec7afc985b88721b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.10-1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-1.9.10+20240717.jar",
          "url": "legacy-1.9.10+20240717.jar",
          "size": 147809,
          "sha512": "83d0f8747afd292b587672b7611cc0583ef0d642b965ad965e03224cec8e578f11d1930c04e64440fd8eb71b0f4528c361af05d720820cdc1082fe8735dccac3",
          "sha256": "e47cf7bf50e856c66a8bd17df736705d2cd1e0e0f1186b00409a08ce6d525349",
          "sha1": "206ef4436e1f890809aa8d5ecd217d057fbe2894",
          "md5": "0b7e1cdab929d9ccec7afc985b88721b"
        }
      ]
    }
  ]
}
