{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250729/kmpotest-20250729.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250729",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosArm32Main-20250729.klib",
          "url": "kmpotest-watchosarm32-20250729.klib",
          "size": 39699,
          "sha512": "ccf4ab5907cac3766cae0c8793ff0a498dc0b3e67df2cd638d8f4babcaaff4898a51c33e917fb5de676ccbe7a85ee13b492311bd999864c91ebe8fb37b406619",
          "sha256": "5d04376a167f153afa1c088312cd4dae27de26e181487099e212ebe23be6d507",
          "sha1": "96c8abaaa70dd5fb8e655dd16040cc15b9dde21d",
          "md5": "bd1c8db2714e08296064a212147df00d"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-watchosarm32-20250729-sources.jar",
          "url": "kmpotest-watchosarm32-20250729-sources.jar",
          "size": 4340,
          "sha512": "caa3132543f44a4cc4a7d21991ec85b00b73bd381e57959a46b001a9eeff8d7e8a356497443ddace12b28b3009834c78d60e8c2b25cc68c1115a2796d45e9149",
          "sha256": "b2edda31e96dbe9971141fbe1b026b6fb1958427eb67388d424740ffa96098b0",
          "sha1": "5dee5f94a3dd8a483496c4d61b01803a84103067",
          "md5": "1a34c275f040e641ce7c0800e673f60c"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosarm32-20250729-metadata.jar",
          "url": "kmpotest-watchosarm32-20250729-metadata.jar",
          "size": 261,
          "sha512": "e5104d907b09200b4ecfe1c04283fc767179f33585ed365c1877ae5034e21c256a43967ea373a164c6a07549656c8bc8ac8d3f43a1940dd4eca89a3268c88ad7",
          "sha256": "cb998315dfd991ac7f7f6c6ba720f622b2d8d93a3a64329cf1d03488846733d3",
          "sha1": "e0e733f313d2fe4b3275741dbc475112d963c221",
          "md5": "874d3135f6ad09c41f078e66dbb0fa9c"
        }
      ]
    }
  ]
}
