{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "20251108",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-20251108.jar",
          "url": "k2-20251108.jar",
          "size": 183536,
          "sha512": "645a884f5ae542bf9cd1be3d79606b60115ced51f1ecf6120eef17c27ee36678686281d30083c58372a4c6683907e41bf7d49b278320487e911ed320d61cda44",
          "sha256": "0f6277bf93655d6bf75cf05a7ee059556db9514efd326a68f898694d251477a4",
          "sha1": "49bb052c981d63dc34fb3cff6d60d30793266362",
          "md5": "434555a0612dd8793ead0589a158f064"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-20251108.jar",
          "url": "k2-20251108.jar",
          "size": 183536,
          "sha512": "645a884f5ae542bf9cd1be3d79606b60115ced51f1ecf6120eef17c27ee36678686281d30083c58372a4c6683907e41bf7d49b278320487e911ed320d61cda44",
          "sha256": "0f6277bf93655d6bf75cf05a7ee059556db9514efd326a68f898694d251477a4",
          "sha1": "49bb052c981d63dc34fb3cff6d60d30793266362",
          "md5": "434555a0612dd8793ead0589a158f064"
        }
      ]
    }
  ]
}
