{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "conventions",
    "version": "1.8.21+20230622",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "conventions-1.8.21+20230622.jar",
          "url": "conventions-1.8.21+20230622.jar",
          "size": 84917,
          "sha512": "c279e7c1c453a919a0049d8038c7474045e01a448b08c3ca9f98d4881dc1dbd9755791083b23f13f5f267b17908b6f7b5d9c827fce195912a1db2dc0883ec4ee",
          "sha256": "4eb6f421876d57575c7d56f025bb33c317f17ac78177391724ae5db8457e5825",
          "sha1": "014b748ab00e8e5d01439a29059e74ce52d799ee",
          "md5": "bfe15d80c70f9ea5c5e5e4e02c025f0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "conventions-1.8.21+20230622.jar",
          "url": "conventions-1.8.21+20230622.jar",
          "size": 84917,
          "sha512": "c279e7c1c453a919a0049d8038c7474045e01a448b08c3ca9f98d4881dc1dbd9755791083b23f13f5f267b17908b6f7b5d9c827fce195912a1db2dc0883ec4ee",
          "sha256": "4eb6f421876d57575c7d56f025bb33c317f17ac78177391724ae5db8457e5825",
          "sha1": "014b748ab00e8e5d01439a29059e74ce52d799ee",
          "md5": "bfe15d80c70f9ea5c5e5e4e02c025f0f"
        }
      ]
    }
  ]
}
