{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-arrow/6.0.0-LOCAL/kotest-assertions-arrow-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-assertions-arrow",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-assertions-arrow-jvm-6.0.0-LOCAL.jar",
          "size": 26739,
          "sha512": "4f4aa749cfffa034d545052022f275a8e1864a39880e3ca1657751b1ce2dfd56ee4688a6d56a3a4ee342165e84ba292ef72e9dea8db6e926044db361053bd310",
          "sha256": "67120d0e4207b4bb8ac6baa83b335af80044dcb2a2578e85f408c28a3da47742",
          "sha1": "7194fdc5c8c12dadd8ebb482189a8b5facecfd7b",
          "md5": "88084619db0f45fe8558f1d12c54933e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-assertions-arrow-jvm-6.0.0-LOCAL.jar",
          "size": 26739,
          "sha512": "4f4aa749cfffa034d545052022f275a8e1864a39880e3ca1657751b1ce2dfd56ee4688a6d56a3a4ee342165e84ba292ef72e9dea8db6e926044db361053bd310",
          "sha256": "67120d0e4207b4bb8ac6baa83b335af80044dcb2a2578e85f408c28a3da47742",
          "sha1": "7194fdc5c8c12dadd8ebb482189a8b5facecfd7b",
          "md5": "88084619db0f45fe8558f1d12c54933e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-assertions-arrow-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-arrow-jvm-6.0.0-LOCAL-sources.jar",
          "size": 5886,
          "sha512": "47f310168f28a95b4891a58033e2d2f033c378cf1df484945f61e2246699c7a28d7f88b3ac756dec60b4eeeed90896f4320c7b8b11887ff1f20e5dbc5eb6f376",
          "sha256": "c79bc48d7979091cdee82371143e7d9d6aee6075362a6cac7928162e416fce25",
          "sha1": "4326d6be6dea17da849809ee10b7d03f17366b05",
          "md5": "1b8fe5fcd85a859b5d4532f68c7d1e4f"
        }
      ]
    }
  ]
}
