{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/20251017/testballoon-shim-20251017.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-linuxArm64Main-20251017.klib",
          "url": "testballoon-shim-linuxarm64-20251017.klib",
          "size": 17968,
          "sha512": "8ff1836b781a9f5c01b74b858b75346469e6d39189c5d3f963e710bfba0019135a8e85c85bafe3b20190d4958b998b5a56acee9d8335a7127dbd6fa1b9d9401f",
          "sha256": "be973fe8b6abca40946c7890c4d26af3e78f3b951d9daf0eb77a15609b9e282f",
          "sha1": "0c6390795b3aad917d70e1320cc8134c53c8b44b",
          "md5": "7c21644b515e7363d440c6d9f0323924"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-linuxarm64-20251017-sources.jar",
          "url": "testballoon-shim-linuxarm64-20251017-sources.jar",
          "size": 3152,
          "sha512": "ffee194380732ec52966857202163af86effb22841d3af68c5e6e1a48b25460144a35accad38addbb940ec659e99cd0ab7d18f2c088ea66cc2876d7da991e8da",
          "sha256": "9a5d30210c625efea37e8be4afb0b1e751dc1be538276fefb9ed845d0aa3c174",
          "sha1": "ad0a24491b22d93ae8b4174198a2279705c15c68",
          "md5": "71247fa0ad76327e326adf8891c98c3c"
        }
      ]
    }
  ]
}
