{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251114/testhelper-20251114.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-androidNativeX86Main-20251114.klib",
          "url": "testhelper-androidnativex86-20251114.klib",
          "size": 6093,
          "sha512": "e6ca56fb96d2a88daf1583ba2a4ec845b7c512b52e27be6c3019d28ef065c82943727a44bd012d06aeee27cdff5a84c9716817deda1e8ede8a253838f70fd748",
          "sha256": "4f48be6e4a247fb6cd739948a0532202fe479eaf6e10de83e07305667eecd921",
          "sha1": "2f294c33c98649fd9c0c31fb8639cf684e2d0bea",
          "md5": "dbb50f53613f4549b44af0b03b650561"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-androidnativex86-20251114-sources.jar",
          "url": "testhelper-androidnativex86-20251114-sources.jar",
          "size": 1965,
          "sha512": "796367baa86177b36796d35f56b9a87504ea49e069b19e58cb04d962041badbe6e643e933e62dc0aa61cb56f9ea3159e6c34d7e4bf3bd742cc223f82302ff164",
          "sha256": "e4a5bf69cd3fed96df1b2b6a9b4bd19e145f4547c83a2598f9f7eb67f4e34d6f",
          "sha1": "3e3dc07b82dc71f138389519d47e4d1447ed1334",
          "md5": "5e6e3498c3a7bcb08725073f71e33d5e"
        }
      ]
    }
  ]
}
