{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250715-SNAPSHOT/kmpotest-20250715-SNAPSHOT.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250715-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosX64Main-20250715-SNAPSHOT.klib",
          "url": "kmpotest-watchosx64-20250715-SNAPSHOT.klib",
          "size": 38191,
          "sha512": "5bec8837cddddbf80743d5073df42d62559af5faa59e3380dab46c1ac9671f377ea8b0c9996d02a1d8d2a3dbd07e92c97370017f88b5b3f443eface94e8640d4",
          "sha256": "60b7e239d152c44f804c50b834369b5dd63b77677c72dc7865d25871e0f2efee",
          "sha1": "8d4f543d58c664d85d0865957bfe412ba719bce6",
          "md5": "eba6123e526ba2044994885faa74686a"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-watchosx64-20250715-SNAPSHOT-sources.jar",
          "url": "kmpotest-watchosx64-20250715-SNAPSHOT-sources.jar",
          "size": 4488,
          "sha512": "40aaaac11b083ef2b176dbe47040c083d280657105f419aa269eab1a214535538fa3300704deff0058adf22759aa83d814fcd749f7f931dc2be08441397b04a3",
          "sha256": "04f71f528fe5549eb2a2af92c549efdfda596e8e3e7f29f882cee120f9197b3e",
          "sha1": "a58e2241951f15ab81a67f5ef705d7777e1197bc",
          "md5": "4cfc52557bc71914532e545f2f5720ad"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosx64-20250715-SNAPSHOT-metadata.jar",
          "url": "kmpotest-watchosx64-20250715-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4c6aed76434d3f0323769a26dc38bce8a9bd77bec24d08966cdc8c7344092bcf67b0b7b754d851213ca1c62f2fd800d23f689ec50c245b4eee19869e08c71727",
          "sha256": "4d8c7d68aa97e2a4607d89851b2b9c3c1b1e3983e1a0fdad7464da30c4d54b37",
          "sha1": "e2f8d757c366b1bae6d5357b05a548c995959967",
          "md5": "576caa53b0ba0f0d6b95a03eb871f68e"
        }
      ]
    }
  ]
}
