{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "legacy",
    "version": "1.9.10+20240919",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.10-1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-1.9.10+20240919.jar",
          "url": "legacy-1.9.10+20240919.jar",
          "size": 149472,
          "sha512": "e44d108bed301607349b6918788481a0b6599047958f80120c91de7a5313c9e5120ed41ad299eda1cbc2874685a6b03a654db4eafd3b587115e4ff7854b4bb4c",
          "sha256": "454e78fd1bceb291b5701ba6359b9475c7033c6e919a5e03fd99d4858fb06e36",
          "sha1": "610a53087b6ae619e5ba05e4f1a87a75ac52f0dd",
          "md5": "337888d937fa150da3f1ceec377f6444"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.10-1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-1.9.10+20240919.jar",
          "url": "legacy-1.9.10+20240919.jar",
          "size": 149472,
          "sha512": "e44d108bed301607349b6918788481a0b6599047958f80120c91de7a5313c9e5120ed41ad299eda1cbc2874685a6b03a654db4eafd3b587115e4ff7854b4bb4c",
          "sha256": "454e78fd1bceb291b5701ba6359b9475c7033c6e919a5e03fd99d4858fb06e36",
          "sha1": "610a53087b6ae619e5ba05e4f1a87a75ac52f0dd",
          "md5": "337888d937fa150da3f1ceec377f6444"
        }
      ]
    }
  ]
}
