{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.1.20-199+20250314",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20-199"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.1.20-199"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.20-199+20250314.jar",
          "url": "k2-2.1.20-199+20250314.jar",
          "size": 161567,
          "sha512": "c04e5118af66ea99cc7c6fae4c528127f8a740fc60b04e239a67a0f474aea9136060fc350ee7b9c1cfc28ba7b740d677e16ddea739fe5aa68d5335545863ad27",
          "sha256": "1c87ab1a9a04169268c6580064e931a43fce3ee91b384c6f1b6c485773a1c0dd",
          "sha1": "1a8b8b93f7cf621de8e90e0c02dd1239e5101a3d",
          "md5": "cc329b78d8ab6fc008ad09a4054a8c31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20-199"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.1.20-199"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.20-199+20250314.jar",
          "url": "k2-2.1.20-199+20250314.jar",
          "size": 161567,
          "sha512": "c04e5118af66ea99cc7c6fae4c528127f8a740fc60b04e239a67a0f474aea9136060fc350ee7b9c1cfc28ba7b740d677e16ddea739fe5aa68d5335545863ad27",
          "sha256": "1c87ab1a9a04169268c6580064e931a43fce3ee91b384c6f1b6c485773a1c0dd",
          "sha1": "1a8b8b93f7cf621de8e90e0c02dd1239e5101a3d",
          "md5": "cc329b78d8ab6fc008ad09a4054a8c31"
        }
      ]
    }
  ]
}
