{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-property-arrow/6.0.0-LOCAL/kotest-property-arrow-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-property-arrow",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-optics",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-functions",
          "version": {
            "requires": "2.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-arrow-watchosArm64Main-6.0.0-LOCAL.klib",
          "url": "kotest-property-arrow-watchosarm64-6.0.0-LOCAL.klib",
          "size": 22683,
          "sha512": "f2610aba0f7287856340a7fbe11a957703f3e63c07c93e37eaac39d0a8a0268ffb1cc59e6035e1a2042220304212454fa9942dd6acea7e1fa2457465608ec7d5",
          "sha256": "62469408165a6afc9faaffb8961747ce5e064512a682cca9c002ead4676488f9",
          "sha1": "2a9de82fd39f0a9390d32b59cb2dcb8e9b91a840",
          "md5": "4b035380954b476f7a7bcd74b6029531"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-property-arrow-watchosarm64-6.0.0-LOCAL-sources.jar",
          "url": "kotest-property-arrow-watchosarm64-6.0.0-LOCAL-sources.jar",
          "size": 5869,
          "sha512": "01f2332f8fea760472bb4d9f2bb4f81ab3f3b16c43dc8072b40dfbe961e012ed461c69ea1937149f93305e5760994280d12babb4370643bfa618bc597f293ad8",
          "sha256": "946d2d763280f02406abe7958afbb3f815ee3b18ee5ec78b5be170aa853a4589",
          "sha1": "c50319cf0fedf615e37bf79dccde5b9ed1c5cdc6",
          "md5": "1f4faa4bf55fcdb1f135020333f718e6"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-optics",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-functions",
          "version": {
            "requires": "2.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-arrow-watchosarm64-6.0.0-LOCAL-metadata.jar",
          "url": "kotest-property-arrow-watchosarm64-6.0.0-LOCAL-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
