{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-kotlinx-datetime/6.0.0-LOCAL/kotest-assertions-kotlinx-datetime-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-assertions-kotlinx-datetime",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-assertions-kotlinx-datetime-jvm-6.0.0-LOCAL.jar",
          "size": 37493,
          "sha512": "e03ed03f2e2b78caf8b4f7ad5bb2accd45821d28db2b56263738cccb6398535e3ee7639957678894bbe8de8199d4579118fc221b328073a203fb1a2c7d5c53ea",
          "sha256": "31e5be2cba371d689589c5392f8b997612076277a616d493165043a53b43222c",
          "sha1": "b4d80dabda9bd89123f2302880c93bdfdb1e0afe",
          "md5": "8940ebf7a915d4cf99a5e16c93c4cf83"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-assertions-kotlinx-datetime-jvm-6.0.0-LOCAL.jar",
          "size": 37493,
          "sha512": "e03ed03f2e2b78caf8b4f7ad5bb2accd45821d28db2b56263738cccb6398535e3ee7639957678894bbe8de8199d4579118fc221b328073a203fb1a2c7d5c53ea",
          "sha256": "31e5be2cba371d689589c5392f8b997612076277a616d493165043a53b43222c",
          "sha1": "b4d80dabda9bd89123f2302880c93bdfdb1e0afe",
          "md5": "8940ebf7a915d4cf99a5e16c93c4cf83"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-assertions-kotlinx-datetime-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-kotlinx-datetime-jvm-6.0.0-LOCAL-sources.jar",
          "size": 5894,
          "sha512": "3c4de6915eb75ce5c779ab644be50368f319599a32a90792083f2b01924a992cab4482e49850a3a4e2594e20cc5e3743eb31b6d0689d44ea02917db3e172b86a",
          "sha256": "caa4b864e009f1f040b1bbb4a76f0a4ed698f5625cc56a93553bc5730cd63822",
          "sha1": "c35d27219f982a289125ae27434b952f613c7b43",
          "md5": "b5e5cf5e1e0de91477301be67a048bf5"
        }
      ]
    }
  ]
}
