{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-blocking-detection/0.6.3-K2.2.20-SNAPSHOT/testBalloon-integration-blocking-detection-0.6.3-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-blocking-detection",
    "version": "0.6.3-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-jvm-0.6.3-K2.2.20-SNAPSHOT.jar",
          "url": "testBalloon-integration-blocking-detection-jvm-0.6.3-K2.2.20-SNAPSHOT.jar",
          "size": 13194,
          "sha512": "31bc45c0c3996e72242da271dae2a2df0ce7e5c7f34df28b06714a6493327d8b4a0cd1bcb6db5830e0a49a0c443a7aa8e917cb8f8edb6a82286b87bea2386f4d",
          "sha256": "18158dd2f23b446408e4f2280419973fd56f62adf1065c1103224ef4c034e855",
          "sha1": "63ac3eaf6c63eb5f4418069330fa8492354c92a0",
          "md5": "9341d5b7d3bdc5a767b5701e2a1c8978"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.projectreactor.tools",
          "module": "blockhound",
          "version": {
            "requires": "1.0.14.RELEASE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-debug",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-jvm-0.6.3-K2.2.20-SNAPSHOT.jar",
          "url": "testBalloon-integration-blocking-detection-jvm-0.6.3-K2.2.20-SNAPSHOT.jar",
          "size": 13194,
          "sha512": "31bc45c0c3996e72242da271dae2a2df0ce7e5c7f34df28b06714a6493327d8b4a0cd1bcb6db5830e0a49a0c443a7aa8e917cb8f8edb6a82286b87bea2386f4d",
          "sha256": "18158dd2f23b446408e4f2280419973fd56f62adf1065c1103224ef4c034e855",
          "sha1": "63ac3eaf6c63eb5f4418069330fa8492354c92a0",
          "md5": "9341d5b7d3bdc5a767b5701e2a1c8978"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-jvm-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-blocking-detection-jvm-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "size": 3716,
          "sha512": "33cc169763744ca1581e124f12ba13a6572b8dfbb3b1007f3d48c588084e4dfe70a3e0574372859cb704bdf1d3b458a21a73076466baa9907724b033f32451d8",
          "sha256": "52df007362474dac39189121730034d2098173d0bf25bca1e44092a6bbee90e3",
          "sha1": "aaeebda46fccc738f2728e7f1e6b2a2f27fc5e23",
          "md5": "29246d7c12fdd4c43d8834c88c5409c2"
        }
      ]
    }
  ]
}
