{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-abstractions/0.6.3-K2.2.20-SNAPSHOT/testBalloon-framework-abstractions-0.6.3-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-abstractions",
    "version": "0.6.3-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-abstractions-mingwX64Main-0.6.3-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-framework-abstractions-mingwx64-0.6.3-K2.2.20-SNAPSHOT.klib",
          "size": 14994,
          "sha512": "8b83ee165c2c803237832d0d80a63c11ba303317b0769178eb65e571874600272ecd25bd2ecf3c3a9af40338863ec65868da61520e01a5b2ef812bfebd573db7",
          "sha256": "ce4003dc5a5d222abc543c88e74a676a45f8cc4f5e3d16c538f3f574878b1977",
          "sha1": "13ff427bc5010765d0f7d71af9ebbbd965bf8931",
          "md5": "af4a2674e43a403ae486018097d9536a"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-framework-abstractions-mingwx64-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-abstractions-mingwx64-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "size": 4561,
          "sha512": "1625b7ea3d45e1bd5b355a254ed37e3890ab1b9494577f85cd30a85f0d86992d952b22539a50dc873e54df06232babbc88f852580cdd965e1d4a7a0f9a7fa9c1",
          "sha256": "3c89768eeb8c755715c538dfea3beeb35eb677f8719f69fbfda9a52d6dc6b965",
          "sha1": "9951d068e7ad5536413de9eb38e876943b2f5c24",
          "md5": "5f36a0aa3fb3b1ad89f0898bdf1e5a6a"
        }
      ]
    }
  ]
}
