{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-framework-engine/6.0.0-LOCAL/kotest-framework-engine-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-framework-engine",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-mingwX64Main-6.0.0-LOCAL.klib",
          "url": "kotest-framework-engine-mingwx64-6.0.0-LOCAL.klib",
          "size": 895683,
          "sha512": "de2c384396baa8477e57596dc32aea1e72ee06903e02e284ae10d1e826ba9afd105aa81fb56f96fe6d2965cff8cedc6c7905bec9313baab6c7a967deb50abc22",
          "sha256": "595c351f7349b2dfc5a16b0252e7b250fe1818da7e0ab123ea26f44dc0f11bd1",
          "sha1": "c1e6a86543f306ffa3c19987c17375ec2dfe5c1f",
          "md5": "389d57d7e27b793e36be61bbedda0daa"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-framework-engine-mingwx64-6.0.0-LOCAL-sources.jar",
          "url": "kotest-framework-engine-mingwx64-6.0.0-LOCAL-sources.jar",
          "size": 254969,
          "sha512": "cdf9587afa2d40784945c92b6758498cd02029e8d9480c556fd931c602a69e4f99c5e2dc5c74297aca1e9c60bccd3e37474de47103db922067f053be0b6d0196",
          "sha256": "e5b07c38a7046a37355c93366c418aa2c4cc2fc59590893596f4f04215b35266",
          "sha1": "227ab836a9feffbbe0580cd6e43c2f5123adb859",
          "md5": "d6b5bb8d0e176cc07a7c33478c74625c"
        }
      ]
    }
  ]
}
