{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251114/testhelper-20251114.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-mingwX64Main-20251114.klib",
          "url": "testhelper-mingwx64-20251114.klib",
          "size": 6071,
          "sha512": "574099bf1265d0a2faf3520ab3dbb7c0022de33a8cd686beb5982794df65846b52be6cbf1180b81e6ae6f665d37c3b66b2664b0976deabb64256c727f891fa68",
          "sha256": "cecec2f4968da7250b36d2b548a5cc4863d13fbd09ce97e7d53fa7918f0b2182",
          "sha1": "6881a2dda8527a4b567a740e5d3a81692c5a7ce3",
          "md5": "f77257aea46db3f34a5617c1914ec6e0"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-mingwx64-20251114-sources.jar",
          "url": "testhelper-mingwx64-20251114-sources.jar",
          "size": 1880,
          "sha512": "5d9701237ce1b37154cc957653502a77c205a065b0d5080f0ec0e7a6e4ebc2541cfcf0f25338845c579118e7610bd647b3e5ea4d5434681dccaa6ba99e7cd884",
          "sha256": "062600fed4de5b8d8b7fbde396870b22d5aff977e3690b33f0b5c91ebf032e41",
          "sha1": "fb0d4e95d2e6ad13daa7a0bcd6ac62b1c83ebc7a",
          "md5": "9fa446f66915a8b9300c0e633429f53b"
        }
      ]
    }
  ]
}
