{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251114/testhelper-20251114.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-linuxArm64Main-20251114.klib",
          "url": "testhelper-linuxarm64-20251114.klib",
          "size": 6088,
          "sha512": "6117344efe53f5bc63c44e59f8d773e6fc04b087de2d46660eea3d1cfffe139a7c78cc069cb6d4483894b40450d47885424756d019af9ae620789913f939de7a",
          "sha256": "cab847e6701e3ca08aaa8f64f401d2823843975c05c211926e5f803cae9b27cf",
          "sha1": "7b1a41a803ef48dfa9dff1647daab94a20bca374",
          "md5": "d889544e58f133ace41ad9e7e96ed9a7"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-linuxarm64-20251114-sources.jar",
          "url": "testhelper-linuxarm64-20251114-sources.jar",
          "size": 1904,
          "sha512": "f61f033f4f23116f86dd1aaef93dd10fe51a14c468256b5c334cbd7f6dffcc907b2d36f1cbcb0f4a43593631b839915f24b7e6f53b1864c1f7ecdb0044b4124d",
          "sha256": "53ceecef418f2077fa399231763ca2b19d9e3ef124ce818574a42af982e1e5e0",
          "sha1": "ac61e49a6cc7e5839b176e50a9256cb5a9b19bb2",
          "md5": "13dc39b54097b198acc92fe75ba7da78"
        }
      ]
    }
  ]
}
