{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-property",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-metadata-6.0.0-LOCAL.jar",
          "url": "kotest-property-6.0.0-LOCAL.jar",
          "size": 83268,
          "sha512": "3dfc587f3dced8c6e6ca3f661a51b117421db384e83c35919bbf4e1cef2c23593c654120710a4ae0d5dae3c1553be13686c41d565dcd217b8489af283081dc4c",
          "sha256": "23b42743ef34cbe53dc24bef1fe2924a5d1382f6d3dcbaa216c0146f3f192494",
          "sha1": "482ad58c85a77efe5f698f7af2d9ac1c1b728978",
          "md5": "6e8aebdb9ca6fab35e1cf4dfcd23568d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-property-kotlin-6.0.0-LOCAL-sources.jar",
          "url": "kotest-property-6.0.0-LOCAL-sources.jar",
          "size": 105829,
          "sha512": "2be6d603df2c4272a5a0f53e5e9310b1973a547f583fb6f6b58f90ff69ff210f3b33e4443f0abd7f1f012ffd0aeba99e6c95f1c8d327a05c902c7ab72bb813db",
          "sha256": "08391eba709d798f95a1846629d00251fc6bc79cba3ab565d137a201bb45c1ab",
          "sha1": "a76a88bebbc6d48e3cdcb660e8b5dd3bf1f18864",
          "md5": "0f604cd7e4df38e539c13f56224b8aeb"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-property-androidnativearm32/6.0.0-LOCAL/kotest-property-androidnativearm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-androidnativearm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-property-androidnativearm32/6.0.0-LOCAL/kotest-property-androidnativearm32-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-androidnativearm32",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-property-androidnativearm64/6.0.0-LOCAL/kotest-property-androidnativearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-androidnativearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-property-androidnativearm64/6.0.0-LOCAL/kotest-property-androidnativearm64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-androidnativearm64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-property-androidnativex64/6.0.0-LOCAL/kotest-property-androidnativex64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-androidnativex64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-property-androidnativex64/6.0.0-LOCAL/kotest-property-androidnativex64-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-androidnativex64",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-property-androidnativex86/6.0.0-LOCAL/kotest-property-androidnativex86-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-androidnativex86",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-property-androidnativex86/6.0.0-LOCAL/kotest-property-androidnativex86-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-androidnativex86",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-property-js/6.0.0-LOCAL/kotest-property-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-property-js/6.0.0-LOCAL/kotest-property-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-property-js/6.0.0-LOCAL/kotest-property-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-property-jvm/6.0.0-LOCAL/kotest-property-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-property-jvm/6.0.0-LOCAL/kotest-property-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-property-jvm/6.0.0-LOCAL/kotest-property-jvm-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-jvm",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-property-wasm-js/6.0.0-LOCAL/kotest-property-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-property-wasm-js/6.0.0-LOCAL/kotest-property-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-property-wasm-js/6.0.0-LOCAL/kotest-property-wasm-js-6.0.0-LOCAL.module",
        "group": "io.kotest",
        "module": "kotest-property-wasm-js",
        "version": "6.0.0-LOCAL"
      }
    }
  ]
}
