{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "conventions",
    "version": "1.9.10+20230828",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.0-dev-228"
          }
        }
      ],
      "files": [
        {
          "name": "conventions-1.9.10+20230828.jar",
          "url": "conventions-1.9.10+20230828.jar",
          "size": 99765,
          "sha512": "a4989865a9952aaca975154ec8859ab8fa95b97f7d96e3bb63ad31a17aef2c8346924aaed018040cc2a15b497604389b493b97839021459f4a49e18d341570c0",
          "sha256": "bcdddce31f2e8cf7cfabe2d1d14b7450cf9c82f69c52af22fc1e701f03908c0f",
          "sha1": "af14265598b959bafa9aa1a9cb3f291bb8e1a1d4",
          "md5": "9b9fcf46b55d6c00801d31dec8469427"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.0-dev-228"
          }
        }
      ],
      "files": [
        {
          "name": "conventions-1.9.10+20230828.jar",
          "url": "conventions-1.9.10+20230828.jar",
          "size": 99765,
          "sha512": "a4989865a9952aaca975154ec8859ab8fa95b97f7d96e3bb63ad31a17aef2c8346924aaed018040cc2a15b497604389b493b97839021459f4a49e18d341570c0",
          "sha256": "bcdddce31f2e8cf7cfabe2d1d14b7450cf9c82f69c52af22fc1e701f03908c0f",
          "sha1": "af14265598b959bafa9aa1a9cb3f291bb8e1a1d4",
          "md5": "9b9fcf46b55d6c00801d31dec8469427"
        }
      ]
    }
  ]
}
