{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.0.0+20240603",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240603"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.0-1.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.0+20240603.jar",
          "url": "k2-2.0.0+20240603.jar",
          "size": 10399,
          "sha512": "02d82651b7ee49219d4ba0c76ff82175470e38b527394299f3fa59a2fc3be75e165641ca9589a4a25dfd3e3572952257f6cddd933ff79edba3072057df445de1",
          "sha256": "12db97f03f189060045a4873fe1c73bffd86228fb57c762ea3ff8b2e6af14089",
          "sha1": "600382a260a18b7ab2ab7b9d9b32290c9b898eed",
          "md5": "100f17175e9240e34ebe4b13be380d3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20240603"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.0-1.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.0.0+20240603.jar",
          "url": "k2-2.0.0+20240603.jar",
          "size": 10399,
          "sha512": "02d82651b7ee49219d4ba0c76ff82175470e38b527394299f3fa59a2fc3be75e165641ca9589a4a25dfd3e3572952257f6cddd933ff79edba3072057df445de1",
          "sha256": "12db97f03f189060045a4873fe1c73bffd86228fb57c762ea3ff8b2e6af14089",
          "sha1": "600382a260a18b7ab2ab7b9d9b32290c9b898eed",
          "md5": "100f17175e9240e34ebe4b13be380d3d"
        }
      ]
    }
  ]
}
