{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251108/testhelper-20251108.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251108",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-macosX64Main-20251108.klib",
          "url": "testhelper-macosx64-20251108.klib",
          "size": 6098,
          "sha512": "a9721d4e343cbceb7081d90f4302b66e8c4f957c40c29285bc9794ff9629efac0cd555e46f17d91e18467cf76d1286dcf666df3bde918530453021364423756b",
          "sha256": "972c269d996295b0f35e0839ac6268034bcfe74c7d742c18a7b29f44d9dcf69d",
          "sha1": "31ce632b78ea8c16214d2b3a1c650727cd7bcc38",
          "md5": "d30aca561f51440678f6d9c51e2bdd2b"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-macosx64-20251108-sources.jar",
          "url": "testhelper-macosx64-20251108-sources.jar",
          "size": 1883,
          "sha512": "a0c7cd3b3b28351e8ca472900b8d4766b7500519ee07d1afeebc10f68677266ab9be7d4c775fe10aacba9ee168e36a999600b00b30a5e12ec550966614b2c7d7",
          "sha256": "62b8fda7e77997d88add60ff5e498859e5c6626ab710fcaf4a5842fa0e8d9849",
          "sha1": "191ec1bea72b8bf42746a070783ffe2fa42ab055",
          "md5": "5553b412f52f7eec93e436d8042f47b3"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-macosx64-20251108-metadata.jar",
          "url": "testhelper-macosx64-20251108-metadata.jar",
          "size": 261,
          "sha512": "d2baf18c2f50fbaf6cbcd442e42769de537cc1a81d2352faae0c65fde06ff655b7b35bca2c0419e3de1402c9e0f6f1b4a2f61a924df515321e7def65b4d4ce80",
          "sha256": "0e9b236656ddfce88319a0a115f4b246e14ccabe09d1ad0489b4ef016f8c6e5f",
          "sha1": "6beb1c2fbecbd10ad1e4fb19b31bb275c6cad651",
          "md5": "24652dd36df51cdc0a24532ce0ff058e"
        }
      ]
    }
  ]
}
