{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/0.0.1/kmpotest-0.0.1.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-macosX64Main-0.0.1.klib",
          "url": "kmpotest-macosx64-0.0.1.klib",
          "size": 38163,
          "sha512": "f872358bbca5bd6ad04bf925177f55431fa8b88659b44d449c417bc4eb1ed01bbb00d0fcffe2c979aaa43e12f7daf2e1b2445c08c4adbe697119c4feafaafe0c",
          "sha256": "a5eb421fa1ef2c989f23c0c3fc610eac389591c2bf3814f44037aa4d507538e0",
          "sha1": "fd09781ec854998312a5dac2cfc26f764abe02d1",
          "md5": "e32a1fe56ae3a2e317430b3fcd526467"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-macosx64-0.0.1-sources.jar",
          "url": "kmpotest-macosx64-0.0.1-sources.jar",
          "size": 3842,
          "sha512": "7558ba403a569c00e5fb0c0f860c03d749b3175822fbdfa06a5d7672b5b075f3a04a1149016f41d91af608914546185e303cddfe3ac32de4e43b9295f116ea4a",
          "sha256": "14ca287394c99d9c2f8bdb60b98670f50c25882d51af24637bc9e160b2f9317b",
          "sha1": "cc15e6664ce98f3046c5db1fd6bd0ae6f7b66141",
          "md5": "5973c51ee2a400cbfdbbdaa1986f5319"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-macosx64-0.0.1-metadata.jar",
          "url": "kmpotest-macosx64-0.0.1-metadata.jar",
          "size": 261,
          "sha512": "e75ce590209d34b7fb2b87c7f7f89466f5b9f06f89cf26c89fe95f612b5c65a01cb69d4726d89eca5ca12d2ab9565db5c5a8e5772e249a0f5ce105a31afa3000",
          "sha256": "444106c7773e9322fb4f03dfdb825bf7f872da1235cbd5a93d21753e2f07a715",
          "sha1": "2401488e4a09f938d389bb953c46d20b35bfae74",
          "md5": "b4f8ac6e4679ba8dc4ebaebb52ccfb04"
        }
      ]
    }
  ]
}
