{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions-junit5/6.0.0-LOCAL/kotest-extensions-junit5-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-extensions-junit5",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-junit5-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-junit5-jvm-6.0.0-LOCAL.jar",
          "size": 11146,
          "sha512": "bbc46d7e918f3b211f553a901d9f63d10bd5ed1c001c53fdd6d6d023bb368dd10dc761664e611684b850b77f75522b2147ccc42cec0dcb754d9775fc819eeb60",
          "sha256": "9f7f7dbcf20e01e9f8e76fd94a716ab93f7a5d8936e223aac7c0a909fa256efb",
          "sha1": "c22c1bf73809e9803b993336dd7762ee2ba440c7",
          "md5": "05cd3f280e31c2863bb850763c1d3eae"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-junit5-jvm-6.0.0-LOCAL.jar",
          "url": "kotest-extensions-junit5-jvm-6.0.0-LOCAL.jar",
          "size": 11146,
          "sha512": "bbc46d7e918f3b211f553a901d9f63d10bd5ed1c001c53fdd6d6d023bb368dd10dc761664e611684b850b77f75522b2147ccc42cec0dcb754d9775fc819eeb60",
          "sha256": "9f7f7dbcf20e01e9f8e76fd94a716ab93f7a5d8936e223aac7c0a909fa256efb",
          "sha1": "c22c1bf73809e9803b993336dd7762ee2ba440c7",
          "md5": "05cd3f280e31c2863bb850763c1d3eae"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-extensions-junit5-jvm-6.0.0-LOCAL-sources.jar",
          "url": "kotest-extensions-junit5-jvm-6.0.0-LOCAL-sources.jar",
          "size": 3133,
          "sha512": "925c35bf7802ff41814b66bc5fc647de3cc9c1dd935787971aa275fe260d041217dfa2fb9cc34df18365aa9f308b12583504737da18ea3f790e1c5a396c3c56f",
          "sha256": "7bb47fe9834dfe941c2c060b2c3550d9dda10601684a7f70aa4b91e1ec6cb393",
          "sha1": "26be4c79c7eeaca0cdbee80c71c65ee93188933d",
          "md5": "b356cf041321c599e44ace390170ff29"
        }
      ]
    }
  ]
}
