{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-jvm-202509019.jar",
          "url": "testballoon-shim-jvm-202509019.jar",
          "size": 26707,
          "sha512": "4e0f5ac63ac196450a087e65a64a72b39d8ce8dd6196deb50a04d4f8c09541813c16a7f241ee2fc19875fc69f0d40b382124c79180f77ab67e609f05d08b4c4b",
          "sha256": "ac2cfdc0d92eab71374aa9820b018fda33b01ef7965982c7ad2a43ec638f0e0f",
          "sha1": "c8a362cabdd9906488c7e72ddad0cbc8705d7f53",
          "md5": "ead9c1e6befc07adec9b65130e998dc4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-jvm-202509019.jar",
          "url": "testballoon-shim-jvm-202509019.jar",
          "size": 26707,
          "sha512": "4e0f5ac63ac196450a087e65a64a72b39d8ce8dd6196deb50a04d4f8c09541813c16a7f241ee2fc19875fc69f0d40b382124c79180f77ab67e609f05d08b4c4b",
          "sha256": "ac2cfdc0d92eab71374aa9820b018fda33b01ef7965982c7ad2a43ec638f0e0f",
          "sha1": "c8a362cabdd9906488c7e72ddad0cbc8705d7f53",
          "md5": "ead9c1e6befc07adec9b65130e998dc4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "testballoon-shim-jvm-202509019-sources.jar",
          "url": "testballoon-shim-jvm-202509019-sources.jar",
          "size": 3131,
          "sha512": "2baa7304b68929b5b56d28717658736d37602ff88264297fd4ba8c689ec282a2d0757b95f962a87547c916fb981dc774f97cbeebf463651c68875370223262ce",
          "sha256": "975188b6d320d8d214fd2eceeb99a46af87468efcd1c7fd71014a74455e8bc21",
          "sha1": "80fba31de089827814f1fc51c1b7cd293498ee7d",
          "md5": "8eee823120e4de2fd7d4435cec124f11"
        }
      ]
    }
  ]
}
