{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "conventions",
    "version": "1.9.10+20230823",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.0-dev-228"
          }
        }
      ],
      "files": [
        {
          "name": "conventions-1.9.10+20230823.jar",
          "url": "conventions-1.9.10+20230823.jar",
          "size": 99765,
          "sha512": "f282b996a6def67d87248c9986cde23e0ef9714f89ab95739234fc1e095fa76b6d1dc9813815007dd6715f7238a7f4499b775f8c9ad9ba3f62840719b6475710",
          "sha256": "8743d463405fe29bc03c36296c8b53d9796341515c73d3f403cc6b421d29dca5",
          "sha1": "d8de2ffb26ba07ec6b16954b1b6911c85d7bc449",
          "md5": "8d5b3be78ceddd97eedcbe81bd90ca2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.0-dev-228"
          }
        }
      ],
      "files": [
        {
          "name": "conventions-1.9.10+20230823.jar",
          "url": "conventions-1.9.10+20230823.jar",
          "size": 99765,
          "sha512": "f282b996a6def67d87248c9986cde23e0ef9714f89ab95739234fc1e095fa76b6d1dc9813815007dd6715f7238a7f4499b775f8c9ad9ba3f62840719b6475710",
          "sha256": "8743d463405fe29bc03c36296c8b53d9796341515c73d3f403cc6b421d29dca5",
          "sha1": "d8de2ffb26ba07ec6b16954b1b6911c85d7bc449",
          "md5": "8d5b3be78ceddd97eedcbe81bd90ca2a"
        }
      ]
    }
  ]
}
