{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-yaml/6.0.0-LOCAL-PRE/kotest-assertions-yaml-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-assertions-yaml",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-yaml-jvm-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-assertions-yaml-jvm-6.0.0-LOCAL-PRE.jar",
          "size": 16185,
          "sha512": "d53da24415284a8edd1bfa67af4d139148d48219cf924eba54caf3c572efab8f271f9bafe6387776dfdb323d10556301162d43cd4a582566ba62d5eaa9cc8ebc",
          "sha256": "8179eabec73beca58743ee858f323838b9a94f11b736cdedf8a2f880c471458a",
          "sha1": "103ceb35d2348031b7dd478a8cf75c8b01970804",
          "md5": "06046060ddbe464bf7507e65dce8df57"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "com.charleskorn.kaml",
          "module": "kaml",
          "version": {
            "requires": "0.66.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-yaml-jvm-6.0.0-LOCAL-PRE.jar",
          "url": "kotest-assertions-yaml-jvm-6.0.0-LOCAL-PRE.jar",
          "size": 16185,
          "sha512": "d53da24415284a8edd1bfa67af4d139148d48219cf924eba54caf3c572efab8f271f9bafe6387776dfdb323d10556301162d43cd4a582566ba62d5eaa9cc8ebc",
          "sha256": "8179eabec73beca58743ee858f323838b9a94f11b736cdedf8a2f880c471458a",
          "sha1": "103ceb35d2348031b7dd478a8cf75c8b01970804",
          "md5": "06046060ddbe464bf7507e65dce8df57"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-assertions-yaml-jvm-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-assertions-yaml-jvm-6.0.0-LOCAL-PRE-sources.jar",
          "size": 1756,
          "sha512": "7c4df3857b3bec2081b35b3415adc081030f8720f8bea9bfe89f19f79ce10aa6baaf393d56d0384cb19387dc005874a5c743e96ef3fc5216827fb61c2f6412d2",
          "sha256": "c6bcc40dd3d8d253f046d136ca2a1bcf25bf1e16e71159d5bb7db36073c3d7ab",
          "sha1": "fe24caacc606dcffe382770e9ad3bb97138dca17",
          "md5": "97c9b6e287b878d83cc3fbcb567e48d7"
        }
      ]
    }
  ]
}
