{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-watchosSimulatorArm64Main-202509019.klib",
          "url": "testballoon-shim-watchossimulatorarm64-202509019.klib",
          "size": 19060,
          "sha512": "dbdf4992b3889cd93300a055bcc682e23f27089416eaedb7f3e5c235dfab493bf80b1d541151a998cba9653b5d209fef7dc6de665d6d63a5a0f6fc3908e98fa0",
          "sha256": "e649cb73580e62a5beb382996a35357941f6eccbd25b36585445223dcbd0d1a7",
          "sha1": "a2e74df06e222db48805584880aea74a45abc7f0",
          "md5": "6e4eaa75f3f984ab83bce3f6441277c5"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-watchossimulatorarm64-202509019-sources.jar",
          "url": "testballoon-shim-watchossimulatorarm64-202509019-sources.jar",
          "size": 3318,
          "sha512": "a9ca3c30563aa0860594b741a9809648cda8911ed66b7193abd79f2fbccef0a8150469c336bf81a00f9897b6b96fe454ad5354937580d3d1013ce96aefda655e",
          "sha256": "3c368969de27ae655f79ba8c64646f5f92877e88ed5479b198ce85810e0c852e",
          "sha1": "59a165aadb135c27c9a0911ccbb9f53ca93c8588",
          "md5": "ea04fd88b7a2e244263896ef71919b31"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-watchossimulatorarm64-202509019-metadata.jar",
          "url": "testballoon-shim-watchossimulatorarm64-202509019-metadata.jar",
          "size": 261,
          "sha512": "661cedce0f727efcae0a5aa8b1d29328806de84188e7b0fd5f086d199fa8f97f0bab508762277d24bf72e268f6cd3a8b99c6bd72d5508416564d1f2a42cbc2ec",
          "sha256": "ed288edfb4a40d3bcb61bfddee95fddb2cd52514ca05d948b6ab14fbb09a2a5a",
          "sha1": "659c386fa611a44e3eb0bfb24fe88242c24fbd22",
          "md5": "6cabdf8ccf52df4d49402098eaceaeb3"
        }
      ]
    }
  ]
}
