{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-core/0.6.3-K2.2.20-SNAPSHOT/testBalloon-framework-core-0.6.3-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-core",
    "version": "0.6.3-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-abstractions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-core-wasm-js-0.6.3-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-framework-core-wasm-js-0.6.3-K2.2.20-SNAPSHOT.klib",
          "size": 135300,
          "sha512": "7c78c494bc3773bfbf146b83797c0d7c1a469c9eceae4733f000ade9f9693f562bd4adf3a536353f17ef42d418e28d4f44b9733da36b22909ddf852f74882744",
          "sha256": "59b3519aaf35486ed4c5cc01e30e6ae0c9c64a9f40ff13306f26f0202389bec2",
          "sha1": "37edbc12c1a2fe66851e975032b307b5fb08f811",
          "md5": "10a7a76d663d9579ddfe430831f9e82c"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-abstractions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-core-wasm-js-0.6.3-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-framework-core-wasm-js-0.6.3-K2.2.20-SNAPSHOT.klib",
          "size": 135300,
          "sha512": "7c78c494bc3773bfbf146b83797c0d7c1a469c9eceae4733f000ade9f9693f562bd4adf3a536353f17ef42d418e28d4f44b9733da36b22909ddf852f74882744",
          "sha256": "59b3519aaf35486ed4c5cc01e30e6ae0c9c64a9f40ff13306f26f0202389bec2",
          "sha1": "37edbc12c1a2fe66851e975032b307b5fb08f811",
          "md5": "10a7a76d663d9579ddfe430831f9e82c"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "testBalloon-framework-core-wasm-js-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-core-wasm-js-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "size": 39761,
          "sha512": "caaa85e328c834e69a48b585ae7ea04af95e721ff50366daa7fbaa42592e58b4b6dcbddbe3b4a969336b82a3d7de5341a7f0b6e2d23880d99a6ac82fbb6a6502",
          "sha256": "6e58df89225989f0633adcfe59935eeaa0516d580e33e9b70675f3d45de01184",
          "sha1": "b47cc34eae113e817146d080adb300e4b4ad539d",
          "md5": "25a1ce9ebc08ae6a83cea5e3bd7ba94c"
        }
      ]
    }
  ]
}
