{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-common/6.0.0-LOCAL-PRE/kotest-common-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-common",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-common-androidNativeArm32Main-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-common-androidnativearm32-6.0.0-LOCAL-PRE.klib",
          "size": 28790,
          "sha512": "4d42acc2116134c49ed2e60c6310a681eed56a327a08e02f308e8d79d640be42d6d64a104678c7954179e3f4998cf38ce3b837664509b66b9d6028d0db4d773d",
          "sha256": "d56c2b6f9f695ce55111e886c19e21e840f68a4e512c0127079b63ccecb5a442",
          "sha1": "f6eeb43327c84ef0ed301d689e5ed7e2efa190e6",
          "md5": "5e1ec1d7a514991150cf183ba8ee6f39"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-common-androidnativearm32-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-common-androidnativearm32-6.0.0-LOCAL-PRE-sources.jar",
          "size": 8119,
          "sha512": "0caf444a201bf9d61f7d677787ee7974a0c20118a65e8c5293ed5291a9fa21a401f404ed7146d283da97d5716aaea0b0806d6388132bdfbcc830ed42183599c2",
          "sha256": "95156022732dac7ca3157a3c11c4f21f40344bf258b48115ac68bd7559ee4fc9",
          "sha1": "b1c173c573b0722ee82dfb3e1d2e1ed23292943e",
          "md5": "7d6e3d9f2e28eda894bd6561856eddac"
        }
      ]
    }
  ]
}
