{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251107/testhelper-20251107.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251107",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-iosArm64Main-20251107.klib",
          "url": "testhelper-iosarm64-20251107.klib",
          "size": 6097,
          "sha512": "75d80c3fdefb031db5a9eb1d6b1eb864c6cf6d33d55738adc3ebc746368a8d484c31f1b1324d5c12dc55a2a6e5bb5b548b0305e78645d3694d377946f750bce5",
          "sha256": "b87cc397442d26d6718524eee4ff7dd71b3580127f5d1adedd28bb3da7ce55ee",
          "sha1": "cf3520095afa0ab3cdf986efe264bd7d60d888c8",
          "md5": "e7684aa69c987a1e266191e921a6acf3"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-iosarm64-20251107-sources.jar",
          "url": "testhelper-iosarm64-20251107-sources.jar",
          "size": 1882,
          "sha512": "223146363b034f72e80f22f3c2d7c139c34537403ed2b8fbc2cf2535d076c6771642344b8478f4278fd6dd8d7c082996588d9fa117cc12906b50c37798dd54e9",
          "sha256": "4a0def48a8cb1197c7d99873ed10e34e53fb9b45d20afacb6d95da422018c23b",
          "sha1": "86b7004f9a47c1c6a92f4b0a260cccec64405d34",
          "md5": "08523c7036e4db905b90ac2f8a1d68aa"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-iosarm64-20251107-metadata.jar",
          "url": "testhelper-iosarm64-20251107-metadata.jar",
          "size": 261,
          "sha512": "0b0027930cb8d352d5b48e9d32cee950a5e1e30339ffe8c923e97f48130790b406d3b6c0e3ea2bea420106b039c3a1954f40ce4c37bab81fc85de76d3c18bbe7",
          "sha256": "9a42720af4be540038883e5b5969568f26400c63e817fe406c80b385e1a9c922",
          "sha1": "7491aff11527375b54c8a1d9c32736d65e2e4a94",
          "md5": "b226eeec11987387fb19a9ff5070f1d8"
        }
      ]
    }
  ]
}
