{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-macosArm64Main-202509019.klib",
          "url": "testballoon-shim-macosarm64-202509019.klib",
          "size": 18162,
          "sha512": "bb3687b28a1854d1cb72be2a4abc35049e57517ae46dde6e0d3def300a0e150658ed545917507173eda54add0ea3973ef570f4494d07dd58c48291d6aac1cfd1",
          "sha256": "990c35a768cd93a0dc63811f4ecd3b3d1abf5d527a259263b9f9e4ef3776fed3",
          "sha1": "49b0c3fad3fa3d1cee513b1da84bd01cd0ff5683",
          "md5": "4c41a29cc9eda3158b141f094e787490"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-macosarm64-202509019-sources.jar",
          "url": "testballoon-shim-macosarm64-202509019-sources.jar",
          "size": 3058,
          "sha512": "5b41504d5f9b840ac7c016f1d33dc5ca9b88c473f4d1a6b60a38f9e7c524526ec588f8feab24193a49d45c603037399fbe3e0ea370f511f97d079220b5dd3093",
          "sha256": "319a5367a54713cfbe294af9f15dfe06cf04da4d9678677d03e6ce92dfe082ba",
          "sha1": "39990eeb1fdc999f9f18c6c6ad78621f4ca0787c",
          "md5": "ce4a4a18e9895077f991df1a7a614fec"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-macosarm64-202509019-metadata.jar",
          "url": "testballoon-shim-macosarm64-202509019-metadata.jar",
          "size": 261,
          "sha512": "98e933395e45ea9589d31c65fa945977b36af2deea54a205e3401ee0c2635f0983d26de220a4308a129b787ac40dfcaf51cb3259e26ae33dfb5b8e4a2a279af0",
          "sha256": "24da81afa424083a7c666bf007b006640c400f21a6c4e002a5982387255e6402",
          "sha1": "d415b17a2bc1a696063fb8905e2a484726e74fa2",
          "md5": "1f932fad3bf235527429bf5959f3dbd5"
        }
      ]
    }
  ]
}
