{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-macosArm64Main-202509019.klib",
          "url": "testballoon-shim-macosarm64-202509019.klib",
          "size": 18993,
          "sha512": "b67c43d245c2cc1c069c3b89dca2dc6dc6c003918df7262077d406366aba6963e310d0a8dac2fcb3d1ea858546f612a32b7bc7fea5bfb01ea8a6baccde2bbaf9",
          "sha256": "d22f0bf19de0cf4feba7fd5af46c0c38a805a589cab7f3f01e7408a8ef503f85",
          "sha1": "7a14f6b40b7f7565572a0bff32631b8875b5b448",
          "md5": "f61e2610769e0e5d6a076817d0a4373a"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-macosarm64-202509019-sources.jar",
          "url": "testballoon-shim-macosarm64-202509019-sources.jar",
          "size": 3200,
          "sha512": "1531e3dacff32481aac8e98c48c7b4839bf66a2f0ddfc90415758e9df5c6ab4f3dbe4db1a4c938e186b2b6a2a1a98658d207d1286bae05c5cb2af0cf95990ce3",
          "sha256": "cca15791ca67e20511c61951f786802d7939d11637bb4cae190265f2eebe6285",
          "sha1": "039b08c9ddeed0ef7bbf442620a004a95ecb38c6",
          "md5": "3f412823def01b885a502a0c1b56cf6f"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-macosarm64-202509019-metadata.jar",
          "url": "testballoon-shim-macosarm64-202509019-metadata.jar",
          "size": 261,
          "sha512": "7c0c0e9bfb43d97beea34244fc1e893c67a3271642698bf1a90554f371e255f399aa425edceab35a0f0cefcdf968b27267ceae8cadc78a0c75bc3cdf13134f36",
          "sha256": "8b5ce1903a03897d41c8a1585537d832fe67c7cee830683d3d7a6acaaddb1d60",
          "sha1": "a81d4b6ecd23032950486b23f06b00eab981f286",
          "md5": "7a955626c6b3d425892e08d7801b71e9"
        }
      ]
    }
  ]
}
