{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-core/0.6.2-K2.2.20-SNAPSHOT/testBalloon-framework-core-0.6.2-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-core",
    "version": "0.6.2-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-abstractions",
          "version": {
            "requires": "0.6.2-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-core-androidNativeX64Main-0.6.2-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-framework-core-androidnativex64-0.6.2-K2.2.20-SNAPSHOT.klib",
          "size": 119518,
          "sha512": "73c5dfd0d3035ad47bd15d0450dc87488d2060ae53683f9abbde990d5eee6e2e116bef9ab2457b5f68220e8838a35b30d5838fbdf604a2e66742b9413ceba7c8",
          "sha256": "e061acfc24035f83ecc720b45425b9bb7d5c8020d7bebfed59b85839ecb151e4",
          "sha1": "8d6bb2dfec9795c4871043e6ee75dfefab0b550d",
          "md5": "c2152e3a2c2d820900d7ec3718f09263"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-framework-core-androidnativex64-0.6.2-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-core-androidnativex64-0.6.2-K2.2.20-SNAPSHOT-sources.jar",
          "size": 30228,
          "sha512": "87f7787caea4b58e401fd731502eb32b6f04ea749d3021587292a7c3d476a943db66d989081cfc0a463eec7ca99a049404301827db2fa11bddcaa423e86394ba",
          "sha256": "825546ef92c156ec8f59ea94f475637b69dfebd2ef9e603e8eb67b46140ce367",
          "sha1": "4efbc600da7916c46703b5ee6a491de33c57640a",
          "md5": "df2bd7575c4c94c635181fe57d7529c1"
        }
      ]
    }
  ]
}
