{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-core/6.0.0-LOCAL/kotest-assertions-core-6.0.0-LOCAL.module",
    "group": "io.kotest",
    "module": "kotest-assertions-core",
    "version": "6.0.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-core-watchosArm32Main-6.0.0-LOCAL.klib",
          "url": "kotest-assertions-core-watchosarm32-6.0.0-LOCAL.klib",
          "size": 532100,
          "sha512": "a1b199cacd3ffd2352839c85c6ae2db2485b34db263c20e3a3dbec9ec0f347b2592238b233a0b2b06ff467536cf45821279db51094d17e8d32801f61b5820ce0",
          "sha256": "346b9218bc63172958b68d9a173c9b8210086dd007221811a12024304289916e",
          "sha1": "c0a2dc3d17332cc0b6b51bfdcb5629e06e95ab9c",
          "md5": "684317839a77c9d9f96ca5591661d9d5"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-assertions-core-watchosarm32-6.0.0-LOCAL-sources.jar",
          "url": "kotest-assertions-core-watchosarm32-6.0.0-LOCAL-sources.jar",
          "size": 109376,
          "sha512": "ad4a435f76f66d310f8b2da246a2dad397b9be01a7cf475635a63e3f026078a7142e7b090e8183b026e48764324048d5d7ba855f5df840ef3b618dd7ce9c3f2d",
          "sha256": "2114d96ccc5ffc3bbc016e4eff19af3788d6748eff9c622607e1c1f6ac34936e",
          "sha1": "5d47dfa994b84d99bb3b1a5341dea75686a197dd",
          "md5": "845cda9bece8a927f987244bbba5d4cb"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-core-watchosarm32-6.0.0-LOCAL-metadata.jar",
          "url": "kotest-assertions-core-watchosarm32-6.0.0-LOCAL-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
