{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-androidNativeArm64Main-202509019.klib",
          "url": "testballoon-shim-androidnativearm64-202509019.klib",
          "size": 18139,
          "sha512": "0bf55233902d54543817e170a42784a45f32660f9227a95f266f0088105f66af574e54e783f04491ede83945e6ee1c1f5ac3fa4c7c9699efbc2a183137a3b746",
          "sha256": "9095553bb63f4ada00615f39baaa4919a61ccdf1692cd231b1a6136681afa9e8",
          "sha1": "b6d9e9a4e0ec45731a8ff5a37318cb6e81a9d32f",
          "md5": "5b06bb00eb7904f755d1c36a4b592522"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-androidnativearm64-202509019-sources.jar",
          "url": "testballoon-shim-androidnativearm64-202509019-sources.jar",
          "size": 3144,
          "sha512": "d5a849f088fb148587f7db93634077c890a799289face71cb748fa34e7b786bab9333c6e2acc5a1aa322cea67beb5164c0beec1f3853ac7ca08e45846d54cf3f",
          "sha256": "61ec20436afa23b9aa4ad4807899e1b952e85413c81cff05ad4be654ae014225",
          "sha1": "66ebeec44a7f9a093260063058e26bccdfa08d50",
          "md5": "b42ae4ec5a1d056bbbb96b80fa25370a"
        }
      ]
    }
  ]
}
