{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/202509019/testballoon-shim-202509019.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "202509019",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.0-K2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-androidNativeArm64Main-202509019.klib",
          "url": "testballoon-shim-androidnativearm64-202509019.klib",
          "size": 18979,
          "sha512": "2beda8ae3e6e38ee46fdd4eec414c8e40e383c24a4c7a879c1d0997ff62c3e61481540ccdf65bfd79385c8c24574a4ff4aea549ad2392b7a4cecf1e5d3e73a68",
          "sha256": "bc065f8632189027d279be028a82f127fe356a629e7f6b7e4ab66b97ec49a2a2",
          "sha1": "599070457407162f574e10ba9b05d8aeb37351c1",
          "md5": "617417517f4c235d236af7f287d249b3"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-androidnativearm64-202509019-sources.jar",
          "url": "testballoon-shim-androidnativearm64-202509019-sources.jar",
          "size": 3286,
          "sha512": "60cbf7a67e449938a573a9bd8e4a5b510ab085251c6a7da93cf518e4265e159adf5f0929b144e0406ec30e97d465fef0a808e26b27b1b8ef2bbbd6128b7327e1",
          "sha256": "8aea09ffc7735898f9ab4b7e1c10bd9bbc160fa2779b963e750e8868eac17920",
          "sha1": "87179ebf522620f3e1a1161037e79d05d3ded0a1",
          "md5": "fdb2f793277516630acf4602a0ed1541"
        }
      ]
    }
  ]
}
