{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-property/6.0.0-LOCAL-PRE/kotest-property-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-property",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-tvosSimulatorArm64Main-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-property-tvossimulatorarm64-6.0.0-LOCAL-PRE.klib",
          "size": 783121,
          "sha512": "f59692e7f8af00989fefd92b64b29a6169f2e389159370969169f11a1bee1b3571f9fe886f5b3fcf6ffbd6d7584d926b87c9cbfd33947ab82d0a9d87a4875d9d",
          "sha256": "14be1a05fa0b0d20ed28ea583d93f4a0890194f6ad3c0364f92552d7e6ecb7e5",
          "sha1": "dbb90a25fd147fac8799004e517f53ce1ba78ceb",
          "md5": "d2b8faa26c33eba15d390bba04d8fa7b"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-property-tvossimulatorarm64-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-property-tvossimulatorarm64-6.0.0-LOCAL-PRE-sources.jar",
          "size": 104410,
          "sha512": "e8bb801cddb72452ed072e8b781c464e067cf6e0180468b15e6b4fdd34fb83564c69fc32e98ea547353487237299e094ff14e58207673f2c894b0875ce4cb20e",
          "sha256": "fc649612ac43a12d2f5131f36adc73328b4747e5e658e7d224c5783ee6f40ee2",
          "sha1": "6b9f3cc7d279ebb9bb635410452140525df6eed4",
          "md5": "9e2593e855c104fa9eb0fa0fc29ad305"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.0-LOCAL-PRE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-property-tvossimulatorarm64-6.0.0-LOCAL-PRE-metadata.jar",
          "url": "kotest-property-tvossimulatorarm64-6.0.0-LOCAL-PRE-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
