{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-common/6.0.0-LOCAL-PRE/kotest-common-6.0.0-LOCAL-PRE.module",
    "group": "io.kotest",
    "module": "kotest-common",
    "version": "6.0.0-LOCAL-PRE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-common-mingwX64Main-6.0.0-LOCAL-PRE.klib",
          "url": "kotest-common-mingwx64-6.0.0-LOCAL-PRE.klib",
          "size": 28766,
          "sha512": "af60d3c12060b016240ef50b5585e9b578495e1b1c27a199982ba91fe1d7127ff8f984ee17579c7cecf61d80a3ef30fb33e23ee701a93ec459e502e0483c35fd",
          "sha256": "8d26851b771455e72bd6bffda88353e0068681ced883e3fd6ae3291145ae4c29",
          "sha1": "2fb20512683d7c74eac8e9dfcd67dcef8d09cbf4",
          "md5": "3acb6eb56dfae6b82e8c94d6aee65f34"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotest-common-mingwx64-6.0.0-LOCAL-PRE-sources.jar",
          "url": "kotest-common-mingwx64-6.0.0-LOCAL-PRE-sources.jar",
          "size": 8119,
          "sha512": "0caf444a201bf9d61f7d677787ee7974a0c20118a65e8c5293ed5291a9fa21a401f404ed7146d283da97d5716aaea0b0806d6388132bdfbcc830ed42183599c2",
          "sha256": "95156022732dac7ca3157a3c11c4f21f40344bf258b48115ac68bd7559ee4fc9",
          "sha1": "b1c173c573b0722ee82dfb3e1d2e1ed23292943e",
          "md5": "7d6e3d9f2e28eda894bd6561856eddac"
        }
      ]
    }
  ]
}
