{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251114/testhelper-20251114.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-linuxX64Main-20251114.klib",
          "url": "testhelper-linuxx64-20251114.klib",
          "size": 6072,
          "sha512": "8a38ac447750f62c9cd257c34804ad3bcd37deace06cb650b1ee388f4a42133f5af943e85f7d1a955608c2bd6bd734a67568ade57df4068695f7cefa265f4775",
          "sha256": "8073d16cb53bf21c49d4f1da6e14c955456aadb768ae285afbb60c0c9478df25",
          "sha1": "e328923fafcaca5401d8ac4f3d6ca63e9af83d9a",
          "md5": "06f7217c32ced5ae1d6fb0854ccc2cd6"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-linuxx64-20251114-sources.jar",
          "url": "testhelper-linuxx64-20251114-sources.jar",
          "size": 1883,
          "sha512": "eadb6c2bbb01bf9a741968e4d34d7b4ac08aaabc0c4ff3c5b64a8a56b5a2be6c4e07f63b88df6e443f9c9bd10d6f6ed266b837aedee34f77b3235328c075c0ff",
          "sha256": "d3147435fc9c9b7dff68d26b72b6aa1a49e8453eb083d92aa42ebe861f492552",
          "sha1": "c097b354aa93ca0feae2355ed742c1ac17e8354a",
          "md5": "09be203bb0d898a778dece8b0ecbd8d3"
        }
      ]
    }
  ]
}
