{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmpotest/20250727/kmpotest-20250727.module",
    "group": "at.asitplus.gradle",
    "module": "kmpotest",
    "version": "20250727",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosDeviceArm64Main-20250727.klib",
          "url": "kmpotest-watchosdevicearm64-20250727.klib",
          "size": 39782,
          "sha512": "8540a14f823f5a9aa913749dadebc83e119d61f95c39999c08217ab513d835b774133e567cfabe977379a26e8fa6ead0ecf862d0a34771ec868e98ceb00edf2a",
          "sha256": "c60a5068b51bf8b24ddfcf00ae867eac991b4a5ccd9ff1757a3a96224df2cf39",
          "sha1": "02d10986c7da3b303ab6cec18c86e83b80c4439a",
          "md5": "7ff5484abf2234f61cccec342c2de054"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmpotest-watchosdevicearm64-20250727-sources.jar",
          "url": "kmpotest-watchosdevicearm64-20250727-sources.jar",
          "size": 4444,
          "sha512": "b9b4e3174b9bccbad3ff2418b62a1e291ef0056338181259bad535f514da875e270ff10b680052bcf5432adff0cd046efc1b1be961dc2a960ea4c6485b761c13",
          "sha256": "5fa65c73347fcbbcda166807c2912c86e1809b003bcb4f13cc1a4722f8eafc84",
          "sha1": "d9eeb3e05326f46085dfcebfd401c132d1c4a921",
          "md5": "84968b1a402cfb310eff2264b4f6af34"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.0.M6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmpotest-watchosdevicearm64-20250727-metadata.jar",
          "url": "kmpotest-watchosdevicearm64-20250727-metadata.jar",
          "size": 261,
          "sha512": "7d9558319d27a71e70e7bc1576543b3724856516cabc54944f051a2caa004e505d69e4f585b0e35875a63a252cce97ffb673d4f1eed298937e7d208afdb84bf0",
          "sha256": "1916f4af472e50ec6a46ca8843e21b2c6cd7e46ed78903d44f9173a09f59b21e",
          "sha1": "626f02b49cd4a58927795634da21d1eeedad7968",
          "md5": "2d28224cddf17cfed32eaa512718c084"
        }
      ]
    }
  ]
}
