{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testhelper/20251114/testhelper-20251114.module",
    "group": "at.asitplus.gradle",
    "module": "testhelper",
    "version": "20251114",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchosArm64Main-20251114.klib",
          "url": "testhelper-watchosarm64-20251114.klib",
          "size": 6103,
          "sha512": "e2247eceeeadb1448ac29d7fab0024315737bfe98dd5df5ab2d14f4e4e6fa2d520f513fb206ad6d0c5e068484b4a6d3f8d7102c9b24df83d77ce4117cd7d0d93",
          "sha256": "3115d8cc650b591a726c583009cb26e8224570ecb89d96ef803e57a17913b675",
          "sha1": "0d55a294112580a8b5e751415f4ed41fbd695013",
          "md5": "81f62d47515d8d7323fc89adb903dc0e"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testhelper-watchosarm64-20251114-sources.jar",
          "url": "testhelper-watchosarm64-20251114-sources.jar",
          "size": 1923,
          "sha512": "c4a92dd4ff93fb88841161e1e01cb9142123ef762c18ab5fefc503ea318ab3eb2bc921e18d3829b2a24343ab45831ce9e636e2ad71d9aafaa2ddf7b9e2471db0",
          "sha256": "a167f6daf826a1fbdb56ce41e671d1e24bff04c9971f2c0344d9c43a7e1804fe",
          "sha1": "9645721792088a9ed14553ee549586311b2e1062",
          "md5": "43c6f4e7033fb3d374b95de4241c490d"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "testhelper-watchosarm64-20251114-metadata.jar",
          "url": "testhelper-watchosarm64-20251114-metadata.jar",
          "size": 261,
          "sha512": "a6d3b112dbe7c3c0e4d3a191fbcee6000d0c14dba9fdd1823f414d421bd72641f1d076f96d4938bd7058c81caafc46ab5498033c52c3a2f9978d7ab7a24a3e6f",
          "sha256": "5d4e630e8ad270150dda33fbff0ea9cdfdb4798e29c6e47e3a2aada790962760",
          "sha1": "89904b12b1c600d46eb4f1b98717324ce6d82d38",
          "md5": "8e80af8e9953bd0e38e0462ebdf3d3da"
        }
      ]
    }
  ]
}
