# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on: workflow_dispatch

jobs:
  build:

    runs-on:  macos-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
       xcode-version: 16.2.0
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build Plugin
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Build KMPotest
      working-directory: kmpotest
      run: ./gradlew build


    - name: Package Plugin
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: publishAllPublicationsToGitHubRepository

    - name: Package KMPotest
      working-directory: kmpotest
      run: ./gradlew publishAllPublicationsToGitHubRepository

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Push Maven Artefacts
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'repo'
        destination_repo: 'a-sit-plus/gradle-conventions-plugin'
        destination_branch: 'mvn'
        user_email: 'plus@a-sit.at'
        user_name: 'asitplus'
        commit_message: 'Maven Release'
