{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testballoon-shim/20251017/testballoon-shim-20251017.module",
    "group": "at.asitplus.gradle",
    "module": "testballoon-shim",
    "version": "20251017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-iosSimulatorArm64Main-20251017.klib",
          "url": "testballoon-shim-iossimulatorarm64-20251017.klib",
          "size": 19919,
          "sha512": "7d24b3c481a4da7c9bc6fad5e9e5c003dbc7ee46b6473c639dd60e22032ee23c6b65b8307d1928233e83ede51dcbc9ea45f631ebf62463a109514af846d64c94",
          "sha256": "9de811d47c22e1cbadab42986b7199bcadfae2c279b73e2a75a5826c2ed8d3c1",
          "sha1": "f42de49ef56969104f2ef6c30fd4420d6c4e34d1",
          "md5": "3d628421c2c39852bf21b3624574352c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testballoon-shim-iossimulatorarm64-20251017-sources.jar",
          "url": "testballoon-shim-iossimulatorarm64-20251017-sources.jar",
          "size": 3439,
          "sha512": "8d54cff44b7b66276ac6331bc3ff4daf03186a603ebe468807b2b72589bb93c0478a541a4c2db00b34a31a7b0c739c0496cbbb3b2dc307e43b8fd42db1a79409",
          "sha256": "b4e1bf9924cfae79376e73bdff7e97f1e8a136637efc6d57d721cb1c972f2376",
          "sha1": "9d21430b7b98de30b56b6aa884bcc784555bd3cd",
          "md5": "7de4e4d752bc2ea9da7289355b036ed2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-property",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-integration-kotest-assertions",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testballoon-shim-iossimulatorarm64-20251017-metadata.jar",
          "url": "testballoon-shim-iossimulatorarm64-20251017-metadata.jar",
          "size": 261,
          "sha512": "aa70baad94b7c5ae611e53d4e546e7f89a058ee771617ac5cd0bcfab489efa7570b88cd20dc6f1ec3ac0b61a5830a85cfe75d34aeb55abcc810d61add4bef04c",
          "sha256": "c505b69f316759fb6197de9bb8ce2225fa5e2f15d8e6bc65bfa0d0bc7fcbd758",
          "sha1": "57f75660dee2c132beb7f3908327762beb4c444a",
          "md5": "f09fd8ae6ea68bc38b5ffe8c2cdba5fc"
        }
      ]
    }
  ]
}
