{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "legacy",
    "version": "1.9.10+20241204",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.10-1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-1.9.10+20241204.jar",
          "url": "legacy-1.9.10+20241204.jar",
          "size": 151757,
          "sha512": "acc7f234b3f0bdcd6ed59538538b24f2fca77f942567d911df6cfebe154a0d063e01ecbbe053ca410d03f5d1649212ba5b37ad48a854eb70259445e56650c558",
          "sha256": "a56cd8246fcac77b620310a34aaf42ee3ceacc4141e1bc7210538fe2f81e2e5e",
          "sha1": "d4fa520d68b411199cc1e28bab1b1bf5c937278e",
          "md5": "a328b39162d7fbde5299b3104dad3380"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "io.ktor.plugin",
          "module": "plugin",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.9.10-1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-1.9.10+20241204.jar",
          "url": "legacy-1.9.10+20241204.jar",
          "size": 151757,
          "sha512": "acc7f234b3f0bdcd6ed59538538b24f2fca77f942567d911df6cfebe154a0d063e01ecbbe053ca410d03f5d1649212ba5b37ad48a854eb70259445e56650c558",
          "sha256": "a56cd8246fcac77b620310a34aaf42ee3ceacc4141e1bc7210538fe2f81e2e5e",
          "sha1": "d4fa520d68b411199cc1e28bab1b1bf5c937278e",
          "md5": "a328b39162d7fbde5299b3104dad3380"
        }
      ]
    }
  ]
}
