{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-blocking-detection/0.6.3-K2.2.20-SNAPSHOT/testBalloon-integration-blocking-detection-0.6.3-K2.2.20-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-blocking-detection",
    "version": "0.6.3-K2.2.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.6.3-K2.2.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-androidNativeX86Main-0.6.3-K2.2.20-SNAPSHOT.klib",
          "url": "testBalloon-integration-blocking-detection-androidnativex86-0.6.3-K2.2.20-SNAPSHOT.klib",
          "size": 5387,
          "sha512": "dc59f82a1bead11a1232e5c67b973e8a3f81a44366d51d5e0118ea0871978b19fb6cd4e14a6d2205420bf92a2e988f4d0ef86effc40f9d281702271cf7e1c4ac",
          "sha256": "223b4d924ea0895f94d94a3b642df2042ccf152d4ca71d5594675732dcf98403",
          "sha1": "9de375578d62bc38438c079b3ef95163a4867dbd",
          "md5": "7ae95e336b723edd1db58832a1111dce"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-androidnativex86-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-blocking-detection-androidnativex86-0.6.3-K2.2.20-SNAPSHOT-sources.jar",
          "size": 2945,
          "sha512": "39e3fe2d09dea6d751c781c9d54c2842a097b0e2a250f1df01abef596da12daba9f9a32861f806a37955f2b86c658c90e0f6408a391dd83b23f3f0e98bce9450",
          "sha256": "dbafc44bb6acf30f004893b05f9105de88a0d9a62512048ce98f2a05fcdbb66c",
          "sha1": "18ff2f39110b3aef01c2c19e1a931081965bbd0a",
          "md5": "184265814655eb8c10190843abd92a1b"
        }
      ]
    }
  ]
}
