{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.gradle",
    "module": "k2",
    "version": "2.1.20-RC2+20241219",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20241219"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20-RC2"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M2"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.20-RC2+20241219.jar",
          "url": "k2-2.1.20-RC2+20241219.jar",
          "size": 10778,
          "sha512": "63e986e014445ea75617f2cba7012b72fc01489efae8eb957083d88e0fc7957c37083811fb0599c5a0c6a7b6f6e64fdf55aa63f1f07a0a2940bbb35539a2e5c8",
          "sha256": "d836d0422ec01bf15a11eed7b07ac1d72e17edd917d4bc1f655ab9c7bff228ec",
          "sha1": "1cae14e45107e7f098673519c0aa048c0974e25c",
          "md5": "a30b099f1d1486d85d0fa9c8ebf83277"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.gradle",
          "module": "legacy",
          "version": {
            "requires": "1.9.10+20241219"
          },
          "excludes": [
            {
              "group": "io.kotest",
              "module": "kotest-framework-multiplatform-plugin-gradle"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20-RC2"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-multiplatform-plugin-gradle",
          "version": {
            "requires": "6.0.0.M2"
          }
        }
      ],
      "files": [
        {
          "name": "k2-2.1.20-RC2+20241219.jar",
          "url": "k2-2.1.20-RC2+20241219.jar",
          "size": 10778,
          "sha512": "63e986e014445ea75617f2cba7012b72fc01489efae8eb957083d88e0fc7957c37083811fb0599c5a0c6a7b6f6e64fdf55aa63f1f07a0a2940bbb35539a2e5c8",
          "sha256": "d836d0422ec01bf15a11eed7b07ac1d72e17edd917d4bc1f655ab9c7bff228ec",
          "sha1": "1cae14e45107e7f098673519c0aa048c0974e25c",
          "md5": "a30b099f1d1486d85d0fa9c8ebf83277"
        }
      ]
    }
  ]
}
